<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
    <head>
	
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="content-style-type" content="text/css" />
        <meta http-equiv="content-script-type" content="text/javascript" />
        
        <title>Hamptons Babysitters</title>
        
        <link rel="stylesheet" type="text/css" href="css/black.css" media="screen, projection, tv" />
        <!--[if lte IE 7.0]><link rel="stylesheet" type="text/css" href="css/ie.css" media="screen, projection, tv" /><![endif]-->
		<!--[if IE 8.0]>
			<style type="text/css">
				form.fields fieldset {margin-top: -10px;}
			</style>
		<![endif]-->
		
		<script type="text/javascript" src="js/jquery-1.3.2.min.js"></script>
		<!-- Adding support for transparent PNGs in IE6: -->
		<!--[if lte IE 6]>
			<script type="text/javascript" src="js/ddpng.js"></script>
			<script type="text/javascript">
				DD_belatedPNG.fix('#nav #h-wrap .h-ico');
				DD_belatedPNG.fix('.ico img');
				DD_belatedPNG.fix('.msg p');
				DD_belatedPNG.fix('table.calendar thead th.month a img');
				DD_belatedPNG.fix('table.calendar tbody img');
			</script>
		<![endif]-->
		<script type="text/javascript">
			$(document).ready(function() {
			    // Search input text handling on focus
					var $searchq = $("#search-q").attr("value");
				    $('#search-q.text').css('color', '#999');
					$('#search-q').focus(function(){
						if ( $(this).attr('value') == $searchq) {
							$(this).css('color', '#555');
							$(this).attr('value', '');
						}
					});
					$('#search-q').blur(function(){
						if ( $(this).attr('value') == '' ) {
							$(this).attr('value', $searchq);
							$(this).css('color', '#999');
						}
					});
				// Switch categories
					$('#h-wrap').hover(function(){
							$(this).toggleClass('active');
							$("#h-wrap ul").css('display', 'block');
						}, function(){
							$(this).toggleClass('active');
							$("#h-wrap ul").css('display', 'none');
					});
				// Handling with tables (adding first and last classes for borders and adding alternate bgs)
					$('tbody tr:even').addClass('even');
					$('table.grid tbody tr:last-child').addClass('last');
					$('tr th:first-child, tr td:first-child').addClass('first');
					$('tr th:last-child, tr td:last-child').addClass('last');
					$('form.fields fieldset:last-child').addClass('last');
				// Handling with lists (alternate bgs)
					$('ul.simple li:even').addClass('even');
				// Handling with grid views (adding first and last classes for borders and adding alternate bgs)
					$('.grid .line:even').addClass('even');
					$('.grid .line:first-child').addClass('firstline');
					$('.grid .line:last-child').addClass('lastline');
				// Tabs switching
					$('#box1 .content#box1-grid').hide(); // hide content related to inactive tab by default
					$('#box1 .header ul a').click(function(){
						$('#box1 .header ul a').removeClass('active');
						$(this).addClass('active'); // make clicked tab active
						$('#box1 .content').hide(); // hide all content
						$('#box1').find('#' + $(this).attr('rel')).show(); // and show content related to clicked tab
						return false;
					});
			});
		</script>
		
    </head>
    <body>	
		<div id="container">
		  <div id="header">
		    <div id="logo"><img src="img/txt.gif" alt="" width="1" height="12" /><img src="img/logo.jpg" width="360" height="125" alt="Hamptons Babysitters" /></div>
            <div class="floatright"><a href="admin-home.html">ADMIN SECTION</a> | <a href="client-home.html">CLIENT SECTION</a> | <a href="sitter-home.html">BABYSITTER SECTION</a></div>
		  </div>
		  <div id="nav">
             <ul>
               <li><a href="admin-home.html">Home</a></li>
               <li><a href="admin-jobs.html">Jobs</a></li>
               <li><a href="admin-clients.html" class="sel">Clients</a></li>
               <li><a href="admin-babysitters.html">Babysitters</a></li>
             </ul>
          </div>
			<div class="inner-container">
				
				<!-- Main content – all content is within boxes. Feel free to add your boxes (see the examples on the bottom of this document) and your content within -->
				<div class="box box-100 altbox">
				  <div class="boxin">
				    <div class="header">
				      <h3>Clients</h3>
			        <a class="button" href="#">Add New Client&nbsp;»</a></div>
				    <div class="content">
				      <table cellspacing="0">
				        <thead>
				          <tr>
				            <td class="tc">Client</td>
				            <th>Available Credits</th>
				            <th>Open Requests</th>
				            <td class="tc">Completed Jobs</td>
				            <td class="tc">YTD Babysitter Fees</td>
				            <td class="tc">Primary Phone</td>
				            <td class="tc">Email</td>
				            <td class="tc">Location</td>
				            <td class="tc">Location</td>
			              </tr>
			            </thead>
				        <tbody>
				          <tr class="first">
				            <td class="tc"><a href="admin-clients-jobs.html">Vicku Dulai</a></td>
				            
				            <!-- .first for first row of the table (only if there is thead) -->
				            <th>6</th>
				            <th>4</th>
				            <th>4</th>
				            <td class="tc">$240</td>
				            <td class="tc">123456</td>
				            <td class="tc">email@email.com</td>
				            <td class="tc">Northfork</td>
				            <td class="tc"><input class="button altbutton" type="submit" value="View" onclick="javascript:window.location='admin-clients-jobs.html';" /></td>
				            <!-- a.ico-comms for comment-like backgrounds -->
			              </tr>
				          <tr>
				            <td class="tc"><a href="admin-clients-jobs.html">Vicku Dulai</a></td>
				            <th>5</th>
				            <th>3</th>
				            <th>3</th>
				            <td class="tc">$250</td>
				            <td class="tc">123456</td>
				            <td class="tc">email@email.com</td>
				            <td class="tc">Northfork</td>
				            <td class="tc"><input class="button altbutton" type="submit" value="View" onclick="javascript:window.location='admin-clients-jobs.html';" /></td>
			              </tr>
				          <tr>
				            <td class="tc"><a href="admin-clients-jobs.html">Kimberly</a></td>
				            <th>5</th>
				            <th>2</th>
				            <th>2</th>
				            <td class="tc">$250</td>
				            <td class="tc">123456</td>
				            <td class="tc">email@email.com</td>
				            <td class="tc">Sag Harbor</td>
				            <td class="tc"><input class="button altbutton" type="submit" value="View" onclick="javascript:window.location='admin-clients-jobs.html';" /></td>
			              </tr>
				          <tr>
				            <td class="tc"><a href="admin-clients-jobs.html">Vicku Dulai</a></td>
				            <th>5</th>
				            <th>1</th>
				            <th>1</th>
				            <td class="tc">$250</td>
				            <td class="tc">123456</td>
				            <td class="tc">email@email.com</td>
				            <td class="tc">Montauk</td>
				            <td class="tc"><input class="button altbutton" type="submit" value="View" onclick="javascript:window.location='admin-clients-jobs.html';" /></td>
			              </tr>
				          <tr>
				            <td class="tc"><a href="admin-clients-jobs.html">Kimberly</a></td>
				            <th>5</th>
				            <th>3</th>
				            <th>3</th>
				            <td class="tc">$250</td>
				            <td class="tc">123456</td>
				            <td class="tc">email@email.com</td>
				            <td class="tc">Quogue</td>
				            <td class="tc"><input class="button altbutton" type="submit" value="View" onclick="javascript:window.location='admin-clients-jobs.html';" /></td>
			              </tr>
			            </tbody>
			          </table>
				      <div class="pagination">
				        <!-- pagination underneath the box's content -->
				        <ul>
				          <li><a href="#">previous</a></li>
				          <li><a href="#">1</a></li>
				          <li><a href="#">2</a></li>
				          <li><strong>3</strong></li>
				          <li><a href="#">4</a></li>
				          <li><a href="#">5</a></li>
				          <li><a href="#">next</a></li>
			            </ul>
			          </div>
			        </div>
			      </div>
			  </div>
				<br clear="all" />
			</div><!-- .inner-container -->
            <div id="footer"></div>
		</div><!-- #container -->
		
    </body>
</html>