<?php
$errors = $this->subscribeForm->getMessages();
if(!empty($errors))$this->errorMessage='Error while create/update client! Please verify your fields';

foreach($errors as $key =>$err){
	
	$er[$key]=implode(', ',$err);
	
}
$errors = $er;
?>
<!-- <div class="inner-container">
    <div class="box box-100 altbox">
              <div class="boxin">
        <div class="header">
                  <h3><?php //echo $this->userInfo['firstname'].' '.$this->userInfo['lastname']?> - Buy Credits</h3>
                  <ul>
            <?php // include_once('tabs.phtml'); ?>
          </ul>
                </div>
        <div class="content pad20">-->
        
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <div class="fixed-position col-lg-12">
	                    <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
	                        <ul class="nav nav-tabs pull-left">
	                        <li>     
	                        	<span class="profile_name"><?php echo $this->userInfo['firstname'] . ' ' . $this->userInfo['lastname'] ?> </span>
	                        </li>
	                            <?php include_once('tabs.phtml'); ?>
	                        </ul>
	                    </header>
                    </div>
                    <div class="clearfix"></div>
                   
                    <!--end header fixes -->
                   <!--<div class="mar-top col-sm-12 text-right" style="float:right;"><span><b>Total Credits Purchased: </b><?php //echo $this->purchased_credits;?></span>&nbsp;&nbsp;&nbsp;&nbsp;<span><b>Total Available Credits: </b><?php //echo $this->total_avail_credits;?></span></div><br>  -->
				<div class="panel-body list_margin">
				<div class="clearfix">
                <div id="errors" class="emessage"></div>


					<?php
					if(!empty($this->paymentProfile) && isset($this->paymentProfile->client_payment_profile_id))
					{
						$href =  ADMIN_URL .'client/checkoutauto/clientpayment/'.$this->paymentProfile->client_payment_profile_id.'/client/'.$this->userid;
					}
					else
					{
						$href =  ADMIN_URL .'client/checkout/client/'.$this->userid;
					}
					?>

                <form class="cmxform form-horizontal tasi-form custom-form" id="subscribeform" enctype="multipart/form-data" method="post" action="<?php echo $href;?>">
                <section id="flip-scroll">       
                  <?php if(!empty($this->packages)){?>
				  <table class="table table-bordered table-striped table-condensed cf" id="selep">
					  <thead class="cf">
					 	 <tr>
							  <th>Select </th>
							  <th>Package </th>
							  <th>Credit</th>
							  <th>Price</th>
						</tr>
					  </thead>
				  
                 <tbody >
                                            <?php foreach ($this->packages as $pack) { ?>
                                                <tr>
                                                    <td class="text-center">
                                                    <div class="form-group radios">
                                                        <label class="label_radio" style="min-height:21px !important">
                                                            <input <?php echo $this->selectedPackage == $pack['package_id'] ? 'checked="checked"' : '' ?> type="radio" name="package"  value="<?php echo $pack['package_id'] ?>" class="form-control" />
                                                        </label>
                                                    </div>
                                                    </td>
                                                    <td> <?php echo $pack['package_name'] ?>  </td>
                                                    <td> <?php echo $pack['credits'] ?></td>
                                                    <td class="numeric"> <?php echo money_format('%.2n',$pack['price']) ?></td>
                                                </tr>
                                            <?php } ?>
                                            </tbody>
                  
                  </table>
                  
                  <?php }?>
                  </section>
                <!-- <input type="checkbox" value="free" name="checkout_type" title="No need of payment transaction" /> Free Purchase   -->
				<div class="btn-group" data-toggle="buttons">
                     <label class="btn btn-info chk ">
                         <input class="child_checkbox" id="free_checkout" autocomplete="off" type="checkbox" title="No need of payment transaction" value="free"  name="checkout_type" />
                         <span class="glyphicon glyphicon-ok"></span>
                     </label> Free Purchase
                </div>

				<?php
				if(!empty($this->paymentProfile) && isset($this->paymentProfile->client_payment_profile_id))
				{
					?>
					<div class="row-sm-12 mar-top" id="checkout_div">
						<input class="button btn btn-danger" type="submit" name="subscribesubmit" id="subscribesubmit" value="Buy"/>
						<input type="button" class="btn btn-default" value="Back " onclick="location.href='<?php echo ADMIN_URL .'client/checkoutauto/clientpayment/'.$this->paymentProfile->client_payment_profile_id.'/client/'.$this->userid;?>'"/>
					</div>

					<?php
				}
				else
				{
					?>
					<div class="row-sm-12 mar-top" id="checkout_div">
						<input class="button btn btn-danger" type="submit" name="subscribesubmit" id="subscribesubmit" value="Checkout"/>
						<input type="button" class="btn btn-default" value="Back " onclick="location.href='<?php echo ADMIN_URL .'client/subscription/client/'.$this->userid;?>'"/>
					</div>
					<?php
				}
				?>



				<div class="row-sm-12 mar-top hidden" id="free_div">
					<input class="button btn btn-danger" type="submit" name="subscribesubmit" id="subscribesubmitfree" value="Add"/>
					<input type="button" class="btn btn-default" value="Back " onclick="location.href='<?php echo ADMIN_URL .'client/subscription/client/'.$this->userid;?>'">
				</div>
	
	</form>
	</div>
</div>
</section>
</div>
</div>
</section>
</section>
                  
       <script type="text/javascript">
			$(function(){

				$('#start_date,#end_date').datepicker({
					ampm: true
				});
								
			});
		</script>
		


<script type="text/javascript" src="<?php echo SITE_URL?>resource/js/jquery-validator.js"></script>
<script type="text/javascript">
function selectSlots(){
	if($("input[name=package]:checked").val()=='custom'){
		$("#custom").slideDown();
		
		
	}else $("#custom").slideUp();
}
$(document).ready(function() {
	// validate signup form on keyup and submit
	var validator = $("#subscribeform").validate({
		errorLabelContainer: '#errors',
		rules: {	
			package: {
				required:true
			}/*,		
			slots: {
				required: function(){return $("input[name=package]:checked").val()=='custom'}
			},
			price: {
				required: function(){return $("input[name=package]:checked").val()=='custom'}
			}*/
			
		},
		messages: {
			package: {
				required: 'Please select a Package'
			}/*,
			slots: {
				required: 'Please enter credits'
			},
			price: {
				required: 'Enter the Amount'
			}*/
		},
		// the errorPlacement has to take the table layout into account
		errorPlacement: function(error, element) {
			//alert(element.attr('type'));
			if ( element.is(":radio") )
				error.appendTo( element.parent().next().next());
			else if ( element.is(":checkbox") )
				error.appendTo ( element.next() );
			else{
				error.appendTo( element.parent());
				
			}
		},
		// specifying a submitHandler prevents the default submit, good for the demo
		submitHandler: function() {
			//$("#login").submit();
			document.getElementById('subscribeform').submit();
		},
		// set this class to error-labels to indicate valid fields
		success: function(label) {
			// set &nbsp; as text for IE
			label.html("&nbsp;").addClass("checked");
		}
	});
	
	<?php 
	
	if(!empty($errors)){
		echo "validator.showErrors(".json_encode($errors).");";
	}
	?>
	
	//$("#login").valid();
	

	$(":radio[name=package]").change(function() {
    $("#selep label.r_on").removeClass("r_on"); //remove previous active class


        $(this).closest("label").addClass("r_on"); //add active to radio selected tr

        selectSlots();
});
	
	$('#free_checkout').change(function() {
        if($(this).is(":checked")) {
        	$('#checkout_div').addClass("hidden");
	    	$('#free_div').removeClass("hidden");
	    	$("#subscribeform").attr('action',"<?php echo ADMIN_URL.'client/buycredits/client/'.$this->userid ?>");
	  
        }
        else{
        	$('#checkout_div').removeClass("hidden");
	    	$('#free_div').addClass("hidden");
	    	$("#subscribeform").attr('action',"<?php echo ADMIN_URL.'client/checkout/client/'.$this->userid?>");
	    
            }
        
    });
});
</script>

