<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        <b>Checkout</b>
                    </header>
                    <div class="panel-body">


                        <div class="alert alert-info fade in">

                            <p><strong>Selected
                                    Package:</strong> <?php echo $this->packages[$this->selectedPackage]['package_name'] ?>
                            </p>

                            <p><strong>Amount:</strong> <?php echo $this->packages[$this->selectedPackage]['price'] ?>
                                USD</p>
                        </div>


                        <?php
 
                        if(!empty($this->paymentProfile) && isset($this->paymentProfile->client_payment_profile_id))
                        {
                        	$payid=$this->paymentProfile->client_payment_profile_id;
                        }
                        
                        $amount = $this->packages[$this->selectedPackage]['price'];
                        $fp_sequence = time();
                        echo getCreditCardForm($this->addresses, $this->userInfo, $this->selectedPackage,$payid);


                        ?>
                    </div>
                </section>
            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>


<script type="text/javascript">
    function changeState(th) {
        $.ajax({
            url: '<?php echo SITE_URL_HTTPS?>misc/stateoptions',
            data: {country_id: th.value},
            success: function (data) {
                $("#states").html(data);
            }
        });
    }
</script>

<?php
function getCreditCardForm($address, $userInfo, $package,$payid)
{
    $prefill = false;
    $hbSettings = new Hb_Settings();
    $states = $hbSettings->getStates();
    $countries = $hbSettings->getCountries();
    //$states =


    if($payid!=null&& $payid!='')
    {
    	//$hidden='';
    	//$checked='';
	$hidden='hidden';
    	$checked='checked';
    }
    else
    {
    	$hidden='hidden';
    	$checked='checked';
    }
    
    $form = '
        <style>
        fieldset {
            overflow: auto;
            border: 0;
            margin: 0;
            padding: 0; }

        fieldset div {
            float: left; }

        fieldset.centered div {
            text-align: center; }

        label {
            color: #183b55;
            display: block;
            margin-bottom: 5px; }

        label img {
            display: block;
            margin-bottom: 5px; }

        input.text {
            border: 1px solid #bfbab4;
            margin: 0 4px 8px 0;
            padding: 6px;
            color: #1e1e1e;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: inset 0px 5px 5px #eee;
            -moz-box-shadow: inset 0px 5px 5px #eee;
            box-shadow: inset 0px 5px 5px #eee; }



        </style>
        <form method="post" action="" class="cmxform form-horizontal tasi-form">
                <input type="hidden" name="x_userid" value="' . $userInfo['userid'] . '" />
                <input type="hidden" name="x_invoice_num" value="' . time() . '" />
            <input type="hidden" name="x_transactiontype" value="credit">
            <input type="hidden" name="x_admin" value="admin">
             <input type="hidden" name="package" value="' . $package . '">
<div style="margin-top:2%">
    <!--<strong>Credit Card Information</strong>-->
    </div>

            <div style="width:100%">

         
        <fieldset>

            <legend>Credit Card Information</legend>

                <div style="width:30%;">
                    <label>Credit Card Number</label>
                    <input placeholder="Credit Card Number" type="text" required="required" pattern="[0-9]*" title="This fields accepts only digits"  title="Please enter the valid digits" pattern=".{16,}*"   title="Enter valid card number" class="form-control" size="15" name="x_card_num" value="' . ($prefill ? '4111111111111111' : '') . '"></input>
                </div>



                <div style="width:10%;margin-left:8%">
                    <label>Exp.</label>
                    <input type="text" class="form-control" required="required" placeholder="MM/YY" pattern="[0-9]{2}/[0-9]{2}" title="Expiration date should be in the format of MM/YY" class="text" size="4" name="x_exp_date" value="' . ($prefill ? '04/17' : '') . '"></input>
                </div>

                <div style="margin-left:6%">
                    <label>CCV</label>
                    <input placeholder="CCV" maxlength="4" type="text" required="required" pattern="[0-9]{3,4}" title="This field should be atleast 3 digits" class="form-control" size="4" name="x_card_code" value="' . ($prefill ? '782' : '') . '"></input>
			</div>

 <div style="width:15%">
   <label>&nbsp;&nbsp;&nbsp;</label>


                    <a class="ico" href="https://www.dcporder.com/ccv.htm" onclick="window.open(\'https://www.dcporder.com/ccv.htm\' ,\'Creditcard\',\'menubar=0,resizable=false,width=600,height=400\');return false;" target="blank" title="click here to know what is ccv " alt="?">
                    <img src="' . SITE_URL . 'resources/img/question_icon.gif"  alt="what is ccv?"/>
                    </a>
                    </div>
                </div>


</fieldset>
<fieldset>
              <div class="btn-group clearfix mar-top '.$hidden.'" data-toggle="buttons">
                     <label class="btn btn-info chk ">
                         <input class="" id="save_card" autocomplete="off" type="checkbox" title="Saved CC info For Next Time" value="1"  name="save_card"  '.$checked.' />
                         <span class="glyphicon glyphicon-ok"></span>
                     </label>

                </div>
                  <div class="btn-group clearfix mar-top '.$hidden.'" data-toggle="buttons">
                      <label>Save CC Info</label>
                </div>

        </fieldset>


<div style="margin-top:2%">
           <!-- <strong>Billing Information</strong>-->
            <fieldset>
            <legend>Billing Information</legend>
                <div style="width:30%;">
                    <label class="mar-top" >First Name</label>
                    <input required="required" placeholder="First name" pattern="[a-zA-Z\s.,]+" type="text" class="form-control" size="15" name="x_first_name" value="' . $userInfo['firstname'] . '"></input>
                </div>
                <div style="width:30%;margin-left:8%" >
                    <label class="mar-top" >Last Name</label>
                    <input type="text" required="required" placeholder="Last name" pattern="[a-zA-Z\s.,]+" class="form-control" size="14" name="x_last_name" value="' . $userInfo['lastname'] . '"></input>
                </div>
            </fieldset>
            <fieldset>
                <div style="width:30%" >
                    <label class="mar-top">Address</label>
                    <input type="text" required="required" placeholder="Address" class="form-control" size="26" name="x_address" value="' . $address['streat_address'] . '"></input>
                </div>
                    <div style="width:30%;margin-left:8%" >
                    <label class="mar-top">City</label>
                    <input type="text" required="required" placeholder="City" pattern="[a-zA-Z\s.,]+" title="This field should be accept only alphabets" class="form-control" size="15" name="x_city" value="' . $address['city'] . '"></input>
                </div>
            </fieldset>
            <fieldset>
                <div style="width:30%">
                    <label class="mar-top">State</label>';
    $t = '';
    $form_state = '<select required="required" name="x_state" id="states" class="form-control">';

    foreach ($states as $state) {
        $t .= '<option ' . ($address['state'] == $state['zone_id'] ? 'selected="selected"' : '') . ' value="' . $state['code'] . '">' . $state['name'] . '</option>';
    }

    $form_state .= $t . '</select>';
    $form .= $form_state . '
                </div>
                <div style="width:30%;margin-left:8%" >
                    <label class="mar-top">Zip Code</label>
                    <input type="text" required="required" placeholder="Zipcode" class="form-control"  name="x_zip" value="' . $address['zipcode'] . '"></input>
                </div>
                 </fieldset>
 <fieldset>

                <div style="width:30%">
                    <label class="mar-top">Country</label>';
    $t = '';
    $form_country = '<select class="form-control" required="required" name="x_country" onchange="changeState(this);">';

    foreach ($countries as $country) {
        $t .= '<option ' . ($address['country'] == $country['country_id'] ? 'selected="selected"' : '') . ' value="' . $country['iso_code_2'] . '">' . $country['name'] . '</option>';
    }

    $form_country .= $t . '</select>';
    $form .= $form_country . '
                    </div>
            </fieldset><br>

</div>
            <input type="submit" name="buy" id="buy" class="btn btn-success" value="BUY" >
            <!--<input type="button" class="btn btn-info" value="Cancel" onclick="window.location=\'' . ADMIN_URL . 'client/subscription\'" class="button altbutton submit buy">-->
            <input type="button" class="btn btn-default" value="BACK " onclick="history.back();" class="button altbutton submit buy">
            <br/><br clear="all"/>
        </form>';
    return $form;
}

?>

