<?php
//echo '<pre>';
$errors = $this->childForm->getMessages();
//print_r($errors);
foreach ($errors as $key => $err) {
    $er[$key] = implode(', ', $err);
}
$errors = $er;
?>
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel clearfix">
                    <!--  <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
                        <ul class="nav nav-tabs pull-right">
                            <?php //include_once('tabs.phtml'); ?>
                        </ul>
                        <span class="hidden-sm wht-color"> <?php //echo $this->userInfo['firstname'] . ' ' . $this->userInfo['lastname'] ?> - Children</span>
                    </header>-->
                    <!--header fixes -->
                     <div class="fixed-position">
	                    <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
	                        <ul class="nav nav-tabs pull-left">
	                        <li>     
	                        	<span class="profile_name"><?php echo $this->userInfo['firstname'] . ' ' . $this->userInfo['lastname'] ?></span>
	                        </li>
	                            <?php include_once('tabs.phtml'); ?>
	                        </ul>
	                    </header>
	                     <div class="clearfix"></div>
	                 </div>
                    <!--end header fixes -->
                    <div class="panel-body list_margin">
                        <form class="cmxform form-horizontal tasi-form custom-form" id="childform" method="post" enctype="multipart/form-data" action="<?php echo $this->childForm->getAction() ?>" >

                            <?php if ($_SESSION['message'] != '') { ?>


                                <div style="color:#3C763D"><p><?php echo $_SESSION['message'] ?></p></div>

                                <?php unset($_SESSION['message']);
                            } ?>


                            <dl class="zend_form">
                                <section class="clearfix">

                                    <div class="col-sm-6">
                                        <h4><?php echo $this->childId > 0 ? 'Modify ' : 'Add ' ?>Child</h4>
                                        <div class="border-top m-bot20"></div>

                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Child's Name</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" name="<?php echo $this->childForm->child_name->getName() ?>" id="child_name" value="<?php echo $this->childForm->child_name->getValue() ?>" />
                                            </div>
                                        </div>
                                        
                                     	<div class="form-group ">
                                             <label class="control-label col-lg-3">Gender</label>
                                             <?php $sgender = $this->childForm->sex->getValue(); ?>
                                                <div class="col-lg-9">
                                                <select class="form-control" id="sex" name="sex">
                                                 <option value="" <?php if ($sgender == '') { ?> selected="selected" <?php } ?> >Select Gender</option>
                                                	 <?php foreach ($this->childForm->sex->getMultiOptions() as $key=>$value) { ?>
				                                        <option value="<?php echo $key; ?>"
				                                        <?php  if ($sgender == $key) { ?>
				                                                    selected="selected" <?php } ?>><?php echo $value; ?></option>
				                                            <?php } ?> 
                                				</select>
                                                </div>
                                        </div>
                                        
                                        <div class="form-group ">
                                            <label class="control-label col-lg-3">Date of Birth</label>
                                            <div class="col-lg-9">
                                                <div data-date-viewmode="years" data-date-format="mm/dd/yyyy"   class="input-group date default-date-picker-birth clearfix">
                                                    <input type="text" readonly size="16" class="form-control datep"  name="<?php echo $this->childForm->dob->getName() ?>" id="dob" value="<?php echo strtotime($this->childForm->dob->getValue()) > 0 ? date(DATE_FORMAT, strtotime($this->childForm->dob->getValue())) : '' ?>" >
                                                    <span class="input-group-btn" style="width: auto" id="btn">
                                                        <button type="button" class="btn btn-danger date-set tri"><i class="fa fa-calendar"></i></button>
                                                    </span>
                                                </div> 
                                                 <div>   
                                                </div>

                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Allergies</label>
                                            <div class="col-lg-9 radiop">
                                                <label class="label_radio" for="radio-13">
                                                    <input  id="radio-13" <?php echo $this->childForm->allergy_status->getValue() == 'Yes' ? 'checked="checked"' : '' ?> class="form-control " type="radio" name="allergy_status" value="Yes"> Yes 
                                                </label>
                                                <label class="label_radio" for="allergy_status">
                                                    <input <?php echo $this->childForm->allergy_status->getValue() == 'No' ? 'checked="checked"' : '' ?> class="form-control" type="radio"  name="<?php echo $this->childForm->allergy_status->getName() ?>" id="allergy_status" value="No" > No 
                                                </label>
                                                <div class="clearfix"></div> 
                                                <div class="col-lg-9 allergies_text" style="display:<?php echo $this->childForm->allergy_status->getValue() == 'Yes' ? 'block' : 'none' ?>">
                                                    <!--                                             <label>-->
                                                    <textarea placeholder="Allergies can be life threatening. Please describe in detail. " name="allergies" id="allergies"class="form-control"><?php echo $this->childForm->allergies->getValue() ?></textarea>
                                                    <div>     
                                                        <small>Allergies can be life threatening. Please describe in detail. 
                                                        </small>     
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Medication</label>
                                            <div class="col-lg-9 radiop">
                                                <label class="label_radio" for="radio-15">
                                                    <input  id="radio-15"  class="form-control" type="radio"  name="medicator_status" value="Yes" <?php echo $this->childForm->medicator_status->getValue() == 'Yes' ? 'checked="checked"' : '' ?> > Yes 
                                                </label>
                                                <label class="label_radio" for="radio-14">
                                                    <input  id="radio-14" class="radio" type="radio" name="medicator_status" value="No" <?php echo $this->childForm->medicator_status->getValue() == 'No' ? 'checked="checked"' : '' ?> > No 
                                                </label>
                                                <div class="clearfix"></div> 
                                                <div class="col-lg-9 medicator_text" style="display:<?php echo $this->childForm->medicator_status->getValue() == 'Yes' ? 'block' : 'none' ?>">
                                                    <!--                                             <label>-->
                                                    <textarea placeholder="List all medications" name="medicator" id="medicator" class="form-control"><?php echo $this->childForm->medicator->getValue() ?></textarea>
                                                    <div>
                                                        <small>List all medications </small>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        
                                        <div class="form-group ">
                                             <label class="control-label col-lg-3">Special Needs</label>
                                             <?php $sneeds = $this->childForm->special_needs->getValue(); ?>
                                                <div class="col-lg-9">
                                                <select class="form-control" id="special_needs" name="special_needs">
                                                 <option value="" <?php if ($sneeds == '') { ?> selected="selected" <?php } ?> >Select if any</option>
                                                	 <?php foreach ($this->childForm->special_needs->getMultiOptions() as $needs) { ?>
				                                        <option value="<?php echo $needs['special_need']; ?>"
				                                        <?php  if ($sneeds == $needs['special_need']) { ?>
				                                                    selected="selected" <?php } ?>><?php echo $needs['special_need']; ?></option>
				                                            <?php } ?> 
                                				</select>
                                                </div>
                                        </div>

                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Favorite Food</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" name="fav_food" id="fav_food" value="<?php echo $this->childForm->fav_food->getValue() ?>" />
                                            </div>
                                        </div>
                                        
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Favorite Book</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" name="fav_book" id="fav_book" value="<?php echo $this->childForm->fav_book->getValue() ?>" />
                                            </div>
                                        </div>
                                        
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Favorite Cartoon</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" name="fav_cartoon" id="fav_cartoon" value="<?php echo $this->childForm->fav_cartoon->getValue() ?>" />
                                            </div>
                                        </div>
                                        
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Helpfull hints</label>
                                            <div class="col-lg-9">
                                                <textarea name="notes" id="notes" class='form-control'><?php echo $this->childForm->notes->getValue() ?></textarea>
                                                <small>(ie. Billy loves Thomas the Tank Engine and  needs Teddy for naps)  </small> </dd>
                                            </div>
                                        </div>


                                        <div class="form-group ">
                                            <label class="control-label col-lg-3">Upload Picture</label>
                                            <div class="col-lg-9">
                                                <input type="hidden" name="MAX_FILE_SIZE" value="8388608" id="MAX_FILE_SIZE">
                                                <input class="file" type="file" id="image" name="image" />


                                            </div>
                                        </div>

                                        <div class="form-group clearfix">
                                            <div class="m-bot20 m-top20">
                                                <input class="btn btn-danger" type="submit" value="Save" />
                                                <input class="btn btn-default" type="reset"  value="Cancel" onclick="window.location = '<?php echo SITE_URL ?>client/children/parent/<?php echo $this->userid ?>'"/>

                                            </div>
                                        </div>




                                    </div>
                                    <div class="col-sm-6">
                                        <h4>Children</h4>
                                        <div class="border-top m-bot20"></div>
                                        <div class="">

                                            <?php if (!empty($this->children)) { ?>  
                                                    <?php foreach ($this->children as $child) { ?>
                                                    <div class="Children_pic col-sm-3">
                                                        <?php if ($child['thumb_image'] != '') { ?>
                                                            <img src="<?php echo SITE_URL . $child['thumb_image'] ?>"  />
                                                        <?php } else { ?>
                                                            <img alt="No Image" src="<?php echo SITE_URL . 'resource/img/noimage.jpg' ?>"  />
        <?php } ?>                                


                                                    </div>
                                                    <div class="bio-desk col-sm-9">
                                                        <h4 class="terques"><?php echo $child['child_name'] ?> </h4>
                                                        <p><b>Age: </b> <?php echo $this->age($child['dob']) ?></p>
                                                        <p><b>Allergies: </b><?php echo $child['allergy_status'] ?></p>
                                                        <?php if ($child['allergy_status'] == 'Yes') { ?>	 
                                                            <?php echo $child['allergies'] ?><br /><br />
        <?php } ?>
                                                        <p><b>Medications: </b><?php echo $child['medicator_status'] ?></p>

                                                        <?php if ($child['medicator_status'] == 'Yes') { ?>	 
                                                            <?php echo $child['medicator'] ?><br /><br />
        <?php } ?>
        												<p><b>Special Needs: </b><?php echo $child['special_needs_status'] ?></p>

                                                        <?php if ($child['special_needs_status'] == 'Yes') { ?>	 
                                                            <?php echo $child['special_needs'] ?><br /><br />
        <?php } ?>
                                                        <p><b>Helpful Hints: </b>  <?php echo $child['notes'] ?></p>
                                                        <div>
                                                            <div class="col-sm-2">
                                                                <a class="btn btn-primary btn-xs" title="Edit" href="<?php echo ADMIN_URL . 'client/children/parent/' . $this->parent_id . '/modify/' . $child['child_id'] ?>"><i class="fa fa-pencil"></i></a>
                                                            </div>
                                                            <div class="col-sm-2">
                                                                <a class="btn btn-danger btn-xs"  onclick="if (confirm('Are you sure want to delete?'))
                                                                       return true;
                                                                   else
                                                                       return false;" title="Delete" href="<?php echo ADMIN_URL . 'client/children/parent/' . $this->parent_id . '/delete/' . $child['child_id'] ?>"><i class="fa fa-trash-o"></i></a>
                                                            </div> 

                                                        </div>



                                                    </div>
                                                    <div class="mar-bottom clearfix"></div>
                                                    <div class="border-top m-bot20"></div>    


                                                    <?php
                                                }
                                            }
                                            ?>       



                                        </div>

                                    </div>
                                </section>





                            </dl>
                        </form>
                    </div>
                </section>



            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<!--main content end-->

<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>
<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/additional-methods-new.min.js"></script>



<script type="text/javascript">
                                                       $(document).ready(function () {

                                                           // validate signup form on keyup and submit
                                                           $('input[name=allergy_status]').click(function (event) {
                                                               if (this.value == 'Yes')
                                                                   $('.allergies_text').slideDown();
                                                               else
                                                                   $('.allergies_text').slideUp();
                                                           });
                                                           $('input[name=medicator_status]').click(function (event) {
                                                               if (this.value == 'Yes')
                                                                   $('.medicator_text').slideDown();
                                                               else
                                                                   $('.medicator_text').slideUp();
                                                           });

                                                           var validator = $("#childform").validate({
                                                               rules: {
                                                                   child_name: {
                                                                       required: true
                                                                   },
                                                                   sex: {
                                                                       required: true
                                                                   },
                                                                   dob: {
                                                                       required: true
                                                                   },
                                                                   allergy_status: {
                                                                       required: true
                                                                   },
                                                                   medicator_status: {
                                                                       required: true
                                                                   },
                                                                   image: {
                                                                       required: false,
                                                                       accept: "image/*"
                                                                   },
                                                                   allergies: {
                                                                       required: function () {
                                                                           var status = $("input[name=allergy_status]:checked").val() == 'Yes';
                                                                           if (status)
                                                                               $(".allergies_text").show();
                                                                           return status;
                                                                       }
                                                                   },
                                                                   medicator: {
                                                                       required: function () {
                                                                           var status = $("input[name=medicator_status]:checked").val() == 'Yes';
                                                                           if (status)
                                                                               $(".medicator_text").show();
                                                                           return status;
                                                                       }
                                                                   },
                                                               },
                                                               messages: {
                                                                  child_name: {
                                                                            required: "Please enter your Child's Name."
                                                                        },
                                                                        sex: {
                                                                            required: "Please select your Child's Gender."
                                                                        },
                                                                        dob: {
                                                                            required: "Please provide your Child's Date Of Birth"
                                                                        },
                                                                        allergy_status: {
                                                                            required: 'Please select Allergy information '

                                                                        },
                                                                        medicator_status: {
                                                                            required: 'Please select Medication information'
                                                                        },
                                                                        image: {
                                                                            accept: 'Only jpeg/png/jpg/gif files are allowed'
                                                                        }


                                                               },
                                                               // the errorPlacement has to take the table layout into account
                                                               errorPlacement: function (error, element) {
                                                                   //alert(element.attr('type'));
                                                                   if (element.is(":radio"))
                                                                       // if (element.is(":radio"))
                                                                       error.appendTo(element.parent().next().next());
                                                                   // else
                                                                   // error.appendTo(element.parent());
                                                                   else if (element.is(":checkbox"))
                                                                       error.appendTo(element.next());
                                                                   
                                                                   else if (element.attr('id') == 'dob')
                                                                        error.appendTo(element.parent().next());
                                                                   else {

                                                                       error.appendTo(element.parent());

                                                                   }
                                                               },
                                                               // specifying a submitHandler prevents the default submit, good for the demo
                                                               submitHandler: function () {
                                                                   //$("#login").submit();
                                                                   document.getElementById('childform').submit();
                                                               },
                                                               // set this class to error-labels to indicate valid fields
                                                               success: function (label) {
                                                                   // set &nbsp; as text for IE
                                                                   label.html("&nbsp;").addClass("checked");
                                                               }
                                                           });

<?php
if (!empty($errors)) {
    echo "validator.showErrors(" . json_encode($errors) . ");";
}
?>

                                                           //$("#login").valid();


                                                       });
</script>

