<style>
    .cerror{
        color: #B94A48;

    }      

    .cerror_show{
        color: red;
        margin-left: 10px;
    }
    .modifyjob
    {
    	display:block;
    }
    .newjobpost
    {
    	display:none;
    }
</style>


<?php
//echo $this->event['job_status'];die;
$continueSubmit = true;
$childStyle = 'style="display:none"';

$errors = $this->eventsForm->getMessages();
if (!empty($errors))
    $this->errorMessage = 'Error while create/update jobs! Please verify your fields';

foreach ($errors as $key => $err) {
    if (!isset($err[0])) {
        foreach ($err as $key2 => $r)
            $er[$key . '[' . $key2 . ']'] = implode(', ', $r);
    } else
        $er[$key] = implode(', ', $err);
}
$errors = $er;
?>

<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <!--  <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
                        <ul class="nav nav-tabs pull-right"><?php //include_once('job-tabs.phtml'); ?></ul>
                        <span class="hidden-sm wht-color"> <?php //if ($this->searchParams['modify'] > 0) { ?> View Job <?php
                               //echo $this->jobnumber($this->searchParams['modify']);
                                //$cb=' modifyjob';
                            //} else {
                            	//$cb=' newjobpost';
                                ?>Add New Job<?php //} ?></span>
                    </header>
                    -->
                    <!--header fixes -->
                     <div class="fixed-position">
	                    <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
	                        <ul class="nav nav-tabs pull-left">
	                        <li>     
	                        	<span class="profile_name"> <?php if ($this->searchParams['modify'] > 0) { ?> View Job <?php
                                echo $this->jobnumber($this->searchParams['modify']);
                                $cb=' modifyjob';
                            } else {
                            	$cb=' newjobpost';
                                ?>Add New Job<?php } ?></span>
	                        </li>
	                            <?php include_once('job-tabs.phtml'); ?>
	                        </ul>
	                    </header>
	                     <div class="clearfix"></div>
	                 </div>
                    <!--end header fixes -->
                    
                    <div class="panel-body list_margin">

 <!--     //added later by namrata-->


                        <?php if ($this->event['job_start_date']) {
                            ?>
                            <?php $timediff = $this->timediff($this->event['job_start_date']); ?>

                            <?php if (!$timediff) {
                                ?>
                                <?php if (in_array($this->event['job_status'], array('new', 'pending'))) { ?>

                                    <div class="alert alert-warning fade in">
                                        Job Expired
                                    </div>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>


                        <?php if ((isset($child_error)) && (!empty($child_error))) { ?>
                            <div class="emessage"><?php echo $child_error; ?></div>
                        <?php } ?>


                        <?php if ($_SESSION['jobSuccess'] != '') { ?>
                            <div class="alert alert-success fade in">
                                <p> <?php
                                    echo $_SESSION['jobSuccess'];
                                    unset($_SESSION['jobSuccess']);
                                    ?></p>
                            </div>
                        <?php } ?>

                        <?php if ($this->searchParams['msg'] != '') { ?>
                            <div class="smessage">
                                <p>Your message was sent successfully</p>
                            </div>	
                        <?php }
                        ?>

                        <?php if (strtotime($this->event['jobs_posted_date']) > 0) { ?>
                            <div class="alert alert-info fade in">
                             <p><span><i class="fa fa-user"></i></span> Client Name: <span style="font-size: 15px;"><?php if($this->event['client_status']!='deleted'){?><a href="<?php echo ADMIN_URL ?>client/profile/modify/<?php echo $this->event['client_user_id'] ?>"><b><?php echo $this->event['firstname']." ".$this->event['lastname'];  ?></b></a><?php }else { ?> <a class="deleted_client"><b><?php echo $this->event['firstname']." ".$this->event['lastname'];  ?></b> </a><?php } ?></span></p>

                                <p><span><i class="fa fa-clock-o"></i></span> Job Posted Time: <?php echo date(DATETIME_FORMAT, strtotime($this->event['jobs_posted_date'])) ?></p>
                            </div>
                            <?php
                            $timeover = time() - strtotime($this->event['jobs_posted_date']) > 86400;
                            if ($timeover) {
                                ?>

                                <!--                                <div class="alert alert-success fade in">
                                                                    <p>We are currently processing your Job Request. At this time you are not allowed to modify job details.</p>
                                                                </div>-->

                            <?php } ?>
                        <?php } ?>

                        <?php if ($this->event['job_status'] == "cancelled") { ?>
                            <div class="alert alert-danger fade in">
                                <p>Job has been cancelled</p> <?php } ?>


                            <form class="cmxform form-horizontal tasi-form custom-form" id="eventsform" method="post" enctype="multipart/form-data" action="<?php echo $this->eventsForm->getAction(); ?>" >
                                <dl class="zend_form">
                                    <section class="clearfix">
                                        <div class="col-sm-6">
                                            <h4>Date and Time</h4>
                                            <div class="border-top m-bot20"></div>
                                            <div class="form-group ">
                                                <label class="control-label col-lg-3">Start Date/Time</label>
                                                <div class="col-lg-9">
                                                    <div class="input-group date dtimecustom" data-date-format="mm/dd/YY h:i a" startDate=""   data-date-viewmode="years">
                                                        <input type="text" name="start_date" id="start_date" value="<?php echo date(DATETIME_FORMAT, strtotime($this->eventsForm->start_date->getValue())) ?>"  class="form-control datep" readonly="" placeholder="Actual End Time">
                                                        <div class="input-group-btn">
                                                            <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                                        </div>
                                                    </div>
                                                    <div><small>Click on field to change date/time</small><br/>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group ">
                                                <label class="control-label col-lg-3">End Date/Time</label>
                                                <div class="col-lg-9">
                                                    <div class="input-group date dtimecustom" data-date-format="mm/dd/YY h:i a" data-date-viewmode="years">
                                                        <input type="text" name="end_date" id="end_date" value="<?php echo date(DATETIME_FORMAT, strtotime($this->eventsForm->end_date->getValue())) ?>" class="form-control datep" readonly="" placeholder="Actual End Time">
                                                        <div class="input-group-btn">
                                                            <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                                        </div>
                                                    </div>
                                                    <div><small>Click on field to change date/time</small><br/></div>
                                                </div>
                                            </div>
										<?php if(in_array($this->event['job_status'], array('new','pending','confirmed'))){
											$status_class = ' alert-info';
											}
											elseif(in_array($this->event['job_status'], array('completed','closed'))) 
											{
												$status_class = ' alert-success';
											}
											else {
												$status_class = ' alert-danger';
											}
										 ?>
										 <?php if($cb ==' newjobpost'){?>
                                           <div class="alert alert-success fade in" id="ok" style="display:none"></div>
                                            <div class="alert alert-block alert-danger fade in" id="error" <?php if ($this->errorMessageCredits == '') { ?>style="display:none" <?php } ?>><?php echo $this->errorMessageCredits ?></div>

                                             <div class="alert alert-info fade in" id="info">
                                                You have <strong><?php echo $this->credits ?> Credits  </strong> available. 
                                            </div><?php }else{ ?>
                                            <div class="alert<?php echo $status_class; echo $cb;  ?> fade in" id="info">
                                               Job Status: <strong><?php echo $this->event['jstatus'] ?></strong>
                                            </div><?php } ?>
                                            <h4>Location</h4>
                                            <div class="border-top m-bot20"></div>
                                            <div class="alert alert-block alert-danger fade in" id="other_error" style="display:none"></div>	

                                            <div class="radiop">
                                                <?php
                                                if (!empty($this->addresses)) {

                                                    $states = $this->eventsForm->other->state->getMultiOptions();
                                                    ?>
                                                    <?php foreach ($this->addresses as $address) { ?>
                                                        <div class="clearfix"></div>
                                                        <label class="label_radio" >
                                                            <input <?php echo $address['address_id'] == $this->selectedAddress || ((int) $this->selectedAddress <= 0 && $address['address_type'] == 'local' ) ? 'checked="checked"' : ''; ?> type="radio" name="address_id" value="<?php echo $address['address_id'] ?>" class="form-control" />
                                                            <strong><?php echo strtoupper($address['address_type']) ?> ADDRESS</strong>

                                                            <br />
                                                            <?php if ($address['billing_name'] != '') { ?>
                                                                <p><b>Hotel Name: </b> <?php echo $address['billing_name'] ?> </p> <?php } ?>
                                                            <?php if ($address['address_1'] != '') { ?>
                                                                <p><b>Cross Street: </b><?php echo $address['address_1'] ?> </p><?php } ?>
                                                            <p><b>Street Address: </b> <?php echo $address['streat_address'] ?> </p>
                                                            <p><b>City: </b><?php echo $address['city'] ?></p>
                                                            <p><b>Zip Code: </b><?php echo $address['zipcode'] ?> </p>
                                                            <p><b>State: </b> <?php echo $states[$address['state']] ?> </p>
                                                        </label>

                                                    <?php } ?>

                                                <?php } ?>
                                                <div class="clearfix"></div>

                                                <label class="label_radio" >
                                                    <input class="form-control" type="radio" name="address_id" id="address_id_other" value="other"  />
                                                    <strong>ALTERNATE ADDRESS</strong> (Please specify below if  location differs from your local address)
                                                </label>

                                                <div class="clearfix"></div>
                                            </div>  
                                            <div id="other_address" style="display:none">     
                                                <div class="form-group ">
                                                    <label for="curl" class="control-label col-lg-3">Hotel Name: (if applicable):</label>
                                                    <div class="col-lg-9">
                                                        <input name="other[billing_name]" type="text" class="form-control" id="some16" value="" />                                        </div>
                                                </div>
                                                <div class="form-group ">
                                                    <label for="curl" class="control-label col-lg-3">Street Address:</label>
                                                    <div class="col-lg-9">
                                                        <input type="text" class="form-control required" name="other[streat_address]" id="local_streat_address" value="<?php echo $this->eventsForm->other->streat_address->getValue() ?>">
                                                    </div>
                                                </div>
                                                <div class="form-group ">
                                                    <label for="curl" class="control-label col-lg-3">Cross Street:</label>
                                                    <div class="col-lg-9">
                                                        <input type="text" name="other[address_1]" id="local_address_1" class="form-control required" value="<?php echo $this->eventsForm->other->address_1->getValue() ?>">
                                                    </div>
                                                </div>
                                                <div class="form-group ">
                                                    <label for="curl" class="control-label col-lg-3">City:</label>
                                                    <div class="col-lg-9">
                                                        <input name="other[city]" id="local_city" type="text" class="form-control required"  value="<?php echo $this->eventsForm->other->city->getValue() ?>" />
                                                    </div>
                                                </div>
                                                <div class="form-group ">
                                                    <label for="curl" class="control-label col-lg-3">State:</label>
                                                    <div class="col-lg-9">
                                                        <select id="local_state" name="other[state]" class="form-control required">
                                                            <?php foreach ($this->eventsForm->other->state->getMultiOptions() as $key => $option) { ?>
                                                                <option value="<?php echo $key ?>" <?php echo $this->eventsForm->other->state->getValue() == $key ? 'checked="checked"' : '' ?>><?php echo $option ?></option>
                                                            <?php } ?>
                                                        </select>                                        </div>
                                                </div>
                                                <div class="form-group ">
                                                    <label for="curl" class="control-label col-lg-3">Zip Code:</label>
                                                    <div class="col-lg-9">
                                                        <input name="other[zipcode]" id="local_zipcode" type="text" class="form-control required"  value="<?php echo $this->eventsForm->other->zipcode->getValue() ?>" />
                                                    </div>
                                                </div>
                                            </div>
                                            
                                    <div class="<?php echo $cb;?>">      
                                    <h4>Sitter Updates</h4>
                                    <div class="border-top m-bot20"></div>
                                       <div class=""><?php if (isset($this->logs) && !empty($this->logs) ) { foreach($this->logs as $row){?>
                                        <p><b><?php echo $row['modification'] ?></b></p>
                                         <?php }}else{ echo '<p>No update by sitter</p></br>';} ?>
                                	</div>
                                	</div> 
                                        </div>
                                       
                             <div class="col-sm-6">
                                <div class="<?php echo $cb; ?>">
                                  <h4>Confirmed Babysitter</h4>
                                  <div class="border-top m-bot20"></div>
                                  <div class=""><?php if (isset($this->selectedSitter)) { ?>
                                        <div class="Children_pic col-lg-3">
                                            <?php if ($this->selectedSitter['thumb_image'] != ''&& file_exists($this->selectedSitter['thumb_image'])) { ?>
                                                <img
                                                    src="<?php echo SITE_URL . $this->selectedSitter['thumb_image'] ?>"/>
                                            <?php } else { ?>
                                                <img alt="No Image"
                                                     src="<?php echo SITE_URL . 'resource/img/noimage.jpg' ?>"/>
                                            <?php } ?>
                                        </div>
                                        <div class="bio-desk col-lg-9">
                                            <h4 class="terques"><a
                                                    href="<?php echo ADMIN_URL ?>sitters/profile/modify/<?php echo $this->selectedSitter['userid'] ?>"><?php echo $this->selectedSitter['firstname'] . ' ' . $this->selectedSitter['lastname'] ?></a>
                                            </h4>
                                            <p><b>Mobile: </b><?php echo $this->selectedSitter['phone'] ?></p>
                                            <p><b>Home: </b><?php echo $this->selectedSitter['local_phone'] ?></p>
                                            <p><b>Email: </b><a href="mailto:<?php echo $this->selectedSitter['username'] ?>"><?php echo $this->selectedSitter['username'] ?>
                                            </p></a>
                                            <div>
                                            </div></div> <?php }else{ echo '<label class="control-label ">No Confirmed Babysitter.</label></br>';} ?>
                                </div>
                                </div>
                                <div class="clearfix"></div>
                           
                                
                                            <h4>Children</h4>
                                            <div class="border-top m-bot20"></div>
                                            <div class="">

                                                <?php if (!empty($this->children)) { ?>  
                                                    <?php foreach ($this->children as $child) { ?>
                                                        <div class="btn-group" data-toggle="buttons">

                                                            <label class="btn btn-info chk <?php echo in_array($child['child_id'], $this->selectedChild) || !(int) $this->searchParams['modify'] ? 'active' : ''; ?>">
                                                                <input class="child_checkbox" autocomplete="off" type="checkbox" value="<?php echo $child['child_id'] ?>"  <?php echo in_array($child['child_id'], $this->selectedChild) || !(int) $this->searchParams['modify'] ? 'checked="checked"' : ''; ?> name="child[]" />
                                                                <span class="glyphicon glyphicon-ok"></span>
                                                            </label>
                                                        </div>
                                                        <div class="Children_pic col-lg-3">
                                                            <?php if ($child['thumb_image'] != '' && file_exists($child['thumb_image'])) { ?>
                                                                <img src="<?php echo SITE_URL . $child['thumb_image'] ?>"  />
                                                            <?php } else { ?>
                                                                <img alt="No Image" src="<?php echo SITE_URL . 'resource/img/noimage.jpg' ?>"  />
                                                            <?php } ?>                                
                                                        </div>
                                                        <div class="bio-desk col-lg-9">
                                                            <h4 class="terques"><?php echo $child['child_name'] ?> </h4>
                                                            <p><b>Age: </b> <?php echo $this->age($child['dob']) ?></p>
                                                            <p><b>Allergies: </b><?php echo $child['allergy_status'] ?></p>
                                                            <?php if ($child['allergy_status'] == 'Yes') { ?>	 
                                                                <?php echo $child['allergies'] ?><br /><br />
                                                            <?php } ?>
                                                            <p><b>Medications: </b><?php echo $child['medicator_status'] ?></p>

                                                            <?php if ($child['medicator_status'] == 'Yes') { ?>	 
                                                                <?php echo $child['medicator'] ?><br /><br />
                                                            <?php } ?>
                                                            <p><b>Special Needs: </b><?php echo $child['special_needs_status'] ?></p>

                                                        <?php if ($child['special_needs_status'] == 'Yes') { ?>	 
                                                            <?php echo $child['special_needs'] ?><br /><br />
        												<?php } ?>
                                                            <p><b>Helpful Hints: </b>  <?php echo $child['notes'] ?></p>
                                                        </div>
                                                        <div class="clearfix"></div>
                                                        <div class="border-top m-bot20"></div>    
                                                        <?php
                                                    }
                                                } else {
                                                    $childStyle = 'style="display:block"';
                                                    ?>   
                                                    <div class="alert alert-block alert-danger fade in" id="child_error" <?php echo $childStyle ?>><p> Must add child’s profile to complete job request.  <a href="<?php echo ADMIN_URL . 'client/children/parent/' . $this->userid ?>"> Add Child Now</a> </p></div>		

                                                <?php } ?>
                                                <div class="alert alert-block alert-danger fade in" id="child_error" style="display:none" ><p> Please add child to schedule babysitter. </p></div>		
                                            </div>

                                            <?php if ($this->childError != '') { ?>
                                                <div class="alert alert-block alert-danger fade in"> <p>Please select child to make job</p></div>		
                                            <?php } ?>

                                            <?php if ($this->searchParams['modify'] > 0) { ?>      

                                                <h4>Job Details</h4>
                                                <div class="border-top m-bot20"></div>

                                                <p><b>Booking fee paid: </b> <?php echo $this->event['credits_used'] . " " . Credit; ?></p>
                                                <input type="hidden" value="<?php echo $this->event['job_id']; ?>" id="j_id">
                                                <input type="hidden" value="<?php echo $this->userid; ?>" id="user_id">

                                                <?php
                                                $start_date = $this->event['job_start_date'];
                                                $end_date = $this->event['job_end_date'];
                                                $diff = strtotime($end_date) - strtotime($start_date);
                                                $diff_in_hrs = $diff / 3600;
                                                if ($this->event['job_status'] == 'completed') {
                                                    $end_date = $this->event['completed_date'];

                                                    if (strtotime($end_date) < strtotime($start_date)) {
                                                        $end_date = $this->event['job_end_date'];
                                                    }
                                                }

                                                $diff = strtotime($end_date) - strtotime($start_date);
                                                $act_diff_in_hrs = $diff / 3600;
                                                ?>
                                                <p><b>Actual End Date: </b> <?php echo date('m/d/Y h:i A',strtotime($end_date)); ?></p>
                                                <p><b>Hours: </b> <?php echo $diff_in_hrs; ?></p>
                                                <p><b>Actual Hours: </b> <?php echo $act_diff_in_hrs; ?></p>
                                                <p><b>Kids: </b><?php echo $this->event['child_count']; ?></p>
                                                <p><b>Actual Kids: </b><?php echo $this->event['actual_child_count']; ?></p>
                                                <input type="button" value="Add Child" onclick="addchild()" class="btn btn-info"/>
                                               

                                                <div id="mydiv" style="display:none" >
                                                 </br></br>
                                                    <h4>Add Child</h4>
                                                    <div class="border-top m-bot20"></div>

                                                    <div class="form-group ">
                                                        <label for="cname" class="control-label col-lg-3">Child's Name</label>
                                                        <div class="col-lg-9">
                                                            <input class="form-control" type="text" id="child_name" name="child_name" />
                                                            <span class="cerror" id="name_child"></span>
                                                        </div>
                                                    </div>
                                                    
		                                          <div class="form-group ">
		                                             <label class="control-label col-lg-3">Gender</label>
		                                                <div class="col-lg-9">
		                                                <select class="form-control" id="sex" name="sex">
		                                                 <option value=""  selected="selected">Select Gender</option>
		                                                	 <?php foreach ($this->eventsForm->sex->getMultiOptions() as $key=>$value) { ?>
						                                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
						                                            <?php } ?> 
		                                				</select>
		                                				<span class="cerror" id="child_gender"></span>
		                                                </div>
		                                       	 </div>	
                                                    
                                                    <div class="form-group ">
                                                        <label class="control-label col-lg-3">Date of Birth</label>
                                                        <div class="col-lg-9">
                                                            <div data-date-viewmode="years" data-date-format="mm-dd-yyyy"   class="input-group date default-date-picker clearfix">
                                                                <input type="text" readonly size="16" class="form-control datep" id="dob" name="dob">
                                                                <span class="input-group-btn" style="width: auto">
                                                                    <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                                                </span>

                                                            </div> 
                                                            <span class="cerror" id="bod"></span>

                                                        </div>
                                                    </div>
                                                    <div class="form-group ">
                                                        <label for="curl" class="control-label col-lg-3">Allergies</label>
                                                        <div class="col-lg-9 radiop">
                                                            <label class="label_radio" for="radio-13">
                                                                <input  id="radio-13" class="form-control " type="radio" name="allergy_status" value="Yes"> Yes 
                                                            </label>
                                                            <label class="label_radio" for="allergy_status">
                                                                <input  class="form-control" type="radio"  name="allergy_status" id="allergy_status" value="No" > No 
                                                            </label>

                                                            <div class="clearfix"></div> 
                                                            <span class="cerror" id="status_allergy"></span>

                                                            <div class="col-lg-9 allergies_text" style="display:none">
                                                                <!--                                             <label>-->
                                                                <textarea placeholder="Allergies can be life threatening. Please describe in detail. " name="allergies" id="allergies"class="form-control"></textarea>
                                                                <div>     
                                                                    <small>Allergies can be life threatening. Please describe in detail. 
                                                                    </small>     
                                                                </div>
                                                                <span class="cerror" id="text_allergy"></span>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="form-group ">
                                                        <label for="curl" class="control-label col-lg-3">Medication</label>
                                                        <div class="col-lg-9 radiop">
                                                            <label class="label_radio" for="radio-15">
                                                                <input  id="radio-15"  class="form-control" type="radio"  name="medicator_status" value="Yes" > Yes 
                                                            </label>
                                                            <label class="label_radio" for="radio-14">
                                                                <input  id="radio-14" class="radio" type="radio" name="medicator_status" value="No" > No 
                                                            </label>
                                                            <div class="clearfix"></div> 

                                                            <span class="cerror" id="status_medicator"></span>
                                                            <div class="col-lg-9 medicator_text" style="display:none">
                                                                <!--                                             <label>-->
                                                                <textarea placeholder="List all medications" name="medicator" id="medicator" class="form-control"></textarea>
                                                                <div>
                                                                    <small>List all medications </small>
                                                                </div>
                                                                <span class="cerror" id="text_medicator"></span>
                                                            </div>

                                                        </div>
                                                    </div>
                                                    
                                     <div class="form-group ">
                                             <label class="control-label col-lg-3">Special Needs</label>
                                                <div class="col-lg-9">
                                                <select class="form-control" id="special_needs" name="special_needs">
                                                 <option value="" selected="selected">Select if any</option>
                                                	 <?php foreach ($this->eventsForm->special_needs->getMultiOptions() as $needs) { ?>
				                                        <option value="<?php echo $needs['special_need']; ?>" <?php if($this->eventsForm->special_needs->getvalue()==$needs['special_need']){ echo 'selected="selected"';}?>><?php echo $needs['special_need']; ?></option>
				                                            <?php } ?> 
                                				</select>
                                                </div>
                                        </div>

                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Favorite Food</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" name="fav_food" id="fav_food" value="" />
                                            </div>
                                        </div>
                                        
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Favorite Book</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" name="fav_book" id="fav_book" value="" />
                                            </div>
                                        </div>
                                        
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Favorite Cartoon</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" name="fav_cartoon" id="fav_cartoon" value="" />
                                            </div>
                                        </div>
                                                    
                                                    <div class="form-group ">
                                                        <label for="curl" class="control-label col-lg-3">Helpfull hints</label>
                                                        <div class="col-lg-9">
                                                            <textarea name="notes" id="notes" class='form-control'></textarea>
                                                            <small>(ie. Billy loves Thomas the Tank Engine and  needs Teddy for naps)  </small> </dd>
                                                        </div>
                                                    </div>


                                                    <div class="form-group ">
                                                        <label class="control-label col-lg-3">Upload Picture</label>
                                                        <div class="col-lg-9">
                                                            <input type="hidden" name="MAX_FILE_SIZE" value="8388608" id="MAX_FILE_SIZE">
                                                            <input class="file" type="file" id="c_image" name="image" />
                                                            <span class="cerror" id="upload_image"></span>

                                                        </div>
                                                    </div>

                                                    <div class="form-group clearfix">
                                                        <div class="m-bot20 m-top20">
                                                            <input class="btn btn-danger" type="button" value="Add" onclick="add_children()" />
                                                            <input class="btn btn-default" type="button"  value="Cancel" onclick="rechild()"/>

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="clearfix"></div>

                                                <h4>Update Client Rate</h4>
                                                <div class="border-top m-bot20"></div>
                                                <?php
                                                $rate = $this->event['client_updated_rate'];
                                                if ($rate == null) {
                                                    $rate = $this->event['client_rate'];
                                                }
                                                ?>
                                                <div class="clearfix">
                                                    <div class="col-sm-4 no-padding" ><p><b>Client rate: </b> <?php echo money_format('%.2n', $rate); ?></p> </div>

                                                    <div class="col-sm-4">
                                                        <input type="text" id="c_rate" class="form-control"/>

                                                        <div class="emessage" id="c_r_error" style="display:none"></div>
                                                        <div  id="c_ok" class="smessage" style="display:none"> </div>
                                                    </div>
                                                   

                                                    <?php if ($this->event['client_payment_status'] == 'paid') { ?>
                                                        Client Charged
                                                    <?php } else{ ?>
                                                     <div class="col-sm-4">
                                                        <input type="button" value="Update Rate" onclick="update_rate()" class="btn btn-info" required  id="c_r_u"/>
                                                    </div>
                                                    
                                                    <?php }?>
                                                    <br />

                                                </div>

                                                <p><b>Client Charge: </b><?php echo money_format('%.2n', $rate * $act_diff_in_hrs); ?></p>
                                                <input type="button" id="btn_charge_client" onclick="charge_client(<?php echo $this->event['job_id'];?>,<?php echo $this->event['client_user_id'];?>,<?php echo  $rate * $act_diff_in_hrs;?>);" value="Charge Client" class="btn btn-info">
                                                <span id="loading1" style="display: none;">processing please wait...</span>
                                                <div class="clearfix"></div>
                                                <h4>Update Sitter Rate</h4>
  												<div class="border-top m-bot20"></div>
                                                <div class="clearfix">

                                                    <?php
                                                    $s_rate = $this->event['rate'];
                                                    if ($s_rate == null) {
                                                        $s_rate = $this->event['sitter_rate_pre'];
                                                    }
                                                    ?>
                                                    <div class="col-sm-4 no-padding" ><p><b>Sitter rate: </b> <?php echo money_format('%.2n', $s_rate); ?></p> </div>

                                                    <div class="col-sm-4">
                                                        <input type="text" id="s_rate" class="form-control"/>
                                                        <div class="emessage" id="s_r_error" style="display:none"></div>
                                                        <div id="s_ok" class="smessage" style="display:none"></div>
                                                    </div>
                                                    
                                                    <?php if ($this->event['sitter_payment_status'] == 'paid') { ?>
                                                        Sitter Paid
                                                    <?php }else{ ?>
                                                    <div class="col-sm-4">
                                                        <input type="button" value="Update Rate" onclick="update_sitter_rate()" class="btn btn-info" id="s_r_u"/>
                                                    </div>
                                                    <?php }?>
                                                    <br />
                                                </div>
                                                <p><b>Sitter payout: </b><?php echo money_format('%.2n', $s_rate * $act_diff_in_hrs); ?></p>
                                                <input type="button" onclick="paysitter(<?php echo $this->event['sitter_user_id'];?>);" value="Pay Sitter" id="btn_paysitter" class="btn btn-danger"/>
                                            </div>

                                        <?php } ?>
                                    </section>
                                    <!-- <h4>Sitter Requirements</h4> --> 
                                    <h4>Sitter Preferences</h4> 
                                    <div class="border-top m-bot20"></div>

                                    <div>        
                                        <?php if (!empty($this->preferences)) { ?>
                                            <table class="table table-bordered table-striped table-condensed cf">
                                                <?php foreach ($this->preferences as $groupId => $group) { ?>
                                                    <tr>
                                                        <td><?php echo $group['label'] ?></td>
                                                        <td>
                                                            <?php
                                                            if (!empty($group['prefer']))
                                                                foreach ($group['prefer'] as $p) {
                                                                    ?>
                                                                    <div class="btn-group col-sm-3" data-toggle="buttons" >    
                                                                        <label class="btn btn-info chk <?php echo in_array($p['prefer_id'], @array_keys((array) $this->jobPreference[$groupId]['prefer'])) ? 'active' : '' ?>"> 
                                                                            <input autocomplete="off" <?php echo in_array($p['prefer_id'], @array_keys((array) $this->jobPreference[$groupId]['prefer'])) ? 'checked="checked"' : '' ?> type="checkbox" name="prefer[]" value="<?php echo $p['prefer_id'] ?>" />

                                                                            <span class="glyphicon glyphicon-ok"></span>
                                                                        </label>  
                                                                        <?php echo $p['prefer_name'] ?>
                                                                    </div>
                                                                <?php }
                                                            ?> </td>
                                                    </tr>
                                                <?php } ?>
                                            </table>
                                        <?php } ?>
                                    </div>               

                                    <h4>Special Needs</h4> 
                                    <?php $sneeds = $this->eventsForm->special_need->getValue();
                                    ?>
                                    <div class="border-top m-bot20"></div>
                                     <div class="form-group ">
                                                <label class="control-label col-lg-3">Special Needs:</label>
                                                <div class="col-lg-9">
                                                <!--<select class="form-control" id="special_need" name="special_need">
                                                 <option value="" <?php //if ($sneeds == '') { ?> selected="selected" <?php //} ?> >Select if any</option>
                                                	 <?php //foreach ($this->eventsForm->special_need->getMultiOptions() as $needs) { ?>
				                                        <option value="<?php //echo $needs['special_need']; ?>"
				                                        <?php  //if ($sneeds == $needs['special_need']) { ?>
				                                                    selected="selected" <?php //} ?>><?php //echo $needs['special_need']; ?></option>
				                                            <?php //} ?> 
                                				</select>
                                                -->
                                                    <input name="special_need" id="special_need" value="<?php echo $this->eventsForm->special_need->getValue() ?>" class="form-control"/>
                                                </div>
                                    </div>
                                    
                                    <h4>Special instruction</h4> 
                                    <div class="border-top m-bot20"></div>
                              
                                    <label for="some3">Special Requests/ Instructions:<br />
                                        <small>(ie.  Prefer babysitter who is open to staying an hour or two later if necessary)</small> </label>

                                    <textarea name="notes" id="notes" class="form-control"><?php echo $this->eventsForm->notes->getValue() ?></textarea>
                                    <br />
                                    
                                    <?php if($this->event['note_by_sitter']!=''&& $this->event['note_by_sitter']!=null ){?>
                                    <h4>Notes about job</h4> 
                                    <div class="border-top m-bot20"></div>
                                    <p><?php echo $this->event['note_by_sitter']; ?></p>
                              		<?php }?>
                                   
                                    <?php if ($continueSubmit) { ?>
                                        <input class="btn btn-info" type="submit" value="<?php echo $this->searchParams['modify'] > 0 ? 'Update' : 'Book It' ?>" />

                                    <?php } ?>

                                    <input onclick="window.location = '<?php echo ADMIN_URL . 'client/events/user/' . $this->userid . '/listevents/jobs' ?>'" class="btn btn-info" type="button" value="Back"  />

                                    <?php if ($_SESSION['Zend_Auth']['storage']->usertype == 'A') { ?>

                                        <?php if ($this->searchParams['modify'] > 0) { ?>
                                            <?php if ($this->event['job_status'] != "cancelled" && $this->event['job_status'] != "closed" && $this->event['job_status'] != "completed") { ?>
                                                <a onclick="if (confirm('You are going to cancel this job. Are you sure?'))
                                                                        return true;
                                                                    return false;" href="<?php echo ADMIN_URL . 'jobs/canceljob/job_id/' . $this->searchParams['modify'] ?>" class="btn btn-danger" style="float:right">Cancel Job</a>

                                            <?php } ?> 
                                        <?php } ?>
                                    <?php } ?>  
                                </dl>
                            </form>
                        </div>
                </section>

                <form class="cmxform form-horizontal tasi-form custom-form" id="childform" method="post" enctype="multipart/form-data"  >
                </form>

            </div>
        </div>

        <!-- page end-->
    </section>
</section>


<!--main content end-->
<!-- Right Slidebar start -->

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade in" >

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" >
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button" onclick="reloadPage()">×</button>
                <h4 class="modal-title">Message</h4>
            </div>
            <div class="modal-body">
                <form role="form" class="form-horizontal">
                    <div class="form-group">
                        <div class="col-lg-10" id="transaction_message">

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">

                            <button style="float:right" class="btn btn-send" type="submit">Ok</button>
                        </div>
                    </div>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModalSuccess" class="modal fade in" >

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" >
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button" onclick="reloadPage()">×</button>
                <h4 class="modal-title">Transaction Details</h4>
            </div>
            <div class="modal-body">
                <form role="form" class="form-horizontal">
                    <div>
                        <div class="col-md-6"> Client Name </div>
                        <div class="col-md-6" id="cname"> </div>
                    </div>
                    </br>
                    </br>
                    <div>
                        <div class="col-md-6">Job Id</div>
                        <div class="col-md-6" id="client_job_id"></div>
                    </div>
                    </br>
                    </br>
                    <div>  
                        <div class="col-md-6">Transaction Id</div>
                        <div class="col-md-6" id="transaction_id"></div>    
                    </div>
                    </br>
                    </br>

                    <div>
                        <div class="col-md-6">Amount  </div>                                                
                        <div class="col-md-6" id="amount"></div>     
                    </div>

                    </br>
                    </br>
                    <div>
                        <div class="col-md-12">   
                            <button  style="float:right" class="btn btn-send" type="submit">Ok</button>
                        </div>
                    </div>
                    <div  class="clearfix"></div>
                </form>
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<!-- deleted client profile -->
<div class="modal fade" tabindex="-1" role="dialog" id="dclient">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     <h4 class="modal-title">Notice</h4>
      </div>
      <div class="modal-body">
        <div>This client profile has been deleted.</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>
<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/additional-methods-new.min.js"></script>






<script>


var form_valid = true;
$(document).ready(function () {

<?php if (!$timediff) {
    ?>
    <?php if (in_array($this->event['job_status'], array('new', 'pending'))) { ?>

$('input[type=button],input[type=submit]').hide();
$('input[type=checkbox],input[type=radio],textarea').attr('disabled', 'disabled');

    
<?php } ?>

<?php }
if(in_array($this->event['job_status'], array('confirmed', 'new', 'pending'))){?>
	$("#btn_paysitter").hide();
	$("#btn_charge_client").hide();
<?php }?>

<?php if (in_array($this->event['job_status'], array('completed', 'closed', 'cancelled'))) {
    
	 if($this->event['client_payment_status'] == 'unpaid'&& $this->event['sitter_payment_status'] == 'unpaid' && $this->event['job_status']=="completed"){}else{?>
$('input[type=button],input[type=submit]').hide();
$('input[type=checkbox],input[type=radio],textarea').attr('disabled', 'disabled');
<?php }?>
    <?php if ($this->event['client_payment_status'] == 'unpaid' && ($this->event['job_status'] == 'completed' ||($this->event['job_status'] == 'cancelled' && $this->event['immidiate_cancelled']=='yes' ))) { ?>
$("#c_r_u").show();
$("#btn_charge_client").show();
    <?php } ?>
    <?php if ($this->event['sitter_payment_status'] == 'unpaid' && ($this->event['job_status'] == 'completed' ||($this->event['job_status'] == 'cancelled' && $this->event['immidiate_cancelled']=='yes' ))) { ?>
$("#s_r_u").show();
$("#btn_paysitter").show();
    <?php } ?>
<?php } ?>
});

$(document).ready(function () {
	$(".dtimecustom").datetimepicker({
	    format: "mm/dd/yy H:ii p",
	    showMeridian: true,
	    autoclose: true,
	    todayBtn: true,
	    pickerPosition: "bottom-left",
	    <?php if($this->event['job_status']!='completed'){ ?>
	    startDate: new Date(),
	    <?php }?>
	    minuteStep: 15,
	});
    // validate signup form on keyup and submit
    var validator = $("#eventsform").validate({
        rules: {
            start_date: {
                required: true
            },
            end_date: {
                required: true
            },
            'child[]': {
                required: true
            },
            address_id: {
                required: true
            },
            'other[address_1]': {
                required: function () {
                    return $('#address_id_other').is(':checked')
                }
            },
            'other[streat_address]': {
                required: function () {
                    return $('#address_id_other').is(':checked')
                }
            },
            'other[zipcode]': {
                required: function () {
                    return $('#address_id_other').is(':checked')
                }
            },
            'other[city]': {
                required: function () {
                    return $('#address_id_other').is(':checked')
                }

            },
            'other[state]': {
                required: function () {
                    return $('#address_id_other').is(':checked')
                }
            }

        },
        messages: {
            start_date: {
                required: 'Please Select Job Start Date'
            },
            end_date: {
                required: 'Please Select Job End date.'
            },
            address_id: {
                required: 'Please Select address.'
            },
            'child[]': {
                required: 'Please select child to schedule babysitter.'
            }
        },
// the errorPlacement has to take the table layout into account
        errorPlacement: function (error, element) {
            //alert(element.attr('type'));
            if (element.is(":radio")) {
                //$(".msg p").html('');
                $("#other_error").hide();
                error.appendTo($("#other_error"));
                if (error.html() != '')
                    $("#other_error").show();
                else
                    $("#other_error").hide();
            }
            else if (element.is(":checkbox")) {
                $("#child_error").show();
                //$(".msg p").html('');
                $("#child_error p").html('');
                error.appendTo($("#child_error p"));

                $("#child_error").show();
            }
            else {


<?php if (!empty($errors)) { ?>
error.appendTo(element.parent().next());
<?php } else { ?>
error.appendTo(element.parent());
<?php } ?>
    }
},
// specifying a submitHandler prevents the default submit, good for the demo
submitHandler: function () {
    document.getElementById('eventsform').submit();
},
// set this class to error-labels to indicate valid fields
success: function (label) {
}
});

<?php
if (!empty($errors)) {
    echo "validator.showErrors(" . json_encode($errors) . ");";
}
?>
$(".child_checkbox").change(function () {
    if ($(this).is(':checked')) {
        $("#child_error").hide();
    }

    if ($(".child_checkbox:checked").length == 0)
        if ($("#child_error p:eq(0)").html() != '')
            $("#child_error").show();
});
});


$("input[name=address_id]").change(function () {

    if ($("input[name=address_id]:checked").val() == 'other')
        $('#other_address').show();
    else
        $('#other_address').hide();

});


$('input[name=allergy_status]').click(function (event) {

    if (this.value == 'Yes')
        $('.allergies_text').slideDown();
    else
        $('.allergies_text').slideUp();
});
$('input[name=medicator_status]').click(function (event) {
    if (this.value == 'Yes')
        $('.medicator_text').slideDown();
    else
        $('.medicator_text').slideUp();
});

$("#start_date,#end_date").change(function ()
{
    checkCredits();
});

function checkCredits() {
$.ajax({
    url: '<?php echo $this->url() ?>',
    data: {start_date: $('#start_date').val(), end_date: $('#end_date').val(), check: 'credits'},
    dataType: 'json',
    success: function (data) {

if (parseInt(data.required_credits) <= 0) {
    $("#ok").hide();
    $("#error").show();
    $("#error").html('<p>Start date should be less than end date</p>');
    form_valid = false;
    return false;
}
if (parseInt(data.calculated_credits) > 0) {
    $("#ok").show();
    $("#error").hide();
    $("#ok").html('<p>You are going to book for <strong>' + data.required_credits + ' day</strong> and ' + data.required_credits + ' credits will be used</p>');
    form_valid = false;
    //return false;
} else {
    $("#ok").hide();
    $("#error").show();
    $("#error").html('<p>You are going to book for <strong>' + data.required_credits + ' days.</strong></p><p>You do not have enough credits to book. <a href="<?php echo ADMIN_URL?>client/buycredits/client/<?php echo $this->userid; ?>" title="Go to Buy Credits"> Buy credits now</a></p>');
    form_valid = true;
}
    }
    });
}

function update_rate()
{
    var new_rate = $("#c_rate").val();
    var job_id = $("#j_id").val();
    if (!new_rate)
    {
        $("#c_r_error").show();
        $("#c_r_error").html('<p>Please enter rate to update</p>');
    }

    else if (new_rate < 0)
    {
        $("#c_r_error").show();
        $("#c_r_error").html('<p>Please enter valid rate to update</p>');

    }

    else if ($.isNumeric(new_rate)) {
        $("#c_r_error").hide();

        $.ajax({
            url: "<?php echo ADMIN_URL . 'jobs/updateclientrate' ?>",
            data: {job_id: job_id, rate: new_rate},
            dataType: 'json',
            type: 'post',
            success: function (data) {

                if (data.status = "success"){
                    $("#c_ok").show();
                    $("#c_ok").html('<p>Client rate has been updated successfully</p>');
                }
                else{
                    $("#c_r_error").show();
                    $("#c_r_error").html('<p>Please enter a valid rate to update</p>');
                }
                location.reload();
            }
        }); }
    else{
        $("#c_r_error").show();
        $("#c_r_error").html('<p>Please enter a valid rate to update</p>');
    }
}

function update_sitter_rate()
{
    var new_rate = $("#s_rate").val();
    var job_id = $("#j_id").val();
    if (!new_rate) {
        $("#s_r_error").show();
        $("#s_r_error").html('<p>Please enter a valid rate to update</p>');

    }
    else if (new_rate < 0){
        $("#s_r_error").show();
        $("#s_r_error").html('<p>Please enter a valid rate to update</p>');
    }
    else if (jQuery.isNumeric(new_rate)) {
        $("#s_r_error").hide();
        $.ajax({
            url: "<?php echo ADMIN_URL . 'jobs/updatesitterrate' ?>",
            data: {job_id: job_id, rate: new_rate},
            dataType: 'json',
            type: 'post',
            success: function (data) {

                if (data.status = "success")
                {
                    $("#s_ok").show();
                    $("#s_ok").html('<p>Sitter rate has been updated successfully</p>');
                }
                else{
                    $("#s_r_error").show();
                    $("#s_r_error").html('<p>Please enter a valid rate to update</p>');
                }
                location.reload();
            } });
    }
    else {
        $("#s_r_error").show();
        $("#s_r_error").html('<p>Please enter a valid rate to update</p>');
    }
}


function addchild(){
    $("#mydiv").show();

}
function rechild(){
    $("#mydiv").hide();
}

function add_children(){
    var flag = true;
    var childname = $("#child_name").val();
    var dob = $("#dob").val();
    var sex = $("#sex").val();
    
    var al_status = $('input:radio[name=allergy_status]:checked').val();
    var me_status = $('input:radio[name=medicator_status]:checked').val();
    if (!childname)  {
        $("#name_child").html('Please enter the child name');
        var flag = false;
    }
    if (!sex)  {
        $("#child_gender").html('Please select the child gender');
        var flag = false;
    }
    if (!dob){
        $("#bod").html('Please enter the child date of birth');
        var flag = false;
    }

    if (!al_status){
        $("#status_allergy").html('Please Select allergy status of the child');
        var flag = false;
    }
    if (al_status){
        if (al_status == 'Yes') {
            var allergy_text = $("#allergies").val();
            if (!allergy_text){
                $("#text_allergy").html('Please mention the allergies');
                var flag = false;
            }
            else{
                $("#text_allergy").html('');
                var flag = true;
            }  }
    }
    if (!me_status) {
        $("#status_medicator").html('Please Select medicator status of the child');
        var flag = false;
    }
    if (me_status){
        if (me_status == 'Yes'){
            var medicator_text = $("#medicator").val();
            if (!medicator_text){
                $("#text_medicator").html('Please mention the medications');
                var flag = false;
            }
        }
    }

    if ($('#c_image').val().split('.').pop().toLowerCase()){
        var ext = $('#c_image').val().split('.').pop().toLowerCase();
        if ($.inArray(ext, ['gif', 'png', 'jpg', 'jpeg']) == -1) {

            $('#upload_image').html('Invalid File Extension');
            var flag = false;
        }
    }

    if (flag == true){
        var al_status = $('input:radio[name=allergy_status]:checked').val();
        var m_status = $('input:radio[name=medicator_status]:checked').val();
        var FormDat = new FormData();
        var myFile = $("#c_image")[0].files[0];
        FormDat.append("child_name", $("#child_name").val());
        FormDat.append("sex", $("#sex").val());
        FormDat.append("image", myFile);
        FormDat.append("dob", $("#dob").val());
        FormDat.append("allergies", $("#allergies").val());
        FormDat.append("medicator", $("#medicator").val());
        FormDat.append("allergy_status", al_status);
        FormDat.append("medicator_status", m_status);
        FormDat.append("notes", $("#notes").val());
        FormDat.append("job_id", $("#j_id").val());
        FormDat.append("parent_id", $("#user_id").val());
        FormDat.append("special_needs", $("#special_needs").val());
        FormDat.append("fav_food", $("#fav_food").val());
        FormDat.append("fav_book", $("#fav_book").val());
        FormDat.append("fav_cartoon", $("#fav_cartoon").val());
       
        $.ajax({
            url: "<?php echo ADMIN_URL . 'client/children' ?>",
            cache: false,
            contentType: false,
            processData: false,
            data: FormDat, // Setting the data attribute of ajax with file_data
            dataType: 'json',
            type: 'post',
            success: function (data) {
                if (data.status == 'success') {
                    parent.location.reload();
                }

                else {
                    parent.location.reload();
                }
            },
            complete: function () {
            },
        });
    }
}
function charge_client(job_id, userid, charge)
{
	$("#btn_charge_client").hide();
	$("#loading1").show();
    $.ajax({
        url: "<?php echo ADMIN_URL . 'client/chargeclient' ?>",
        cache: false,
        //    contentType: false,
        //  processData: false,
        data: {job_id: job_id, user_id: userid, charge: charge}, // Setting the data attribute of ajax with file_data
        dataType: 'json',
        type: 'post',
        async: false,
        success: function (data) {
            if (data.status == 'failed')
            {
                $('#myModal').modal('show');
                $("#transaction_message").text(data.message);
            }

            if (data.status == 'success')
            {

                $("#cname").text(data.client_name);
                $("#client_job_id").text(data.job_id);
                $("#amount").text(data.amount);
                $("#transaction_id").text(data.transaction_id);

                $('#myModalSuccess').modal('show');
                $("#btn_charge_client").hide();
                $("#processing_loading").hide();
            }
        },
        complete: function () {
            //hide_loader();
        }
    });


}

function paysitter(id)
{
	var form= '<form method="POST" action="<?php echo ADMIN_URL;?>sitters/paysitter"><input type="hidden" name="sitter_id" value="'+id+'"/></form>';
	$(form).appendTo('body').submit().remove();
}

$(document).ready(function(){
	$('.deleted_client').click(function(){
		$('#dclient').modal('show');
		});
});
</script>

