
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    
                <div class="fixed-position col-lg-12">
                    <header class="panel-heading clearfix">
                        Clients
                        <a href="<?php echo ADMIN_URL ?>client/profile" class="label label-success pull-right">Add Client</a>

                    </header>
                    </br>
                    <form name="searchform" method="post">
                        <div class="col-md-12">
                            <div class="col-md-3">
                                <input  type="text" class="form-control resettext" name="fullname" size="15" value="<?php echo $this->searchParams['fullname'] ?>" placeholder="Name" />
                            </div>
                            <div class="col-md-3">	
                                <input type="text" class="form-control" name="email" placeholder="Email" size="8" value="<?php echo $this->searchParams['email'] ?>" />                           
                            </div>
                            <div class="col-md-3">	
                                <input type="text" class="form-control" name="phone" placeholder="Phone" value="<?php echo $this->searchParams['phone'] ?>" size="8"/>
                            </div>
                            <div class="col-md-2">	
                                <input type="text" class="form-control" name="job_id" placeholder="Job number" value="<?php echo $this->searchParams['job_id'] ?>" size="8"/>
                            </div>
                            <div class="col-md-1">	
                                <input type="submit" name="filter" value="Search" class="btn btn-danger" />
                            </div>
                        </div>
                    </form>
                </div>

                    <!--  <div class="panel-body">-->
                    <div class="panel-body clearfix list_margin">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th><a href="<?php echo $this->url(array('key' => 'firstname', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'firstname' ? 'desc' : 'asc')) ?>">Name</a></th>
                                        <th><a title="Sort" href="<?php echo $this->url(array('key' => 'joining_date', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'joining_date' ? 'desc' : 'asc')) ?>">Joined Date</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'available_credits', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'available_credits' ? 'desc' : 'asc')) ?>">Available credits</a></th>
                                       	<th><a href="<?php echo $this->url(array('key' => 'active_alerts', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'active_alerts' ? 'desc' : 'asc')) ?>">Active Alerts</a></th>
                                        <th>Phone</th>
                                        <th>Email</th>
                                        <th>Actions </th>   
                                    </tr>
                                </thead>
                                <?php if (!empty($this->clients['rows'])) { ?>
                                    <tbody>

                                        <?php foreach ($this->clients['rows'] as $client) { ?>
                                            <tr>
                                                <td><a title="Edit"  href="<?php echo ADMIN_URL ?>client/profile/modify/<?php echo $client['client_id'] ?>" > <?php echo $client['firstname'] . ' ' . $client['lastname'] ?></a> </td>
                                                <td><?php echo date(DATE_FORMAT, strtotime($client['joining_date'])) ?></td>

                                                <td><?php echo $client['available_credits']?$client['available_credits']:0 ?> </td>
                                                <td><?php echo $client['active_alerts']?$client['active_alerts']:0 ?> </td>
                                                <td><?php echo $client['phone']?$client['phone']:"-" ?> </td>
                                                <td><a href="mailto:<?php echo $client['username'] ?>" ><?php echo $client['username'] ?></a> </td>
                                                <td class="table_input_padding text-center">


                                                    <a class="btn btn-primary btn-xs" href="<?php echo ADMIN_URL ?>client/profile/modify/<?php echo $client['client_id'] ?>" ><i class="fa fa-pencil"></i> </a>

                                                    <a class="btn btn-danger btn-xs " onclick="if (confirm('Are you sure wants to delete \'<?php echo $client['firstname'] . ' ' . $client['lastname'] ?>\'?'))
                                                                            return true;
                                                                        else
                                                                            return false;" title="Delete" href="<?php echo ADMIN_URL ?>client/delete/id/<?php echo $client['client_id'] ?>"><i class="fa fa-trash-o"></i>
                                                    </a>



                                                </td>

                                            </tr>

                                        <?php } ?>
                                    </tbody>
                                <?php } ?>
                            </table>


                            <?php
                            echo $this->paginationControl($this->paginator, 'Sliding', 'client/pagination.phtml');
                            ?>
                        </section>
                    </div>


                </section>
            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->
<div class="sb-slidebar sb-right sb-style-overlay">
    <h5 class="side-title">Online Customers</h5>
    <ul class="quick-chat-list">
        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
<!--                          <img alt="" src="img/chat-avatar2.jpg" class="media-object">-->
                </a>
                <div class="media-body">
                    <strong>John Doe</strong>
                    <small>Dream Land, AU</small>
                </div>
            </div><!-- media -->
        </li>
        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
<!--                          <img alt="" src="img/chat-avatar.jpg" class="media-object">-->
                </a>
                <div class="media-body">
                    <div class="media-status">
                        <span class=" badge bg-important">3</span>
                    </div>
                    <strong>Jonathan Smith</strong>
                    <small>United States</small>
                </div>
            </div><!-- media -->
        </li>

        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
<!--                          <img alt="" src="img/pro-ac-1.png" class="media-object">-->
                </a>
                <div class="media-body">
                    <div class="media-status">
                        <span class=" badge bg-success">5</span>
                    </div>
                    <strong>Jane Doe</strong>
                    <small>ABC, USA</small>
                </div>
            </div><!-- media -->
        </li>
        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
<!--                          <img alt="" src="img/avatar1.jpg" class="media-object">-->
                </a>
                <div class="media-body">
                    <strong>Anjelina Joli</strong>
                    <small>Fockland, UK</small>
                </div>
            </div><!-- media -->
        </li>
        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
<!--                          <img alt="" src="img/mail-avatar.jpg" class="media-object">-->
                </a>
                <div class="media-body">
                    <div class="media-status">
                        <span class=" badge bg-warning">7</span>
                    </div>
                    <strong>Mr Tasi</strong>
                    <small>Dream Land, USA</small>
                </div>
            </div><!-- media -->
        </li>
    </ul>
    <h5 class="side-title"> pending Task</h5>
    <ul class="p-task tasks-bar">
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Dashboard v1.3</div>
                    <div class="percent">40%</div>
                </div>
                <div class="progress progress-striped">
                    <div style="width: 40%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" class="progress-bar progress-bar-success">
                        <span class="sr-only">40% Complete (success)</span>
                    </div>
                </div>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Database Update</div>
                    <div class="percent">60%</div>
                </div>
                <div class="progress progress-striped">
                    <div style="width: 60%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-warning">
                        <span class="sr-only">60% Complete (warning)</span>
                    </div>
                </div>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Iphone Development</div>
                    <div class="percent">87%</div>
                </div>
                <div class="progress progress-striped">
                    <div style="width: 87%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" class="progress-bar progress-bar-info">
                        <span class="sr-only">87% Complete</span>
                    </div>
                </div>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Mobile App</div>
                    <div class="percent">33%</div>
                </div>
                <div class="progress progress-striped">
                    <div style="width: 33%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" class="progress-bar progress-bar-danger">
                        <span class="sr-only">33% Complete (danger)</span>
                    </div>
                </div>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Dashboard v1.3</div>
                    <div class="percent">45%</div>
                </div>
                <div class="progress progress-striped active">
                    <div style="width: 45%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" class="progress-bar">
                        <span class="sr-only">45% Complete</span>
                    </div>
                </div>

            </a>
        </li>
        <li class="external">
            <a href="#">See All Tasks</a>
        </li>
    </ul>
</div>

<script>
    function saveRate(th) {
        //alert(th.value);
        //alert(th.name);
        $.ajax({url: "<?php echo ADMIN_URL . 'client/events/' ?>",
            data: {rate: th.value, saverate: 'rate', job_id: $(th).attr('rel')}, success: function (data) {
            }
        });
    }


    function printpage()
    {
        window.print()
    }

</script>