
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">
              <!-- page start-->
              <div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
              <!--  <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
                        <ul class="nav nav-tabs pull-right">
                            <?php //include_once('tabs.phtml');?>
                        </ul>
                        <span class="hidden-sm wht-color"> <?php //echo $this->userInfo['firstname'] . ' ' . $this->userInfo['lastname'] ?> </span>
                    </header>-->
                     <!--header fixes -->
	                    <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
	                        <ul class="nav nav-tabs pull-left">
	                        <li>     
	                        	<span class="profile_name"><?php echo $this->userInfo['firstname'] . ' ' . $this->userInfo['lastname'] ?></span>
	                        </li>
	                            <?php include_once('tabs.phtml'); ?>
	                        </ul>
	                    </header>
	                     <div class="clearfix"></div>
                    <!--end header fixes -->
               </section>
               
              
                      <section class="panel">
                          <header class="panel-heading clearfix">
                              Open Jobs
                              <a href="<?php echo ADMIN_URL?>jobs/view/status/open/client_id/<?php echo $this->userInfo['userid'];?>" class="label label-success pull-right">View all Open Jobs</a>
                          <a href="<?php echo ADMIN_URL?>client/events/user/<?php echo $this->userInfo['userid'];?>" class="label label-danger pull-right mar-right">Add New Job</a>
                          </header>
                          <div class="panel-body">
                              <section id="flip-scroll">
                                  <table class="table table-bordered table-striped table-condensed cf">
                                      <thead class="cf">
                                      <tr>
                                        <th>Job Number</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Client Name</th>
                                        <th>Sitter Name</th>
                                        <th>Cancelled Date & Time</th>
                                        <th>Special Status</th>
                                        <th>Active Alerts</th>
                                        <th>Actions</th>
                                    </tr>
                                      </thead>
                                      <tbody>
                                      <?php 
					if(!empty($this->open['rows']))
					foreach($this->open['rows'] as $job){?>
                                        <tr class="first"><!-- .first for first row of the table (only if there is thead) -->
					<td><a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>"><?php echo $this->jobnumber($job['job_id']);?></a></td>
					<td><?php echo date(DATETIME_FORMAT,strtotime($job['job_start_date']));?></td>
					<td ><?php echo date(DATETIME_FORMAT,strtotime($job['job_end_date']));?></td>
					<td ><a href="<?php echo ADMIN_URL.'client/profile/modify/'.$job['client_user_id']?>"><?php echo ucwords($job['firstname'].' '.$job['lastname']);?></a></td>
                    <td><?php echo "-";?> </td>
                    <td>  <?php echo "NA"; ?></td>
                    <?php if ($job['is_special']==1 || $job['is_special']=='1') { ?>
                      <td ><?php echo "S";?></td>
                    <?php }
                    else{ ?><td ><?php echo "NA";?></td><?php } 
                     if ($job['alerts']>0) { ?>
                       <td ><?php echo "A";?></td>
                     <?php }
                     else{ ?><td ><?php echo "NA";?></td><?php }?> 
                     <td class="table_input_padding text-center">
                         <a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i> </a>
                         <button onclick="confirmDelete(<?php echo $job['client_user_id'];?>,<?php echo $job['job_id'];?>);" class="btn btn-danger btn-xs "><i class="fa fa-trash-o"></i></button>
                     </td>
				</tr>
                                  <?php }else {?>
				          <tr><td colspan="9"><div >No Jobs Posted yet. To create a new job <a href="<?php echo ADMIN_URL ?>client/events/user/<?php echo $this->userid ?>" class="btn btn-info">Click here</a></div></td>
				          <!-- <td colspan="8">No records found.</td> --></tr>
                         <?php }?>
                                      </tbody>
                                  </table>
                              </section>
                          </div>
                      </section>
                
              <div class="clearfix"></div>
             
                      <section class="panel">
                          <header class="panel-heading clearfix">
                              Scheduled Jobs
                              <a href="<?php echo ADMIN_URL?>jobs/view/status/scheduled/client_id/<?php echo $this->userInfo['userid'];?>" class="label label-success pull-right">View all Scheduled Jobs</a>
                          </header>
                          <div class="panel-body">
                              <section id="flip-scroll">
                                  <table class="table table-bordered table-striped table-condensed cf">
                                      <thead class="cf">
                                      <tr>
                                        <th>Job Number</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Client Name</th>
                                        <th>Sitter Name</th>
                                        <th>Cancelled Date & Time</th>
                                        <th>Special Status</th>
                                        <th>Active Alerts</th>
                                        <th>Actions</th>
                                    </tr>
                                      </thead>
                                      <tbody>
                                       <?php if(!empty($this->scheduled['rows'])){?>
						 <?php foreach($this->scheduled['rows'] as $job){?>
						      <tr class="first"><!-- .first for first row of the table (only if there is thead) -->
							<td><a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>"><?php echo $this->jobnumber($job['job_id']);?></a></td>
							<td><?php echo date(DATE_FORMAT,strtotime($job['job_start_date']));?><span class="tc"> - </span><?php echo date('h:i a',strtotime($job['job_start_date']));?></td>
							<td><?php echo date(DATETIME_FORMAT,strtotime($job['job_end_date']));?></td>
							<td><a href="<?php echo ADMIN_URL.'client/profile/modify/'.$job['client_user_id']?>"><?php echo ucwords($job['firstname'].' '.$job['lastname']);?></a></td>
							<td><a href="<?php echo ADMIN_URL . 'sitters/profile/modify/' . $job['sitter_user_id'] ?>"> <?php echo $job['sitter_firstname'] . ' ' . $job['sitter_lastname'] ?></a></td>
							<td>  <?php echo "NA"; ?></td>
							<?php if ($job['is_special']==1 || $job['is_special']=='1') { ?>
                                                <td ><?php echo "S";?></td>
                                            <?php }else{ ?><td ><?php echo "NA";?></td><?php } 
                                           if ($job['alerts']>0) { ?>
                                             <td ><?php echo "A";?></td>
                                              <?php }else{ ?><td ><?php echo "NA";?></td><?php } ?>
                            	<td class="table_input_padding text-center">
                         			<a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>" class="btn btn-primary btn-xs "><i class="fa fa-pencil"></i> </a>
                         			<button onclick="confirmDelete(<?php echo $job['client_user_id'];?>,<?php echo $job['job_id'];?>);" class="btn btn-danger btn-xs "><i class="fa fa-trash-o"></i></button>
                     			</td>
                              </tr>
						      <?php }?>
				          <?php }else {?>
				          <tr><td colspan="9">No records found.</td></tr>
                         <?php }?>
					        </tbody>
                                     
                                  </table>
                              </section>
                          </div>
                      </section>
                 
              
              
                      <section class="panel">
                          <header class="panel-heading clearfix">
                              Active Jobs
                              <a href="<?php echo ADMIN_URL?>jobs/view/status/active/client_id/<?php echo $this->userInfo['userid'];?>" class="label label-success pull-right">View all Active Jobs</a>
                          </header>
                          <div class="panel-body">
                              <section id="flip-scroll">
                                  <table class="table table-bordered table-striped table-condensed cf">
                                      <thead class="cf">
                                      <tr>
                                        <th>Job Number</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Client Name</th>
                                        <th>Sitter Name</th>
                                        <th>Cancelled Date & Time</th>
                                        <th>Special Status</th>
                                        <th>Active Alerts</th>
                                        <th>Actions</th>
                                    </tr>
                                      </thead>
                                      <tbody>
                                     <?php if(!empty($this->active['rows'])){?>
						    
				       <?php foreach($this->active['rows'] as $job){?>
				<tr class="first"><!-- .first for first row of the table (only if there is thead) -->
					<td><a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>"><?php  echo $this->jobnumber($job['job_id']);?></a></td>
					<td ><?php echo date(DATETIME_FORMAT,strtotime($job['job_start_date']));?></td>
					<td ><?php echo date(DATETIME_FORMAT,strtotime($job['job_end_date']));?></td>
					<td><a href="<?php echo ADMIN_URL.'client/profile/modify/'.$job['client_user_id']?>"><?php echo ucwords($job['firstname'].' '.$job['lastname']);?></a></td>
					<td> <a href="<?php echo ADMIN_URL . 'sitters/profile/modify/' . $job['sitter_user_id'] ?>"> <?php echo $job['sitter_firstname'] . ' ' . $job['sitter_lastname'] ?></a></td>
							<td>  <?php echo "NA"; ?></td>
							<?php if ($job['is_special']==1 || $job['is_special']=='1') { ?>
                                                <td ><?php echo "S";?></td>
                                            <?php }else{ ?><td ><?php echo "NA";?></td><?php } 
                                           if ($job['alerts']>0) { ?>
                                             <td ><?php echo "A";?></td>
                                              <?php }else{ ?><td ><?php echo "NA";?></td><?php } ?>
                   <td class="table_input_padding text-center">
                      <a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i> </a>
                      <button onclick="confirmDelete(<?php echo $job['client_user_id'];?>,<?php echo $job['job_id'];?>);" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button>
                   </td>
               </tr>
				           <?php }?>
				          <?php }else {?>
				           <tr><td colspan="9" >No records found.</td></tr>
                         <?php }?>
                                      </tbody>
                                  </table>
                              </section>
                          </div>
                      </section>
                 
              
             
                      <section class="panel">
                          <header class="panel-heading clearfix">
                              Completed Jobs
                              <a href="<?php echo ADMIN_URL?>jobs/view/status/completed/client_id/<?php echo $this->userInfo['userid'];?>" class="label label-success pull-right">View all Completed Jobs</a>
                          </header>
                          <div class="panel-body">
                              <section id="flip-scroll">
                                  <table class="table table-bordered table-striped table-condensed cf">
                                      <thead class="cf">
                                      <tr>
                                        <th>Job Number</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Client Name</th>
                                        <th>Sitter Name</th>
                                        <th>Babysitting Fee</th>
                                        <th>Charge Client</th>
                                        <th>Sitter Paid?</th>
					<th>Actions</th>
                                    </tr>
                                      </thead>
                                      <tbody>
                                    <?php if(!empty($this->completed['rows'])){?>
                                          <?php foreach($this->completed['rows'] as $job){?>
						      <tr class="first"><!-- .first for first row of the table (only if there is thead) -->
					<td><a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>"><?php  echo $this->jobnumber($job['job_id']);?></a></td>
					<td ><?php echo date(DATETIME_FORMAT,strtotime($job['job_start_date']));?></td>
					<td ><?php echo date(DATETIME_FORMAT,strtotime($job['completed_date']));?></td>
					<td ><a href="<?php echo ADMIN_URL.'client/profile/modify/'.$job['client_user_id']?>"><?php echo ucwords($job['firstname'].' '.$job['lastname'])?></a></td>
                    <td> <a href="<?php echo ADMIN_URL . 'sitters/profile/modify/' . $job['sitter_user_id'] ?>"> <?php echo $job['sitter_firstname'] . ' ' . $job['sitter_lastname'] ?></a></td>
												<?php 	if($job['total_received']==0 ||$job['total_received']==null)
                                            	{	
	                                            	if (($job['client_updated_rate'] == "") || ($job['client_updated_rate'] == null)) {
	                                            		$rate = $job['client_rate'];
	                                            	} else {
	                                            		$rate = $job['client_updated_rate'];
	                                            	}
	                                            	
	                                            	if($job['completed_date']!='0000-00-00 00:00:00' && $job['completed_date']!=null)
	                                            	{
	                                            		$end_date=$job['completed_date'];
	                                            	}
	                                            	else 
	                                            	{
	                                            		$end_date = $job['job_end_date'];
	                                            	}
	                                            	
	                                            	if (strtotime($end_date) < strtotime($job['job_start_date'])) {
	                                            		$end_date = $job['job_end_date'];
	                                            	}
	                                            	
	                                            	if($job['immidiate_cancelled']=='yes' && strtotime($job['job_start_date']) > strtotime($job['cancelled_date']))
	                                            		$total_hours = 3;
	                                            	else 
	                                            		$total_hours = round((strtotime(date('Y-m-d H:i:s',strtotime($end_date)))-strtotime(date('y-m-d H:i:s',strtotime($job['job_start_date']))))/(60*60),2);
	                           
	                                            	$job['total_received'] = $total_hours*$rate;
                                            	}
                                            	
                                            	if($job['client_payment_status']=='unpaid')
                                            	{
                                            		$client_paid = 'Outstand';
                                            		$btn_class=" btn-danger";
                                            	}
                                            	else 
                                            	{
                                            		$client_paid = 'Charged';
                                            		$btn_class=" btn-success";
                                            	}
                                            	if($job['sitter_payment_status']=='unpaid')
                                            	{
                                            		$sitter_paid = 'Owed';
                                            		$btn_class1=" btn-danger";
                                            	}
                                            	else
                                            	{
                                            		$sitter_paid = 'Paid';
                                            		$btn_class1=" btn-success";
                                            	}
                                            	?>
                                            	<td class="numeric" ><?php echo "$".$job['total_received'];?></td>
                                            	<td ><input type="submit" class="btn<?php echo $btn_class;?>" value="<?php echo $client_paid;?>" onclick="window.location = '<?php echo ADMIN_URL . 'client/events/user/' . $job['client_user_id'] . '/modify/' . $job['job_id'] ?>'"  /></td>
                                            	<td ><input type="submit" class="btn<?php echo $btn_class1;?>" value="<?php echo $sitter_paid;?>" <?php if($sitter_paid=='Owed'){?>onclick="paysitter(<?php echo $job['sitter_user_id']?>);" <?php }?> /></td>
                                            			<td class="table_input_padding text-center">
							                      <a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i> </a>
							                      <button onclick="confirmDelete(<?php echo $job['client_user_id'];?>,<?php echo $job['job_id'];?>);" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button>
							                   </td>	
										<!-- a.ico-comms for comment-like backgrounds -->
									</tr>
				          <?php }?>
				          <?php }else {?>
				           <tr><td colspan="9">No records found.</td></tr>
                         <?php }?>
                                      </tbody>
                                  </table>
                              </section>
                          </div>
                      </section>
               
              
                      <section class="panel">
                          <header class="panel-heading clearfix">
                              Closed Jobs
                              <a href="<?php echo ADMIN_URL?>jobs/view/status/closed/client_id/<?php echo $this->userInfo['userid'];?>" class="label label-success pull-right">View all Closed Jobs</a>
                          </header>
                          <div class="panel-body">
                              <section id="flip-scroll">
                                  <table class="table table-bordered table-striped table-condensed cf">
                                      <thead class="cf">
                                      <tr>
                                        <th>Job Number</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Client Name</th>
                                        <th>Sitter Name</th>
                                        <th>Babysitting Fee</th>
                                        <th>Charge Client</th>
                                        <th>Sitter Paid?</th>
                                        
                                        
                                    </tr>
                                      </thead>
                                      <tbody>
                                    <?php if(!empty($this->closed['rows'])){?>
                                          <?php foreach($this->closed['rows'] as $job){?>
						      <tr class="first"><!-- .first for first row of the table (only if there is thead) -->
					<td><a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>"><?php  echo $this->jobnumber($job['job_id']);?></a></td>
					<td ><?php echo date(DATETIME_FORMAT,strtotime($job['job_start_date']));?></td>
					<td ><?php echo date(DATETIME_FORMAT,strtotime($job['completed_date']));?></td>
					<td ><a href="<?php echo ADMIN_URL.'client/profile/modify/'.$job['client_user_id']?>"><?php echo ucwords($job['firstname'].' '.$job['lastname'])?></a></td>
				<td> <a href="<?php echo ADMIN_URL . 'sitters/profile/modify/' . $job['sitter_user_id'] ?>"> <?php echo $job['sitter_firstname'] . ' ' . $job['sitter_lastname'] ?></a></td>
												<?php 	if($job['total_received']==0 ||$job['total_received']==null)
                                            	{	
	                                            	if (($job['client_updated_rate'] == "") || ($job['client_updated_rate'] == null)) {
	                                            		$rate = $job['client_rate'];
	                                            	} else {
	                                            		$rate = $job['client_updated_rate'];
	                                            	}
	                                            	
	                                            	if($job['completed_date']!='0000-00-00 00:00:00' && $job['completed_date']!=null)
	                                            	{
	                                            		$end_date=$job['completed_date'];
	                                            	}
	                                            	else 
	                                            	{
	                                            		$end_date = $job['job_end_date'];
	                                            	}
	                                            	
	                                            	if($job['immidiate_cancelled']=='yes' && strtotime($job['job_start_date']) > strtotime($job['cancelled_date']))
	                                            		$total_hours = 3;
	                                            	else 
	                                            		$total_hours = round((strtotime(date('Y-m-d H:i:s',strtotime($end_date)))-strtotime(date('y-m-d H:i:s',strtotime($job['job_start_date']))))/(60*60),2);
	                           
	                                            	$job['total_received'] = $total_hours*$rate;
                                            	}
                                            	
                                            	if($job['client_payment_status']=='unpaid')
                                            	{
                                            		$client_paid = 'Outstand';
                                            		$btn_class=" btn-danger";
                                            	}
                                            	else 
                                            	{
                                            		$client_paid = 'Charged';
                                            		$btn_class=" btn-success";
                                            	}
                                            	if($job['sitter_payment_status']=='unpaid')
                                            	{
                                            		$sitter_paid = 'Owed';
                                            		$btn_class1=" btn-danger";
                                            	}
                                            	else
                                            	{
                                            		$sitter_paid = 'Paid';
                                            		$btn_class1=" btn-success";
                                            	}
                                            	?>
                                            	<td class="numeric" ><?php echo "$".$job['total_received'];?></td>
                                            	<td ><input type="submit" class="btn<?php echo $btn_class;?>" value="<?php echo $client_paid;?>" onclick="window.location = '<?php echo ADMIN_URL . 'client/events/user/' . $job['client_user_id'] . '/modify/' . $job['job_id'] ?>'"  /></td>
                                            	<td ><input type="submit" class="btn<?php echo $btn_class1;?>" value="<?php echo $sitter_paid;?>" <?php if($sitter_paid=='Owed'){?>onclick="paysitter(<?php echo $job['sitter_user_id']?>);" <?php }?> /></td>
                                            
										<!-- a.ico-comms for comment-like backgrounds -->
									</tr>
				          <?php }?>
				          <?php }else {?>
				           <tr><td colspan="8">No records found.</td></tr>
                         <?php }?>
                                      </tbody>
                                  </table>
                              </section>
                          </div>
                      </section>
             
                      <section class="panel">
                          <header class="panel-heading clearfix">
                              Cancelled Jobs
                              <a href="<?php echo ADMIN_URL?>jobs/view/status/cancelled/client_id/<?php echo $this->userInfo['userid'];?>" class="label label-success pull-right">View all Cancelled Jobs</a>
                          </header>
                          <div class="panel-body">
                              <section id="flip-scroll">
                                  <table class="table table-bordered table-striped table-condensed cf">
                                      <thead class="cf">
                                      <tr>
                                        <th>Job Number</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Client Name</th>
                                        <th>Sitter Name</th>
                                        <th>Cancelled Date & Time</th>
                                        <th>Special Status</th>
                                        <th>Active Alerts</th>
                                    </tr>
                                      </thead>
                                      <tbody>
                                    <?php if(!empty($this->cancelled['rows'])){?>
                                          <?php foreach($this->cancelled['rows'] as $job){?>
						      <tr class="first"><!-- .first for first row of the table (only if there is thead) -->
					<td><a href="<?php echo ADMIN_URL.'client/events/user/'.$job['client_user_id'].'/modify/'.$job['job_id']?>"><?php  echo $this->jobnumber($job['job_id']);?></a></td>
					<td ><?php echo date(DATETIME_FORMAT,strtotime($job['job_start_date']));?></td>
					<td ><?php echo date(DATETIME_FORMAT,strtotime($job['job_end_date']));?></td>
					<td ><a href="<?php echo ADMIN_URL.'client/profile/modify/'.$job['client_user_id']?>"><?php echo ucwords($job['firstname'].' '.$job['lastname'])?></a></td>
				    <td> <a href="<?php echo ADMIN_URL . 'sitters/profile/modify/' . $job['sitter_user_id'] ?>"> <?php echo $job['sitter_firstname'] . ' ' . $job['sitter_lastname'] ?></a></td>
                    <td><?php echo date(DATETIME_FORMAT, strtotime($job['cancelled_date'])); ?></td>
											<?php if ($job['is_special']==1 || $job['is_special']=='1') { ?>
                                                <td ><?php echo "S";?></td>
                                            <?php }else{ ?><td ><?php echo "NA";?></td><?php } 
                                           if ($job['alerts']>0) { ?>
                                             <td ><?php echo "A";?></td>
                                              <?php }else{ ?><td ><?php echo "NA";?></td><?php } ?>
										<!-- a.ico-comms for comment-like backgrounds -->
									</tr>
				          <?php }?>
				          <?php }else {?>
				           <tr><td colspan="8">No records found.</td></tr>
                         <?php }?>
                                      </tbody>
                                  </table>
                              </section>
                          </div>
                      </section>
              </div>
           </div>
              <!-- page end-->
          </section>
      </section>
      <!--main content end-->
      <!-- Right Slidebar start -->
       
<div class="modal fade" tabindex="-1" role="dialog" id="confirmdelete">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete Job</h4>
      </div>
      <div class="modal-body">
        <div id="jobmsg"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a id="deletejob" href=""  class="btn btn-danger">Delete</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
      
 <script>
        function confirmDelete(client_id,job_id)     
        {
            $('#jobmsg').html('<p>Are you sure wants to delete Job '+job_id+'?</p>');
            $('#deletejob').attr('href','<?php echo ADMIN_URL?>client/events/user/'+client_id+'/delete/'+job_id);
            $('#confirmdelete').modal('show');
        }
 </script>     
     
      
      
      
      
      
      
