<?php
$errors = $this->userform->getMessages();
if (!empty($errors))
    $this->errorMessage = 'Error while create/update client! Please verify your fields';

foreach ($errors as $key => $err) {
    if (!isset($err[0])) {
        foreach ($err as $key2 => $r)
            $er[$key . '[' . $key2 . ']'] = implode(', ', $r);
    } else
        $er[$key] = implode(', ', $err);
}
$errors = $er;

// echo $this->userform->setAction($this->url()); 
?>
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel clearfix">
                    <!--  <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
                        <ul class="nav nav-tabs pull-right">
                            <?php //include_once('tabs.phtml'); ?>
                        </ul>
                        <span class="hidden-sm wht-color"><?php //echo $this->userform->firstname->getValue() ?> <?php //echo $this->userform->lastname->getValue() ?> <?php //echo $this->userform->firstname->getValue() != '' ? '-' : '' ?> Profile</span>
                    </header> -->
					<!--header fixes -->
                    <div class="fixed-position col-lg-11">
	                    <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
	                        <ul class="nav nav-tabs pull-left">
	                        <li>     
	                        	<span class="profile_name"><?php echo $this->userform->firstname->getValue() ?> <?php echo $this->userform->lastname->getValue() ?> <?php echo $this->userform->firstname->getValue() != '' ? '-' : '' ?> Profile</span>
	                        </li>
	                            <?php include_once('tabs.phtml'); ?>
	                        </ul>
	                    </header>
                    </div>
                     <div class="clearfix"></div>
                    <!--end header fixes -->
                    <div class="panel-body list_margin">

                        <?php if ($this->successMessage != '') { ?>
                            <div style="color:#3c763d"><p><?php echo $this->successMessage; ?></p></div>
                        <?php } ?>

                        <?php if ($this->errorMessage != '') { ?>
                            <div class="error"><p><?php echo $this->errorMessage; ?></p></div>
                        <?php } ?> 

                        <form class="cmxform form-horizontal tasi-form custom-form" id="userform" method="post" enctype="multipart/form-data" action="<?php echo $this->userform->getAction(); ?>" >
                            <dl class="zend_form">
                                <section class="clearfix">
                                    <h4>Basic Information</h4>
                                    <div class="border-top m-bot20"></div>
                                    <div class="col-sm-6">
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">First Name</label>
                                            <div class="col-lg-9">
                                                <input name="firstname" type="text" class="form-control" id="firstname" value="<?php echo $this->userform->firstname->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label class="control-label col-lg-3">Last Name</label>
                                            <div class="col-lg-9">
                                                <input name="lastname" type="text" class="form-control" id="lastname" value="<?php echo $this->userform->lastname->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Other Guardian</label>
                                            <div class="col-lg-9">
                                                <input name="spouse_firstname" type="text" class="form-control" id="spouse_firstname" value="<?php echo $this->userform->spouse_firstname->getValue() ?>" />
                                            </div>
                                        </div>

                                        <strong>Emergency Contact</strong>

                                        <div class="clearfix"></div>

                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Name</label>
                                            <div class="col-lg-9">
                                                <input name="emergency_contact" type="text" class="form-control" id="emergency_contact" value="<?php echo $this->userform->emergency_contact->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3"> Phone</label>
                                            <div class="col-lg-9">
                                                <input name="emergency_phone" type="text" class="form-control" id="emergency_phone" value="<?php echo $this->userform->emergency_phone->getValue() ?>" />
                                            </div>
                                        </div>




                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Mobile</label>
                                            <div class="col-lg-9">
                                                <input name="phone" type="text" class="form-control" id="phone" value="<?php echo $this->userform->phone->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="cemail" class="control-label col-lg-3">Local Phone</label>
                                            <div class="col-lg-9">
                                                <input name="local_phone" type="text" class="form-control" id="local_phone" value="<?php echo $this->userform->local_phone->getValue() ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Work Phone</label>
                                            <div class="col-lg-9">
                                                <input name="work_phone" type="text" class="form-control" id="work_phone" value="<?php echo $this->userform->work_phone->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Email</label>
                                            <div class="col-lg-9">
                                                <input name="username" type="text" class="form-control" id="username" value="<?php echo $this->userform->username->getValue() ?>" />
                                            </div>
                                        </div>




                                    </div>
                                </section>
                                <div class="clearfix"></div>
                                <section class="clearfix">
                                    <h4>Local Adress</h4>
                                    <div class="border-top m-bot20"></div>
                                    <div class="col-sm-6">
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Hotel Name(if applicable)</label>
                                            <div class="col-lg-9">
                                                <input name="local[billing_name]" type="text" class="form-control" id="billing_name" value="<?php echo $this->userform->local->billing_name->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label class="control-label col-lg-3">Cross Street</label>
                                            <div class="col-lg-9">
                                                <input type="text" class="form-control required" name="local[address_1]" id="local_address_1" value="<?php echo $this->userform->local->address_1->getValue() ?>">
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Street Address</label>
                                            <div class="col-lg-9">
                                                <input type="text" class="form-control required" name="local[streat_address]" id="local_streat_address" value="<?php echo $this->userform->local->streat_address->getValue() ?>">
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">City</label>
                                            <div class="col-lg-9">
                                                <input name="local[city]" id="local_city" type="text" class="form-control required"  value="<?php echo $this->userform->local->city->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">State</label>
                                            <div class="col-lg-9">
                                                <select id="local_state" name="local[state]" class="form-control required">

                                                    <option value="">Select State</option>

                                                    <?php foreach ($this->userform->local->state->getMultiOptions() as $key => $option) { ?>
                                                        <option value="<?php echo $key ?>" <?php echo $this->userform->local->state->getValue() == $key ? 'selected="selected"' : '' ?>><?php echo $option ?></option>
                                                    <?php } ?>

                                                </select>
                                                <input type="hidden" name="local[country]" value="223" />

                                            </div>
                                        </div>

                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Zip</label>
                                            <div class="col-lg-9">
                                                <input name="local[zipcode]" id="local_zipcode" type="text" class="form-control required"  value="<?php echo $this->userform->local->zipcode->getValue() ?>" />
                                            </div>
                                        </div>                                    




                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group ">

                                            <div class="btn-group" data-toggle="buttons">    
                                                <label class="btn btn-info chk <?php echo $this->billing_diff_local ? 'active' : '' ?> ">
                                                    <input  type="checkbox" id="billing-address_type" name="billing[address_type]" <?php echo $this->billing_diff_local ? 'checked="checked"' : '' ?> value="<?php echo $this->userform->billing->address_type->getValue() ?>"  autocomplete="off" /> 

                                                    <span class="glyphicon glyphicon-ok"></span>          

                                                </label>
                                                Billing Address if different.
                                            </div>

                                        </div>
                                        <div class="form-group ">
                                            <label for="cemail" class="control-label col-lg-3">Street Address</label>
                                            <div class="col-lg-9">
                                                <input name="billing[streat_address]" type="text" class="form-control" id="billing-streat_address" value="<?php echo $this->userform->billing->streat_address->getValue() ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group ">
                                            <label for="cemail" class="control-label col-lg-3">City</label>
                                            <div class="col-lg-9">
                                                <input name="billing[city]" type="text" class="form-control" id="billing-city" value="<?php echo $this->userform->billing->city->getValue() ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">State</label>
                                            <div class="col-lg-9">
                                                <select id="billing_state" name="billing[state]" class="form-control">

                                                    <option value="">Select State</option>
                                                    <?php foreach ($this->userform->billing->state->getMultiOptions() as $key => $option) { ?>
                                                        <option value="<?php echo $key ?>" <?php echo $this->userform->billing->state->getValue() == $key ? 'selected="selected"' : '' ?>><?php echo $option ?></option>
                                                    <?php } ?>


                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Country</label>
                                            <div class="col-lg-9">
                                                <select  onchange="changeState(this);" name="billing[country]" class="form-control">

                                                    <option value="">Select Country</option>
                                                    <?php foreach ($this->userform->billing->country->getMultiOptions() as $key => $option) { ?>
                                                        <option value="<?php echo $key ?>" <?php echo $this->userform->billing->country->getValue() == $key ? 'selected="selected"' : '' ?>><?php echo $option ?></option>
                                                    <?php } ?>


                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Zip</label>
                                            <div class="col-lg-9">
                                                <input name="billing[zipcode]" type="text" class="form-control" id="billing-zipcode" value="<?php echo $this->userform->billing->zipcode->getValue() ?>" />
                                            </div>
                                        </div>
                               </div>
                                </section>
                              <h4>Notes about client</h4>
                                            
                              <div class="border-top m-bot20"></div>  
                                
                                 <div class="form-group col-lg-12">
                                     <textarea id="clientnotes" name="clientnotes" class="form-control"><?php echo $this->userform->clientnotes->getValue() ?></textarea>
                                 </div>

                                
                                <div class="form-group clearfix">
                                    <div class="m-bot20 m-top20">
                                        <input class="btn btn-danger" type="submit" value="Update" />
                                        <input class="btn btn-default" type="reset" value="Back" onclick="history.back()"/>

                                    </div>
                                </div>


                            </dl>
                        </form>
                    </div>
                </section>



            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<!--main content end-->

<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>

<script type="text/javascript">
$(document).ready(function () {
    
    
     $.validator.addMethod("alpha", function(value, element) {
     return this.optional(element) || value == value.match(/^[a-zA-Z\s]+$/); });

    // validate signup form on keyup and submit

    var validator = $("#userform").validate({
        rules: {
            firstname: {
                required: true,
                alpha:true,
            },
            lastname: {
                required: true,
                 alpha:true,
            },
            dob: {
                required: true
            },
            username: {
                required: true,
                email: true
            },
            password: {
                required: true
            }, profile_image: {
                required: false

            }, phone: {
                required: true

            },
            'local[address_1]': {
                required: false
            },
            'local[streat_address]': {
                required: true
            },
            'local[zipcode]': {
                required: true,
                number: true
            },
            'local[city]': {
                required: true

            },
            'local[state]': {
                required: true

            },
            'billing[streat_address]': {
                required: function () {
                    return $('#billing-address_type').is(':checked')
                }
            },
            'billing[zipcode]': {
                required: function () {
                    return $('#billing-address_type').is(':checked')
                }
            },
            'billing[city]': {
                required: function () {
                    return $('#billing-address_type').is(':checked')
                }


            },
            'billing[state]': {
                required: function () {
                    return $('#billing-address_type').is(':checked')
                }
            }

        },
        messages: {
            firstname: {
                required: 'Please enter the First Name',
                 alpha:'Plese enter the valid First Name',
            },
            lastname: {
                required: 'Please enter the Last Name',
                 alpha:'Plese enter the valid Last Name',
            },
            dob: {
                required: 'Please enter the Date of Birth'
            },
            username: {
                required: 'This email is used for login/primary Email address',
                email: "Your email address must be in the format of name@domain"

            },
            profile_image: {
                required: ''

            }, phone: {
                required: 'Please provide your phone number'
            }
        },
        // the errorPlacement has to take the table layout into account
        errorPlacement: function (error, element) {
            //alert(element.attr('type'));
            if (element.is(":radio"))
                error.appendTo(element.parent().next().next());
            else if (element.is(":checkbox"))
                error.appendTo(element.next());
            else {
                error.appendTo(element.parent());

            }
        },
        // specifying a submitHandler prevents the default submit, good for the demo
        submitHandler: function () {
            //$("#login").submit();
            document.getElementById('login').submit();
        },
        // set this class to error-labels to indicate valid fields
        success: function (label) {
            // set &nbsp; as text for IE
            label.html("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;").addClass("checked");
        }
    });

<?php
if (!empty($errors)) {
    echo "validator.showErrors(" . json_encode($errors) . ");";
}
?>

                                                //$("#login").valid();


                                            });

                                            function changeState(th) {
                                                $.ajax({
                                                    url: '<?php echo SITE_URL ?>misc/stateoptionsid',
                                                    data: {country_id: th.value},
                                                    success: function (data) {
                                                        $("#billing_state").html(data);
                                                    }
                                                });
                                            }
</script>

