
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel clearfix">
                    <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
                        <ul class="nav nav-tabs pull-right">
                            <?php include_once('tabs.phtml'); ?>
                        </ul>
                        <span class="hidden-sm wht-color"> <?php echo $this->userInfo['firstname'] . ' ' . $this->userInfo['lastname'] ?> </span>
                    </header>
                    <div class="panel-body">
                    	<div style="float:right;"><span><b>Total Available Credits: </b><?php echo $this->total_avail_credits;?></span></br></br></div>
                        <section id="flip-scroll">

                            <?php if (!empty($this->subscriptions)) { ?>
                                <table class="table table-bordered table-striped table-condensed cf">
                                    <thead class="cf">
                                        <tr>
                                            <th>Transaction ID</th>
                                            <th>Payment Gateway</th>
                                            <th>Date</th>
                                            <th>Description</th>
                                            <th class='text-right'>Amount</th>
                                            <th>Purchased Credits</th>
                                            <th>Remaining Credits from purchase</th>
                                            <th>Expires</th>
                                            <th>Actions</th>                      
                                        </tr>
                                   </thead>
                                    <tbody>	

                                        <?php foreach ($this->subscriptions as $sub) { ?>
                                            <tr>
                                                <td><?php echo $sub['transaction_id'] == 'No Payment' ? 'Free' : $sub['transaction_id'] ?> </td>
                                                <td><?php echo $sub['payment_gateway'] ?> </td>
                                                <td><?php echo date(DATE_FORMAT, strtotime($sub['last_modified_date'])) ?> </td>
                                                <td><?php echo $sub['notes'] ?></td>
                                                <td class='numeric'><?php echo $sub['payment_gateway'] != 'Free' ? '$' . $sub['price'] : 'No Charge' ?></td>
                                                <td><?php echo $sub['total_credits'] ?></td>
                                                <td><?php echo $sub['slots'] ?></td>
                                                <td><?php echo date(DATETIME_FORMAT, strtotime($sub['end_date'])) ?></td>
                                                <td class='text-center'>

                                                    <a class="btn btn-danger btn-xs fa fa-trash-o " onclick="if (confirm('Are you sure want to delete?'))
                                                                        return true;
                                                                    else
                                                                        return false;"  href="<?php echo ADMIN_URL . 'client/subscription/client/' . $this->userid . '/delete/' . $sub['client_sub_id'] ?>" title="Delete"></a>
                                                </td>


                                            </tr>
                                        <?php } ?>
                                    </tbody><?php } ?>
                            </table>
                            <?php
                            echo $this->paginationControl($this->paginator, 'Sliding', 'client/pagination.phtml');
                            ?>
                        </section>
                    </div>
                </section>



            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<!--main content end-->
