
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel clearfix">
                <div class="fixed-position col-lg-11">
                    <header class="panel-heading tab-bg-dark-navy-blue tab-right sitter_head">
                        <ul class="nav nav-tabs pull-left">
                        	<li> <span class="profile_name">
                            <?php echo $this->userInfo['firstname'] ?> <?php echo $this->userInfo['lastname'] ?> <?php echo $this->userInfo['firstname']!= '' ? '-' : '' ?> Password                        
                            </span>
                       		 </li>
                            <?php include_once('tabs.phtml'); ?>
                        </ul>
                    </header>
                    </div>
                    <div class="clearfix"></div>
                    <div class="panel-body list_margin" >
                        <div align="center"><br clear="all"> <b>Current Password:<?php echo $this->userInfo['password'] ?></b><form method="post" onsubmit="if (confirm('Are you sure you want to reset the password. Newly generated password will send to User.'))
                                   return true;
                               else
                                   return false;" name="resetpassword" class="cmxform form-horizontal tasi-form custom-form" action="<?php echo ADMIN_URL ?>sitters/password/user/<?php echo $this->userid ?>"></form>
                                <form method="post" onsubmit="if (confirm('Are you sure you want to reset the password. Newly generated password will send to User.'))
            return true;
        else
            return false;" name="resetpassword" class="basic" action="<?php echo ADMIN_URL ?>client/password/client/<?php echo $this->userid ?>">
                                    <input type="submit" class="btn btn-info"  name="passwordreset" value="Reset Password and Send to User" />
                                </form>
                        </div>
                     </div>
                </section>



            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<!--main content end-->
