<div class="inner-container">
				
				<!-- Main content – all content is within boxes. Feel free to add your boxes (see the examples on the bottom of this document) and your content within -->
				<div class="box box-100 altbox">
				  <div class="boxin">
				    <div class="header">
				      <h3><?php echo $this->userInfo['firstname'].' '.$this->userInfo['lastname']?> </h3>
				     
				      <ul>
				        <?php require_once('tabs.phtml');?>

			          </ul>
			        </div>
				    <div class="content">
				<div align="center"><br clear="all"> <b>Current Password:<?php echo $this->userInfo['password']?></b><form method="post" onsubmit="if(confirm('Are you sure you want to reset the password. Newly generated password will send to User.'))return true;else return false;" name="resetpassword" class="basic" action="<?php echo ADMIN_URL?>sitters/password/user/<?php echo $this->userid?>">
				<input type="submit" class="button altbutton"  name="passwordreset" value="Reset Password and Send to User" />
				</form>
</div>
			        </div>
			      </div>
			  </div>
				<br clear="all" />
			</div><!-- .inner-container -->
            



