    
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        <strong> Pay Sitters</strong>
                    </header>
                    <form name="searchform" method="post">

                        <?php
                        if ((isset($this->successMessage)) && (!empty($this->successMessage))) {
                            ?>
                            <div  >
                                <p style="color:#3c763d;margin-left:15px">
                                    <?php echo $this->successMessage; ?>
                                </p>
                            </div>
                        <?php } ?> 
                        
                        
                        <?php
                        if ((isset($this->sitterid)) && (!empty($this->sitterid))) {
                          $this->searchParams['sitter_user_id']=$this->sitterid;
                        } ?> 
                        
                        <div class="mar-top">
                            <div class="col-md-6">	
                                <select name="sitter_user_id" id="sitters" class='form-control'>
                                    
                                    <?php  //print_r($this->searchParams['sitter_user_id']);die;?>
                                    
                                      <option value="0" <?php if ($this->searchParams['sitter_user_id'] == '0') { ?> selected="selected" <?php } ?>>Sitters Owed For Jobs</option>

                                    <?php foreach ($this->unpaid_sitter_list as $sitter) { ?>
                                        <option value="<?php echo $sitter['sitter_user_id']; ?>"
                                        <?php if ($this->searchParams['sitter_user_id'] == $sitter['sitter_user_id']) { ?>
                                                    selected="selected" <?php } ?>><?php echo $sitter['firstname']." ".$sitter['lastname']." (".$sitter['status'].")"; ?></option>
                                            <?php } ?>      
                                </select>

                            </div>
                            <div class="col-md-6">
                                <input type="submit" name="filter" value="Filter" class="btn btn-danger" />

                            </div>
                        </div>
                    </form>                   
                   
                    <div class="panel-body  mar_paysitter">
                        <section id="flip-scroll">
                             <?php 
                            
                             if (!empty($this->searchParams['sitter_user_id']) && $this->searchParams['sitter_user_id'] != '0') { 
                                  //print_r($this->unpaid_sitters_details);die;
                                 ?>
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th>Select</th>
                                        <th>Job Id</th>
                                        <th>Sitter Name</th>
                                        <th>Date</th>
                                        <th class="text-right">Amount</th>
                                    <tr>                    

                                </thead>
                                <tbody>
                                    <?php foreach ($this->unpaid_sitters_details as $details) { ?>
                                        <tr>
                                            <?php 
                                            $rate = $details['rate'];
                                            if (empty($rate) || $rate == null) {
                                                $rate = $details['sitter_rate_pre'];
                                            } else {
                                                $rate = $details['rate'];}
                                                
                                                if(!empty($details['completed_date']) && $details['completed_date']!='0000-00-00 00:00:00') {
                                                	$end_date=$details['completed_date'];
                                                }else {
                                                	$end_date=$details['job_end_date'];
                                                } 
                                                if(strtotime($details['job_start_date'])>strtotime($end_date))
                                                	$end_date=$details['job_end_date'];
                                                
                                                if($details['immidiate_cancelled']=='yes' && strtotime($details['job_start_date']) > strtotime($details['cancelled_date']))
                                                	$total_hours = 3;
                                                else
                                                	$total_hours = round((strtotime(date('Y-m-d H:i:s',strtotime($end_date)))-strtotime(date('y-m-d H:i:s',strtotime($details['job_start_date']))))/(60*60),2);
                                           // $amount = $details['hr'] * $rate;
                                                $amount = $total_hours * $rate;
                                            ?>
                                            <td class="table_input_padding"><div class="btn-group" data-toggle="buttons">    
                                                <label class="btn btn-info chk  ">
                                                    <input type="checkbox"  name="job_id" value="<?php echo $details['job_id'] ?>" autocomplete="off" data="<?php echo $amount; ?>" data-id="<?php echo $details['sitter_user_id']; ?>"> 
                                                    <span class="glyphicon glyphicon-ok"></span>          
                                                </label>
                                            </div></td>

                                            <td><a href="<?php echo ADMIN_URL . 'client/events/user/' . $details['client_user_id'] . '/modify/' . $details['job_id'] ?>"><?php echo $details['job_id']; ?></a></td>
                                            <td><a href="<?php echo ADMIN_URL . 'sitters/profile/modify/' . $details['sitter_user_id'] ?>"><?php echo $details['firstname'] . " " . $details['lastname']; ?></a></td>
                                            <td>
                                                <?php echo date('m/d/Y', strtotime($end_date)); ?>
                                            </td>
                                            <td class="numeric"><?php  echo money_format('%.2n', $amount); ?></td>
                                        </tr>
                                    <?php } ?>


                                </tbody>
                            </table>
                            
                             <?php } ?>
                            <?php
                            echo $this->paginationControl($this->paginator, 'Sliding', 'client/pagination.phtml');
                            ?>
                        </section>
                    </div>

                    <form>
                        <div class="panel-body " style="margin-top: -40px;">
                            <div class='task-progress col-sm-12'>
                                <h1>Add Payment</h1>
                            </div>
                            <div class="clearfix"></div>
                            <div class="mar-top">
                                <div class="col-md-4">
                                    <strong> Job Ids</strong>
                                    <div style="display:none;color:#b70b0b;" id="job"></div>
                                </div>      
                                <div class="col-md-4" id="job_id"></div> 
                                <input type="hidden" id="j_ids">
                                <input type="hidden" id="userid" value="<?php echo $this->searchParams['sitter_user_id']; ?>">
                            </div>    
                            <div class="clearfix"></div>
                            
                            <div class="mar-top">
                                <div class="col-md-4">
                                    <strong> Amount</strong>
                                </div>      
                                <div class="col-md-4" id="amount"></div>  
                                <input type="hidden" id="amounts">
                                <div style="display:none" id="amt"></div>
                            </div>    
                            <div class="clearfix"></div>
                           
                            <div class="radios clearfix">
                                <div class="col-md-4">
                                    <label  class="label_radio">
                                    <input type="radio" id="type" name="type" value="check" checked  class="form-control">&nbsp;&nbsp;&nbsp;Check Number:
                                    </label>
                                    <div style="color:#b70b0b;display:none" id="c_n"></div>
                                </div>      
                                <div class="col-md-4">
                                    <input type="text" name="c_number" id="check_number" class="form-control">
                                </div>  
                            </div> 
     
                            <div class=" clearfix"></div>
                           
                            <div class="radios clearfix">
                                <div class="col-md-4">
                                     <label  class="label_radio">
                                    <input type="radio" name="type" value="wire" >&nbsp;&nbsp;&nbsp;Wire Number:
                                     </label>
                                    <div style="color:#b70b0b;display:none" id="w_n"></div>

                                </div>      

                                <div class="col-md-4">
                                    <input type="text" name="w_number" id="wire_number" style="display:none" class="form-control">
                                </div>  
                                <div class="clearfix"></div>
                              
                                <div class="col-md-6 mar-top">
                                    <input class="btn btn-info" type="button" value="Add Payment" onclick="add_payment()" class="button altbutton"/>
                                </div>   
                            </div> 
                        </div>
                    </form>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->

<script type="text/javascript">
    $(function () {

        //$(document).ready(function(){
        $("input[type=checkbox]").change(function () {
            $("#w_n").hide();
            $("#w_n").html("");
            $("#c_n").hide();
            $("#c_n").html("");
            $("#job").hide();
            $("#job").html("");

            var sum = 0;

            jQuery('input[name=job_id]:checked').map(function () {
                if (this.checked) {
                    sum += parseFloat($(this).attr('data'));
                } else {
                    sum -= parseFloat($(this).attr('data'));
                }
            });

            var ele = jQuery('input[name=job_id]:checked').map(function () {
                return this.value;
            }).get().join()

            $("#job_id").html(ele);
            $("#amount").html(sum);
            $("#j_ids").val(ele);
            $("#amounts").val(sum);
        });

        $("input[type='radio']").change(function () {

            var select = ($(this).val());
            if (select == 'check') {
                $("#w_n").hide();
                $("#w_n").html("");
                $("#wire_number").hide();
                $("#check_number").show();
            }
            if (select == 'wire') {

                $("#c_n").hide();
                $("#c_n").html("");
                $("#wire_number").show();
                $("#check_number").hide();
            }
        });
    });
</script>

<script>

    function add_payment() {
        var flag = false;
        var id = $("#j_ids").val();
        if (!id) {
            $("#job").show();
            $("#job").html("Please select job Id for the payment");
            var flag = false;
        }
        else {
            $("#job").hide();
            $("#job").html("");
            var flag = false;
        }

        var val = $('input:radio[name=type]:checked').val();
        if (val == 'check') {
            var p_type = $("#check_number").val();
            if (!p_type) {

                $("#c_n").show();
                $("#c_n").html("Please enter the check number");
                var flag = false;
            }


            else {


                $("#c_n").hide();
                $("#c_n").html("");
                var flag = true;
            }
        }
        else {
            $("#c_n").hide();
            $("#c_n").html("");
            var p_type = $("#wire_number").val();

            if (!p_type) {
                $("#w_n").show();
                $("#w_n").html("Please enter the wire number");
                var flag = false;
            }
            else if (p_type.match(/^\d+$/)) {
                $("#w_n").hide();
                $("#w_n").html("");
                var flag = true;
            }
            else {
                $("#w_n").show();
                $("#w_n").html("Please enter the valid wire number");
                var flag = false;
            }
        }

        var job_id = $("#j_ids").val();
        var id = $('select[name=sitter_user_id]').val();
        $("#userid").val(id);

        var sitter_id = $("#userid").val();
        var total_amount = $("#amounts").val();

        if (flag == true)
        {

            $.ajax({
                url: "<?php echo ADMIN_URL . 'sitters/updatesitterpaymentstatus' ?>",
                data: {job_id: job_id, sitter_id: sitter_id, type: val, number: p_type, amount: total_amount},
                dataType: 'json',
                type: 'post',<!--    async: false,-->
                success: function (data) {

                    if (data.status = "success")
                    {
                        window.location.href = "<?php echo ADMIN_URL . 'sitters/paysitter' ?>";
                        // alert(data.message);
                    }
                    else
                    {
//window.location.href = "<?php echo ADMIN_URL . 'sitters/paysitter' ?>";
                    }

                }
            });


        }
        //to call ajax here



    }
    
    $(":radio[name=type]").change(function() {
   
    $("label.r_on").removeClass("r_on"); //remove previous active class


        $(this).closest("label").addClass("r_on"); //add active to radio selected tr

      
})

</script>


