<?php
//echo '<pre>';

$errors = $this->userform->getMessages();
if (!empty($errors))
    $this->errorMessage = 'Error while updating information! Please verify your fields';
//print_r($errors);
$er = [];
foreach ($errors as $key => $err) {
    if (!isset($err[0])) {
        foreach ($err as $key2 => $r)
            if ($key2 != 'isEmpty')
                $er[$key . '[' . $key2 . ']'] = implode(', ', $r);
            else
                $er[$key] = implode(', ', $err);
    } else
        $er[$key] = implode(', ', $err);
}
//print_r($er);
$errors = $er;
?>
<style>
.preflist {
clear: both;
display: block;
list-style: none outside none;
margin: 0;
padding: 0;
}
</style>
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading tab-bg-dark-navy-blue tab-right sitter_head ">
                        <ul class="nav nav-tabs pull-right">
                            <?php include_once('tabs.phtml'); ?>
                        </ul>
                        <span class="hidden-sm wht-color profile_name">
                            <?php echo $this->userform->firstname->getValue() ?> <?php echo $this->userform->lastname->getValue() ?> <?php echo $this->userform->firstname->getValue() != '' ? '-' : '' ?> Profile                        </span>
                    </header>
                    <div class="panel-body">

                        <?php if ((int) $this->userInfo['profile_completed'] <= 0) { ?>
                            <div style="color:#a94442"><p><?php echo $this->globalMessages['SitterProfileNotUpdated'] ?></p></div>
                        <?php } ?>

                        <?php if ($this->successMessage != '') { ?>
                            <div class="smessage"><p><?php echo $this->successMessage; ?></p></div>
                        <?php } ?>

                        <?php if ($this->userform->username->getValue() != "") { ?>
                            <div class="alert alert-info fade in">


                                <strong>User Status:</strong><?php echo $this->statusArray[$this->userInfo['status']]; ?>
                                &nbsp;&nbsp;<strong>Joined Date:</strong><?php echo date(DATETIME_FORMAT, strtotime($this->userInfo['joining_date'])) ?>
                                &nbsp;&nbsp;<strong>Profile Last Modified:</strong>
                                <?php echo date(DATETIME_FORMAT, strtotime($this->userInfo['modified_date'])) ?>
                            </div>
                        <?php } ?>

                        <form class="cmxform form-horizontal tasi-form custom-form" id="userform" method="post" enctype="multipart/form-data" action="<?php echo $this->userform->getAction(); ?>" ><dl class="zend_form">

                                <!--                            <dl class="zend_form">-->

                                <section class="clearfix">
                                    <h4>Basic Information</h4>
                                    <div class="border-top m-bot20"></div>
                                    <div class="col-sm-6">
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">First Name</label>
                                            <div class="col-lg-9">
                                                <input name="firstname" type="text" class="form-control" id="some1" value="<?php echo $this->userform->firstname->getValue() ?>"/>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label class="control-label col-lg-3">Last Name</label>
                                            <div class="col-lg-9">
                                                <input name="lastname" type="text" class="form-control" id="some2" value="<?php echo $this->userform->lastname->getValue() ?>"/>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Mobile</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" name="phone" type="text"  id="phone" value="<?php echo $this->userform->phone->getValue() ?>"  />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Home Phone</label>
                                            <div class="col-lg-9">
                                                <input name="local_phone" type="text" class="form-control" id="local_phone" value="<?php echo $this->userform->local_phone->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Work Phone</label>
                                            <div class="col-lg-9">
                                                <input name="work_phone" type="text" class="form-control" id="work_phone" value="<?php echo $this->userform->work_phone->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Email</label>
                                            <div class="col-lg-9">
                                                <input name="username" type="text" class="form-control" id="username" value="<?php echo $this->userform->username->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Date of Birth</label>
                                            <div class="col-lg-9">
                                                <div data-date-viewmode="years" data-date-format="mm/dd/yyyy"   class="input-append date dpYears">
                                                    <input type="text" readonly size="16" class="form-control datep"  id="dob"  value="<?php echo $this->dob($this->userform->dob->getValue()) ?>" name="dob">
                                                    <span class="input-group-btn add-on">
                                                        <button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button>
                                                    </span>
                                                </div>                                        </div>
                                        </div>



                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">Street Address</label>
                                            <div class="col-lg-9">
                                                <input name="local[streat_address]" type="text" class="form-control" id="some10" value="<?php echo $this->userform->local->streat_address->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="cemail" class="control-label col-lg-3">City</label>
                                            <div class="col-lg-9">
                                                <input name="local[city]" type="text" class="form-control" id="some12" value="<?php echo $this->userform->local->city->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">State</label>
                                            <div class="col-lg-9">
                                                <select id="local_state" name="local[state]" class="form-control required">
                                                    <option value="">Select State</option>
                                                    <?php foreach ($this->userform->local->state->getMultiOptions() as $key => $option) { ?>
                                                        <option value="<?php echo $key ?>" <?php echo $this->userform->local->state->getValue() == $key || ($this->userform->local->state->getValue() == '' && $key == 3655) ? 'selected="seleceted"' : '' ?>><?php echo $option ?></option>
                                                    <?php } ?>

                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">ZIP Code</label>
                                            <div class="col-lg-9">
                                                <input name="local[zipcode]" type="text" class="form-control" id="some14" value="<?php echo $this->userform->local->zipcode->getValue() ?>" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label class="control-label col-lg-3">Upload Picture</label>
                                            <div class="col-lg-9">
                                                <input type="hidden" id="MAX_FILE_SIZE" value="8388608" name="MAX_FILE_SIZE">
                                                <input name="profile_image" type="file" id="profile_image" value="" />

                                            </div>
                                        </div>


                                        <div class="form-group" >
                                            <div class="col-lg-9">
                                                <a href="#" style="height:90px;width:100px !important"><?php if ($this->profile_thumb_image != '') { ?><span><img src="<?php echo SITE_URL . $this->profile_thumb_image ?>" /></span><?php } ?>
                                                </a>

                                            </div>
                                        </div>
                                    </div>
                                </section>

                                <section class="clearfix m-top20">
                                    <h4>Additional Information</h4>
                                    <div class="border-top m-bot20"></div>
                                    <div class="col-sm-12">

                                        <!--  <div class="form-group ">
                                            <div class="radios clearfix">
                                                <label class="col-lg-4">Have a car?</label>
                                                <label class="label_radio" for="radio-01">
                                                    <input id="radio-01"  <?php //echo $this->userform->have_car->getValue() == 'yes' ? 'checked="checked"' : '' ?>class="form-control required" type="radio" value="yes" name="have_car"> Yes  
                                                </label>
                                                <label class="label_radio" for="radio-02">
                                                    <input id="radio-02" <?php //echo $this->userform->have_car->getValue() == 'no' ? 'checked="checked"' : '' ?>  type="radio" value="no" name="have_car"> No                                              </label>
                                            </div>
                                        </div>-->
                                        <div class="form-group ">
                                            <div class="radios clearfix">
                                                <label class="col-lg-4">CPR Certification-Infant/Toddler?</label>
                                                <label class="label_radio" for="radio-03">
                                                    <input id="radio-03"  <?php echo $this->userform->cpr_holder->getValue() == 'yes' ? 'checked="checked"' : '' ?> class="form-control required" type="radio" value="yes" name="cpr_holder"> Yes

                                                </label>
                                                <label class="label_radio" for="radio-04">
                                                    <input id="radio-04" <?php echo $this->userform->cpr_holder->getValue() == 'no' ? 'checked="checked"' : '' ?> type="radio" value="no" name="cpr_holder"> No 
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group ">  
                                            <div class="radios clearfix">
                                                <label class="col-lg-4">CPR Certification- Adult?</label>
                                                <label class="label_radio" for="radio-05">
                                                    <input id="radio-05" <?php echo $this->userform->cpr_adult->getValue() == 'yes' ? 'checked="checked"' : '' ?> class="form-control required" type="radio" value="yes" name="cpr_adult"> Yes 
                                                </label>
                                                <label class="label_radio" for="radio-06">
                                                    <input id="radio-06"  <?php echo $this->userform->cpr_adult->getValue() == 'no' ? 'checked="checked"' : '' ?> type="radio" value="no" name="cpr_adult"> No 
                                                </label>
                                            </div> </div>
                                        <div class="form-group ">  
                                            <div class="radios clearfix">
                                                <label class="col-lg-4">First Aid Certification?</label>
                                                <label class="label_radio" for="radio-07">
                                                    <input id="radio-07" <?php echo $this->userform->first_aid_cert->getValue() == 'yes' ? 'checked="checked"' : '' ?> class="form-control required" type="radio" value="yes" name="first_aid_cert"> Yes      </label>
                                                <label class="label_radio" for="radio-08">
                                                    <input id="radio-08" <?php echo $this->userform->first_aid_cert->getValue() == 'no' ? 'checked="checked"' : '' ?> type="radio" value="no" name="first_aid_cert"> No 
                                                </label>
                                            </div>
                                        </div>
                                        <!--<div class="form-group ">
                                            <div class="radios clearfix">
                                                <label class="col-lg-4">Clean Driving Record?</label>
                                                <label class="label_radio" for="radio-09">
                                                    <input id="radio-09"  <?php //echo $this->userform->clean_drive_record->getValue() == 'yes' ? 'checked="checked"' : '' ?> class="form-control required" type="radio" value="yes" name="clean_drive_record"> Yes                                         </label>
                                                <label class="label_radio" for="radio-12">
                                                    <input id="radio-12"  <?php //echo $this->userform->clean_drive_record->getValue() == 'no' ? 'checked="checked"' : '' ?> type="radio" value="no" name="clean_drive_record"> No 
                                                </label>
                                            </div>
                                        </div>
                                          <div class="form-group ">
                                            <div class="radios clearfix">
                                                <label class="col-lg-4">Criminal Record?</label>
                                                <label class="label_radio" for="radio-10">
                                                    <input id="radio-10" <?php //echo $this->userform->criminal_record->getValue() == 'yes' ? 'checked="checked"' : '' ?> class="form-control required" type="radio" value="yes" name="criminal_record"> Yes                                         </label>
                                                <label class="label_radio" for="radio-11">
                                                    <input id="radio-11"  <?php //echo $this->userform->criminal_record->getValue() == 'no' ? 'checked="checked"' : '' ?> type="radio" value="no" name="criminal_record"> No 
                                                </label>
                                            </div>  </div>

                                        <div class="form-group ">
                                            <div class="radios clearfix">
                                                <label class="col-lg-4">Have child under 12?</label>
                                                <label class="label_radio" for="radio-13">
                                                    <input id="radio-13"  <?php //echo $this->userform->have_child->getValue() == 'yes' ? 'checked="checked"' : '' ?> class="form-control required" type="radio" value="yes" name="have_child"> Yes 
                                                </label>
                                                <label class="label_radio" for="radio-14">
                                                    <input id="radio-14"  <?php //echo $this->userform->have_child->getValue() == 'no' ? 'checked="checked"' : '' ?> type="radio" value="no" name="have_child"> No 
                                                </label>
                                            </div>
                                        </div>-->

                                    </div>
                                </section>




                                <section class="clearfix m-top20">
                                    <h4>Preferences</h4>
                                    <p>Unchecked boxes means that you would prefer not to receive jobs that fall within that particular criteria.</p>
                                    <div class="border-top m-bot20"></div>
                                    <div>



                                        <?php if (!empty($this->preferences)) { ?>
                                            <?php $this->preferences = array_chunk($this->preferences, 2); // print_r($this->preferences); ?>

                                            <?php foreach ($this->preferences as $k => $part) {
                                                ?>

                                                <?php foreach ($part as $group) { ?>
                                                    <div>
                                                        <ul class="preflist">
                                                            <li><strong><?php echo $group['label'] ?></strong></li>
                                                            <div class="border-top m-bot20"></div>

                                                            <?php
                                                            if (!empty($group['prefer']))
                                                                foreach ($group['prefer'] as $p) {
                                                                    ?>

                                                                    <li style="float:left;width:220px" >

                                                                        <div class="btn-group" data-toggle="buttons">    
                                                                            <label class="btn btn-info chk <?php echo in_array($p['prefer_id'], $this->sitterPreference) || @in_array($p['prefer_id'], $this->searchParams['prefer']) ? 'active' : '' ?> ">
                                                                                <input  <?php echo in_array($p['prefer_id'], $this->sitterPreference) || @in_array($p['prefer_id'], $this->searchParams['prefer']) ? 'checked="checked"' : '' ?> type="checkbox" name="prefer[]" value="<?php echo $p['prefer_id'] ?>" />
                                                                                <span class="glyphicon glyphicon-ok"></span>
                                                                            </label>
                                                                            <?php echo $p['prefer_name'] ?> 
                                                                        </div>

                                                                    </li>

                                                                <?php }
                                                            ?>                        
                                                        </ul>
                                                        <div class="clearfix"></div>
                                                    <?php } ?>
                                                </div>
                                            <?php } ?>

                                        <?php } ?>
                                    </div>
                                    </div>    


                                    <div class="">
                                        <h4 class="m-top20">Other</h4>
                                        <div class="border-top m-bot20"></div>
                                        <textarea name="otherpreference" class="form-control"><?php echo $this->userform->otherpreference->getValue() ?></textarea>                                    </div>

                                </section>         
                                <section class="clearfix m-top20">
                                    <h4>Additional Information</h4>
                                    <div class="border-top m-bot20"></div>
                                    <div class="col-sm-12">
                                        <section id="flip-scroll">
                                            <table class="table table-bordered table-striped table-condensed cf">
                                                <thead>
                                                    <tr>
                                                        <td>School</td>
                                                        <td>Start Date</td>
                                                        <td>End Date</td>
                                                        <td>Degree</td>
                                                    </tr>
                                                </thead>
                                                <tbody id="education_body">
                                                    <?php if (!empty($this->educations)) { ?>
                                                        <?php foreach ($this->educations as $edu) { ?>
                                                            <tr><!-- .first for first row of the table (only if there is thead) -->
                                                                <td>

                                                                    <input name="education[institution][]" type="text" class="form-control width-70" id="some15" value="<?php echo $edu['institution'] ?>" /></td>
                                                                <td>


                                                                    <div data-date-viewmode="years" data-date-format="dd/mm/yyyy" data-date="12-02-2012"  class="input-append date dpYears">
                                                                        <input type="text" readonly size="16" class="form-control datep"  name="education[start_date][]" id="some16" value="<?php echo strtotime($edu['start_date']) > 0 ? date(DATE_FORMAT, strtotime($edu['start_date'])) : '' ?>">
                                                                        <span class="input-group-btn add-on">
                                                                            <button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button>
                                                                        </span>
                                                                    </div>

                                                                </td>
                                                                <td>


                                                                    <div data-date-viewmode="years" data-date-format="dd/mm/yyyy" data-date="12-02-2012"  class="input-append date dpYears">
                                                                        <input type="text" readonly size="16" class="form-control datep"  name="education[end_date][]" id="some17" value="<?php echo strtotime($edu['end_date']) > 0 ? date(DATE_FORMAT, strtotime($edu['end_date'])) : '' ?>">
                                                                        <span class="input-group-btn add-on">
                                                                            <button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button>
                                                                        </span>
                                                                    </div>
                                                                </td>
                                                                <td><input name="education[degree][]" type="text" class="form-control width-70" id="some18" value="<?php echo $edu['degree'] ?>" /></td>
                                                                <!-- a.ico-comms for comment-like backgrounds -->
                                                            </tr>
                                                        <?php } ?>
                                                    <?php } else { ?>

                                                        <tr>
                                                            <td>

                                                                <input name="education[institution][]" type="text" class="form-control width-70" id="some15" value="" />

                                                            </td>
                                                            <td>


                                                                <div data-date-viewmode="years" data-date-format="dd/mm/yyyy" data-date="12-02-2012"  class="input-append date dpYears">
                                                                    <input type="text" readonly size="16" class="form-control datep"  name="education[start_date][]" id="some16" value="">
                                                                    <span class="input-group-btn add-on">
                                                                        <button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button>
                                                                    </span>
                                                                </div>

                                                            </td>
                                                            <td>


                                                                <div data-date-viewmode="years" data-date-format="dd/mm/yyyy" data-date="12-02-2012"  class="input-append date dpYears">
                                                                    <input type="text" readonly size="16" class="form-control datep"  name="education[end_date][]" id="some17" value="" >
                                                                    <span class="input-group-btn add-on">
                                                                        <button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button>
                                                                    </span>
                                                                </div>
                                                            </td>
                                                            <td><input name="education[degree][]" type="text" class="form-control width-70" id="some18" value=""/></td>
                                                            <!-- a.ico-comms for comment-like backgrounds -->
                                                        </tr>
                                                    <?php } ?>
                                                </tbody>
                                            </table>

                                        </section>

                                        <div class="clearfix">
                                            <a class="btn btn-primary pull-right" onclick="addEducation()"><i class="fa fa-plus-circle"></i> Add More</a>
                                        </div>

                                        <div class="">
                                            <h4 class="m-top20">Tell us about yourself (goals, interests, hobbies).</h4>
                                            <div class="border-top m-bot20"></div>
                                            <textarea class="form-control" name="about_me" id="about_me"><?php echo $this->userform->about_me->getValue() ?></textarea>
                                        </div>

                                        <div class="">
                                            <h4 class="m-top20">What traits or qualities do you possess that make you a good babysitter?</h4>
                                            <div class="border-top m-bot20"></div>
                                            <textarea class="form-control" name="traits" id="traits" ><?php echo $this->userform->traits->getValue() ?></textarea>
                                        </div>

                                        <div class="">
                                            <h4 class="m-top20">Summary of Childcare experience.</h4>
                                            <div class="border-top m-bot20"></div>
                                            <textarea class="form-control" name="exp_summary" id="exp_summary"><?php echo $this->userform->exp_summary->getValue() ?></textarea>
                                        </div>

                                        <section id="flip-scroll">
                                            <h4>Reference.</h4>
                                            <div class="border-top m-bot20"></div>
                                            <table class="table table-bordered table-striped table-condensed cf">
                                                <thead class="cf">
                                                    <tr>
                                                        <th>Name</th>
                                                        <th>Phone Number</th>
                                                        <th>Relationship</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="reference_body">
                                                    <?php if (!empty($this->reference)) { ?>
                                                        <?php foreach ($this->reference as $ref) { ?>

                                                            <tr><!-- .first for first row of the table (only if there is thead) -->
                                                                <td><input name="reference[refered_by][]" type="text" class="form-control width-70" id="some15" value="<?php echo $ref['refered_by'] ?>" /></td>
                                                                <td><input name="reference[phone][]" type="text" class="form-control width-70" id="some16" value="<?php echo $ref['phone'] ?>" /></td>
                                                                <td><input name="reference[relationship][]" type="text" class="form-control width-70" id="some16" value="<?php echo $ref['relationship'] ?>" /></td>
                                                                <!-- a.ico-comms for comment-like backgrounds -->
                                                            </tr>
                                                        <?php } ?>
                                                    <?php } else { ?>
                                                        <tr><!-- .first for first row of the table (only if there is thead) -->
                                                            <td><input name="reference[refered_by][]" type="text" class="form-control width-70" id="some15" value="" /></td>
                                                            <td><input  name="reference[phone][]" type="text" class="form-control width-70" id="some16" value="" /></td>
                                                            <td><input  name="reference[relationship][]" type="text" class="form-control width-70" id="some16" value="" /></td>
                                                            <!-- a.ico-comms for comment-like backgrounds -->
                                                        </tr>
                                                    <?php } ?>  
                                                </tbody>


                                            </table>
                                            <div class="clearfix">
                                                <a href="javascript:void(0)" onclick="addReference()" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> Add More</a>
                                            </div>
                                        </section>
                                                                                 <h4>Notes about Sitter</h4>
                                            
                              <div class="border-top m-bot20"></div>  
                                
                                 <div class="form-group col-lg-12">
                                     <textarea id="sitternotes" name="sitternotes" class="form-control"><?php echo $this->userform->sitternotes->getValue() ?></textarea>
                                </div>
                                        

                                        <div class="form-group clearfix">
                                            <div class="m-bot20 m-top20">

                                                <input class="btn btn-danger" type="submit" value="Update" />
                                                <input class="btn btn-default" type="button" onclick="history.back();" value="Cancel" />
                                            </div>
                                        </div>
                                    </div>
                                </section>
                        </form>
                        </dl>
                    </div>
                </section>
            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->
<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>

<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/additional-methods-new.min.js"></script>
<script type="text/javascript">
$(document).ready(function () {
    
    
    $.validator.addMethod("alpha", function(value, element) {
    return this.optional(element) || value == value.match(/^[a-zA-Z\s]+$/); });
    // validate signup form on keyup and submit

    var validator = $("#userform").validate({
        rules: {
            firstname: {
                required: true,
                    alpha:true,
            },
            middlename: {
                required: false
            },
            lastname: {
                required: true,
                    alpha:true,
            },
            username: {
                required: true,
                email: true
            },
            password: {
                required: true
            }, profile_image: {
                required: false,
                accept: "image/*"

            }, phone: {
                required: true
            },
            'local[streat_address]': {
                required: true
            },
            'local[zipcode]': {
                required: true
            },
            'local[city]': {
                required: true

            },
            'local[state]': {
                required: true

            }


        },
        messages: {
            firstname: {
                required: 'Please enter the First Name',
                alpha:'Please enter the valid First Name'
            },
            lastname: {
                required: 'Please enter the Last Name',
                alpha:'Please enter the valid Last Name'
            },
            username: {
                required: 'Value cannot be empty',
                email: "Your email address must be in the format of name@domain.com"

            },
            password: {
                required: 'Value cannot be empty'
            }, profile_image: {
                required: '',
                accept: 'Only jpeg/png/jpg/gif files are allowed'

            }, phone: {
                required: 'Please enter your phone number.'
            },
            'local[address_1]': {
                required: 'Please Enter your address'
            },
            'local[streat_address]': {
                required: 'Please enter your street address'
            },
            'local[zipcode]': {
                required: "Please enter your ZIP code."
            },
            'local[city]': {
                required: 'Please enter your city'

            }
        },
        // the errorPlacement has to take the table layout into account
        errorPlacement: function (error, element) {
            //alert(element.attr('type'));
            if (element.is(":radio")) {
                error.html('Please enter yes or no');
                error.appendTo(element.parent().parent());
            }
            else if (element.is(":checkbox"))
                error.appendTo(element.next());
            else {
                error.appendTo(element.parent());

            }
        },
        // specifying a submitHandler prevents the default submit, good for the demo
        submitHandler: function () {
            //$("#login").submit();
            document.getElementById('login').submit();
        },
        // set this class to error-labels to indicate valid fields
        success: function (label) {
        }
    });

<?php
if (!empty($errors)) {
    echo "validator.showErrors(" . json_encode($errors) . ");";
}
?>

    $('textarea').each(function (i, ele) {
        if ($(ele).val() == '') {
            $(ele).val('Please provide details.')
        }
    })
    $('textarea').blur(function (event) {
        if (this.value == '' || this.value == 'Please provide details.') {
            this.value = 'Please provide details.'
        }
    });
    $('textarea').focus(function (event) {
        if (this.value == '' || this.value == 'Please provide details.') {
            this.value = ''
        }
    });

});

function addReference() {
    var str = '<tr><td><input name="reference[refered_by][]" type="text" class="form-control width-70" id="some15" value="" /></td><td><input  name="reference[phone][]" type="text" class="form-control width-70" id="some16" value="" /></td><td><input  name="reference[relationship][]" type="text" class="form-control width-70" id="some16" value="" /></td></tr>';
    $("#reference_body").append(str);
}
function addEducation() {
    var str = ' ';
    ;
    var stsr = '<tr><td><input name="education[institution][]" type="text" class="form-control width-70" id="some15" value="" /></td><td><div data-date-viewmode="years" data-date-format="dd/mm/yyyy" data-date="12/02/2012"  class="input-append date dpYears"><input type="text" readonly size="16" class="form-control datep"  name="education[start_date][]" id="some16" value=""><span class="input-group-btn add-on"><button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button></span></div></td><td><div data-date-viewmode="years" data-date-format="dd/mm/yyyy"   class="input-append date dpYears"><input type="text" readonly size="16" class="form-control datep"  name="education[end_date][]" id="some17" value="" ><span class="input-group-btn add-on"><button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button></span></div></td><td><input name="education[degree][]" type="text" class="form-control width-70" id="some18" value=""/></td></tr>';


    var re = ' <tr>td><div data-date-viewmode="years" data-date-format="dd/mm/yyyy"  class="input-append date dpYears"><input type="text" readonly size="16" class="form-control datep"  name="education[start_date][]" id="some16" value=""><span class="input-group-btn add-on"><button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button></span></div> </td></tr>';


    $("#education_body").append(stsr);
    $('.dpYears').datepicker();


}
</script>
