<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                       Send message

                    </header>

                    <?php
                    if ((isset($this->successMsg)) && (!empty($this->successMsg))) {
                        ?>
                        <div  >
                            <p style="color:#3c763d;margin-left:15px">
                                <?php echo $this->successMsg; ?>
                            </p>
                        </div>
                    <?php } ?> 

                    <?php
                    if ((isset($this->errorMsg)) && (!empty($this->errorMsg))) {
                        ?>
                        <div  >
                            <p style="color:#a94442;margin-left:15px">
                                <?php echo $this->errorMsg; ?>
                            </p>
                        </div>
                    <?php } ?> 


                    <div class="panel-body">
                        <span>Simply send a message to  babysitter</span>
                        </br>   </br>

                        <div class=" form">
                            <form class="cmxform form-horizontal tasi-form" id="messageForm" method="post" >
                                <div class="form-group ">
                                    <label for="cname" class="control-label col-lg-2">Recipient's Email </label>
                                    <div class="col-lg-4">
                                       
                                        
<!--       <select multiple="multiple" class="multi-select " id="my_multi_select1" name="my_multi_select1[]">         -->
           
            <select name="my_multi_select3[]" class="multi-select"  multiple="multiple" id="my_multi_select3" >
           
            <?php foreach ($this->all_sitters as $sitter){ ?>                           
    
    <option value="<?php echo $sitter['userid']?>"><?php echo $sitter['firstname']." ".$sitter['lastname'];?></option>
            <?php } ?>     
    
    
                                        </select>
                                        
                                        
                                        
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-2">Message
                                    </label>
                                    <div class="col-lg-4">
                                        <textarea class="form-control" name="message" placeholder="type your message here" ></textarea>

                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <input type="submit" name="send" value="Send Message" class="btn btn-danger">

                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

<script src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>


<script type="text/javascript">
    $(document).ready(function () {
        
  
        var validator = $("#messageForm").validate({
            rules: {
                'my_multi_select3[]': {
                    required: true,
                    

                },
                
                  message: {
                    required: true,

                },

            },
            messages: {
                'my_multi_select3[]': {
                    required: "Please select the sitters u want to send email."
                   

                },
                message: {
                    required: "Please enter a message."
                    

                }

                
                

            }

            // specifying a submitHandler prevents the default submit, good for the demo

            // set this class to error-labels to indicate valid fields

        });






    });</script>
