
<div class="inner-container">
<!-- Main content – all content is within boxes. Feel free to add your boxes (see the examples on the bottom of this document) and your content within -->
<div class="box box-100 altbox">
    <div class="boxin">
        <div class="header">
            <h3>Sitters Payment History</h3>
	</div></br>
        <form name="searchform" method="post">
            <div style="margin-left:50px">
               <tr>
                   <th>
                       <div style="display: inline; margin: 0px 69px" align="center">
                          Start Date:<input placeholder="Start date" type="text"class="txt" name="payment_start_date" id="payment_start_date" size="10" value="<?php echo $this->searchParams['job_start_date']?>" />
                          End Date:<input placeholder="End date" type="text" class="txt" name="payment_end_date" id="payment_end_date" size="10" value="<?php echo $this->searchParams['job_end_date']?>" />
			</div>
                   </th>
                    <th>
                        <select name="userid">
                            <option value="0" <?php if($this->searchParams['userid'] == 0) { ?> selected="selected" <?php }?>>All Sitters</option>
                            <?php  foreach($this->sitters as $sitter) { ?>
                                <option value="<?php echo  $sitter['userid'] ;?>" <?php if($this->searchParams['userid'] == $sitter['userid']) {?> selected="selected" <?php }?>><?php echo  $sitter['name'];?></option>
                            <?php }?>      
                    
                        </select>
                    </th>
                    <th>
                        <input type="submit" name="filter" value="Filter" />
                    </th>
               </tr>
            </div>
				
	</form></br>
	<div class="content">
            <table border="1">
                <thead>
                    <tr>
                        <th>Payment Id</th>
                        <th>Job IDs</th>
                        <th>Sitter Name</th>
                        <th>Date </th>
                        <th>Amount $</th>
                        <th>Detail</th>
                     <tr>
		</thead>
                         <?php if(!empty($this->sitter_payment_history_details)){?>
                         <?php foreach($this->sitter_payment_history_details as $details){?>
                    <tr>
                        <td><?php echo $details['sitter_payment_details_id'];?></td>
                        <td><?php echo $details['job_ids'];?></td>
                        <td><?php echo $details['firstname']." ".$details['lastname'];?></td>
                        <td><?php echo $details['date_added'];?></td>
                        <td><?php echo $details['total_paid'];?></td>
                        <td><a onclick="get_details(<?php echo $details['sitter_payment_details_id']; ?>)">Details</a></td>
                    </tr>
	
                        <?php }?>	
                        <?php }else{?>
                    <tr>
                        <td colspan="6">No records found</td>
                    </tr>
                        <?php }?>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Total</td>
                    <td><?php echo $this->total_amount;?></td>
                    
            </table>

                <?php  echo $this->paginationControl ( $this->paginator, 'Sliding', 'client/pagination.phtml' );?>
	</div>
    </div>
</div></div>


<!-- .inner-container -->
<link type="text/css"
	href="<?php echo SITE_URL?>resources/css/redmond/jquery-ui-1.7.3.custom.css"
	rel="stylesheet" />
<script type="text/javascript"
	src="<?php echo SITE_URL?>resources/js/jquery-ui-1.7.3.custom.min.js"></script>
<script type="text/javascript"
	src="<?php echo SITE_URL?>resources/js/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript" 
        src="<?php echo SITE_URL?>resources/js/jquery-validator.js"></script>
<script type="text/javascript">
$(function(){
        $('#payment_start_date,#payment_end_date').datepicker({
	ampm: true,dateFormat:'mm-dd-yy',changeMonth: true,
	changeYear: true });
            });
</script>

<script type="text/javascript">
function  get_details(payment_id)
{
alert(payment_id);
}
</script>


		
<style type="text/css">
/* css for timepicker */
.ui-timepicker-div .ui-widget-header {
	margin-bottom: 8px;
}

.ui-timepicker-div dl {
	text-align: left;
}

.ui-timepicker-div dl dt {
	height: 25px;
}

.ui-timepicker-div dl dd {
	margin: -25px 0 10px 65px;
}

.ui-timepicker-div td {
	font-size: 90%;
}
</style>

