
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

         <div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                             Add Pricing
                          </header>
                          <div class="panel-body">
                              <div class=" form">
                                  <form class="cmxform form-horizontal tasi-form" id="form_login" method="post" action="<?php echo ADMIN_URL?>pricing/add">
                                      <div class="form-group ">
                                          <label for="child_count" class="control-label col-lg-2">Number of children </label>
                                          <div class="col-lg-4">
                                              <input class=" form-control" name="child_count" id="child_count"  />
                                          </div>
                                      </div>
                                      <div class="form-group ">
                                          <label for="client_rate" class="control-label col-lg-2">Client Rate
                                          </label>
                                          <div class="col-lg-4">
                                              <input class="form-control " id="client_rate"  name="client_rate"  />
                                          </div>
                                      </div>
                                     
                                      <div class="form-group ">
                                          <label for="sitter_rate" class="control-label col-lg-2">Sitter Rate</label>
                                          <div class="col-lg-4">
                                              <input class="form-control " id="sitter_rate" name="sitter_rate" ></input>
                                          </div>
                                      </div>
                                      <div class="form-group">
                                          <div class="col-lg-offset-2 col-lg-10">
                                              <button class="btn btn-danger" type="submit">Save</button>
                                          </div>
                                      </div>
                                  </form>
                              </div>

                          </div>
                      </section>
                  </div>
              </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

<script src="<?php echo SITE_URL?>resource/js/jquery-validator.js"></script>
<script type="text/javascript">
$(document).ready(function() {
	var validator = $("#form_login").validate({
		rules: {
			
			child_count: {
				required: true
				number:true
			},
			client_rate: {
				required: true,
                number:true
			},
                        
			sitter_rate: {
				required: true,
                number:true
			}
			
		},
		messages: {
			child_count: {
				required: "Enter the no of children."
				
			},
			client_rate: {
				required: "Enter the client rate."
			},
			sitter_rate: {
				required: "Enter the sitter rate."
			} 
			
		}
	});

});</script>