
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        <h3>test Profile</h3>
                    </header>
                    <div class="panel-body">

                       
                            
                            
                            
                            
                        <form class="cmxform form-horizontal tasi-form custom-form" id="userform" >
                            <dl class="zend_form">
                                <section class="clearfix">
                                    <h4>Basic Information</h4>
                                    <div class="border-top m-bot20"></div>
                                    <div class="col-sm-6">
                                        <div class="form-group ">
                                            <label for="cname" class="control-label col-lg-3">First Name</label>
                                            <div class="col-lg-9">
                                                <input name="firstname" type="text" class="form-control" id="firstname" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label class="control-label col-lg-3">Phone</label>
                                            <div class="col-lg-9">
                                                <input name="lastname" type="number" class="form-control" id="lastname" />
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <label for="curl" class="control-label col-lg-3">Email</label>
                                            <div class="col-lg-9">
                                                <input name="spouse_firstname" type="email" class="form-control" id="spouse_firstname"  />
                                            </div>
                                        </div>




                                    </div>
                                    
                                <div class="clearfix"></div>
                                
                                <div class="form-group clearfix">
                                    <div class="m-bot20 m-top20">
                    <input class="btn btn-danger" type="submit" value="Update" />
                    <input class="btn btn-default" type="reset" value="Back" onclick="history.back()"/>

                                    </div>
                                </div>


                            </dl>
                        </form>
                    </div>
                </section>
            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->
<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>

<script type="text/javascript">
$(document).ready(function() {
	// validate signup form on keyup and submit
	
	var validator = $("#userform").validate({
		rules: {			
			firstname: {
				required: true
			},
			lastname: {
				required: true
			},
			dob: {
				required: true
			},
			username: {
				required: true,
				email:true
			},
			password: {
				required: true
			},profile_image: {
				required: false
			
			},phone: {
				required: true,
                                number:true,
                                maxlength:11,
                                minlength:10
			},
			'local[address_1]': {
				required: false
			},
			'local[streat_address]': {
				required: true
			},
			'local[zipcode]': {
				required: true,
                                number:true
			},
			'local[city]': {
				required: true
				
			},
			'local[state]': {
				required: true
			
			},
			'billing[streat_address]': {
				required: function(){ return $('#billing-address_type').is(':checked')}
			},
			'billing[zipcode]': {
				required: function(){ return $('#billing-address_type').is(':checked')}
			},
			'billing[city]': {
				required: function(){ return $('#billing-address_type').is(':checked')}
                               
				
			},
			'billing[state]': {
				required: function(){ return $('#billing-address_type').is(':checked')}
			}
			
		},
		messages: {
			firstname: {
				required:'Please enter the First Name'
			},
			lastname: {
				required:'Please enter the Last Name'
			},
			dob: {
				required:'Please enter the Date of Birth'
			},
			username: {
				required:'This email is used for login/primary Email address',
				email: "Your email address must be in the format of name@domain"
   
			},
			profile_image: {
				required: ''
			
			},phone: {
				required: 'Please provide your phone number.'
			}
		},
		// the errorPlacement has to take the table layout into account
		errorPlacement: function(error, element) {
			//alert(element.attr('type'));
			if ( element.is(":radio") )
				error.appendTo( element.parent().next().next() );
			else if ( element.is(":checkbox") )
				error.appendTo ( element.next() );
			else{
				error.appendTo( element.parent());
				
			}
		},
		// specifying a submitHandler prevents the default submit, good for the demo
		submitHandler: function() {
			//$("#login").submit();
			document.getElementById('login').submit();
		},
		// set this class to error-labels to indicate valid fields
		success: function(label) {
			// set &nbsp; as text for IE
			label.html("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;").addClass("checked");
		}
	});
	
	<?php 
	
	if(!empty($errors)){
		echo "validator.showErrors(".json_encode($errors).");";
	}
	?>
	
	//$("#login").valid();
	

});

function changeState(th){
	$.ajax({
		url:'<?php echo SITE_URL?>misc/stateoptionsid',
		data:{country_id:th.value},
		success:function(data){$("#billing_state").html(data);}
		});
}
</script>
