<?php



$job_info=$this->job_information;
//print_r($job_info);die;


$in= Zend_Controller_Front::getInstance()->getRequest()->getQuery( 'msg' );
?>

<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        <b>Pay Booking charge</b>
                    </header>
                    <div class="panel-body">
                    
                    
                    <div class="alert alert-info fade in">
                        <p><strong>You are going to book for:</strong> <?php  echo $this->payment_info['days'];  ?>days</p>
                        <p><strong>Previous Credits Used:</strong> <?php  echo $this->payment_info['credits'];  ?></p>
                        <p> <strong>Payble Booking Amount:</strong> <?php  echo  $this->payment_info['amount']; ?>USD</p>
                   </div>
                    <?php
                                    if(!empty($this->paymentProfile) && isset($this->paymentProfile->client_payment_profile_id))
                                    {
                                    	$payid=$this->paymentProfile->client_payment_profile_id;
                                      ?>
                                        <div class="panel panel-info" >
                                            <div class="well">
                                                <div class="btn-group clearfix" data-toggle="buttons" style="float:left;">
                                                    <label class="btn btn-info chk active">
                                                        <input class="" id="saved_card" autocomplete="off" type="checkbox" title="Saved CC info For Next Time" value="1"  name="saved_card" checked />
                                                        <span class="glyphicon glyphicon-ok"></span>
                                                    </label>
                                                    </div>
                                                    <div class="mar-left" style="float:left; margin-top:6px;">
													<p><b>XXXX-XXXX-XXXX-<?php echo $this->paymentProfile->card_number;?></b></p>
                                                </div>
                                          		<div class="clearfix"></div>
                                            </div>
                                        </div>
                                    <?php
                                    }
                                    ?>
                                
                  <?php if((isset($in))&&(!empty($in))) {?>
                        <div class="emessage"><?php echo $in;  ?></div>
                  <?php }?>
                       
                     <?php 
require_once APPLICATION_PATH.'/../library/Hb/anet_php_sdk/AuthorizeNet.php'; // The SDK
$url = SITE_URL."authorizenet";

$api_login_id = AUTHORIZENET_LOGIN_ID;
$transaction_key = AUTHORIZENET_TRAN_KEY;
$md5_setting = AUTHORIZENET_MD5_SETTING; // Your MD5 Setting
$amount = $this->payment_info['amount'];
$fp_sequence = time();
//AuthorizeNetDPM::directPostDemo($url, $api_login_id, $transaction_key, $amount, $md5_setting);
//print_r($url);die;
echo  getCreditCardForm($amount, $fp_sequence, $url, $api_login_id, $transaction_key,$this->addresses,$this->userInfo,$this->job_information,$this->payment_info,$payid);
 
 
?>
   </div>                
                </section>
            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<script type="text/javascript" src="<?php echo SITE_URL?>resource/js/jquery-validator.js"></script>


<script type="text/javascript">
function changeState(th){
	$.ajax({
		url:'<?php echo SITE_URL_HTTPS?>misc/stateoptions',
		data:{country_id:th.value},
		success:function(data){$("#states").html(data);}
		});
}
</script>

<?php 
  function getCreditCardForm($amount, $fp_sequence, $relay_response_url, $api_login_id, $transaction_key,$address,$userInfo,$job_info,$payment_info,$payid)
    {
      
     
        $time = time();
        $fp = AuthorizeNetDPM::getFingerprint($api_login_id, $transaction_key, $amount, $fp_sequence, $time);
        $sim = new AuthorizeNetSIM_Form(
            array(
            'x_amount'        => $amount,
            'x_fp_sequence'   => $fp_sequence,
            'x_fp_hash'       => $fp,
            'x_fp_timestamp'  => $time,
            'x_relay_response'=> "TRUE",
            'x_test'		  => X_TEST,
            'x_relay_url'     => $relay_response_url,
            'x_login'         => $api_login_id,
            )
        );
        $hidden_fields = $sim->getHiddenFieldString();
        $post_url = SITE_URL.'client/chargebookingfee';//PAYMENT_URL;//(PAYMENT_TESTMODE ? AuthorizeNetDPM::SANDBOX_URL : self::LIVE_URL);
        
        $hbSettings = new Hb_Settings();
        $states = $hbSettings->getStates();
        $countries = $hbSettings->getCountries();
        //$states = 
        
        if($payid!=null&& $payid!='')
        {
        	//$hidden='';
        	//$checked='';
	$hidden='hidden';
    	$checked='checked';
        }
        else
        {
        	$hidden='hidden';
        	$checked='checked';
        }
        
        $form = '
        <style>
        fieldset {
            overflow: auto;
            border: 0;
            margin: 0;
            padding: 0; }

        fieldset div {
            float: left; }

        fieldset.centered div {
            text-align: center; }

        label {
            color: #183b55;
            display: block;
            margin-bottom: 5px; }

        label img {
            display: block;
            margin-bottom: 5px; }

        input.text {
            border: 1px solid #bfbab4;
            margin: 0 4px 8px 0;
            padding: 6px;
            color: #1e1e1e;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: inset 0px 5px 5px #eee;
            -moz-box-shadow: inset 0px 5px 5px #eee;
            box-shadow: inset 0px 5px 5px #eee; }
            


        </style>
        <form method="post" id="card_info_form" action="'.$post_url.'" class="cmxform form-horizontal tasi-form">
                '.$hidden_fields.'
                <input type="hidden" name="x_userid" value="'.$userInfo['userid'].'" />
                <input type="hidden" name="x_invoice_num" value="'.time().'" />
                    
<input type="hidden" name="x_transactiontype" value="booking">  


<input type="hidden" name="x_start_date" value="'.$job_info['start_date'].'" >
<input type="hidden" name="x_end_date" value="'.$job_info['end_date'].'" >
<input type="hidden" name="x_notes" value="'.$job_info['notes'].'" >
  
   <input type="hidden" name="x_children" value="'. htmlentities(serialize($job_info['children'])).'" > 
       



<input type="hidden" name="x_address_id" value="'.$job_info['address_id'].'" >
<input type="hidden" name="x_prefer" value="'. htmlentities(serialize($job_info['prefer'])).'" >

<input type="hidden" name="x_add_credit" value="'.$payment_info['add_credit'].'" >





<div style="margin-top:2%">

     <legend>Credit Card Information</legend>
    </div>

            <div style="width:100%">
        <fieldset>
               

                <div style="width:30%;">
                    <label>Credit Card Number</label>
                    <input placeholder="Credit Card Number" type="text" required="required" pattern="[0-9]*" title="This fields accepts only digits"  title="Please enter the valid digits" pattern=".{16,}*"   title="Enter valid card number" class="form-control" size="15" name="x_card_num" value="'.($prefill ? '6011000000000012' : '').'"></input>
                </div>
                 


                <div style="width:10%;margin-left:8%">
                    <label>Exp.</label>
                    <input type="text" class="form-control" required="required" placeholder="MM/YY" pattern="[0-9]{2}/[0-9]{2}" title="Expiration date should be in the format of MM/YY" class="text" size="4" name="x_exp_date" value="'.($prefill ? '04/17' : '').'"></input>
                </div>
                 
                <div style="width:15%;margin-left:8%">
                    <label>CCV</label>
                    <input placeholder="CCV" maxlength="4" type="text" required="required" pattern="[0-9]{3,4}" title="This field should be atleast 3 digits" class="form-control" size="4" name="x_card_code" value="'.($prefill ? '782' : '').'"></input>
			</div>			
                        
 <div style="width:15%">
   <label>&nbsp;&nbsp;&nbsp;</label>


                    <a class="ico" href="https://www.dcporder.com/ccv.htm" onclick="window.open(\'https://www.dcporder.com/ccv.htm\' ,\'Creditcard\',\'menubar=0,resizable=false,width=600,height=400\');return false;" target="blank" title="click here to know what is ccv " alt="?">
                    <img src="'.SITE_URL.'resources/img/question_icon.gif"  alt="what is ccv?"/>
                    </a>
                    </div>
                </div>
                
            
</fieldset>

 <fieldset>
              <div class="btn-group clearfix mar-top '.$hidden.'" data-toggle="buttons">
                     <label class="btn btn-info chk ">
                         <input class="" id="save_card" autocomplete="off" type="checkbox" title="Saved CC info For Next Time" value="1"  name="save_card" '.$checked.'/>
                         <span class="glyphicon glyphicon-ok"></span>
                     </label>

                </div>
                  <div class="btn-group clearfix mar-top '.$hidden.'" data-toggle="buttons">
                      <label>Save CC Info</label>
                </div>

        </fieldset>
            



<div style="margin-top:2%">
<!-- <strong>Billing Information</strong> -->
		 <legend>Billing Information</legend>
            <fieldset>
                <div style="width:30%;">
                    <label>First Name</label>
                    <input required="required" placeholder="First name" pattern="[a-zA-Z\s.,]+" type="text" class="form-control" size="15" name="x_first_name" value="'.$userInfo['firstname'].'"></input>
                </div>
                <div style="width:30%;margin-left:8%" >
                    <label>Last Name</label>
                    <input type="text" required="required" placeholder="Last name" pattern="[a-zA-Z\s.,]+" class="form-control" size="14" name="x_last_name" value="'.$userInfo['lastname'].'"></input>
                </div>
            </fieldset>
            <fieldset>
                <div style="width:30%" >
                    <label>Address</label>
                    <input type="text" required="required" placeholder="Address" class="form-control" size="26" name="x_address" value="'.$address['streat_address'].'"></input>
                </div>
                    <div style="width:30%;margin-left:8%" >
                    <label>City</label>
                    <input type="text" required="required" placeholder="City" pattern="[a-zA-Z\s.,]+" title="This field should be accept only alphabets" class="form-control" size="15" name="x_city" value="'.$address['city'].'"></input>
                </div>
            </fieldset>
            <fieldset>
                <div style="width:30%">
                    <label>State</label>';
                    $t='';
                    $form_state='<select required="required" name="x_state" id="states" class="form-control">';
                    
                    foreach($states as $state){
						$t.='<option '.($address['state']==$state['zone_id']?'selected="selected"' : '').' value="'.$state['code'].'">'.$state['name'].'</option>';
					}
                    
                    $form_state.=$t.'</select>';
                    $form.=$form_state.'
                </div>
                <div style="width:30%;margin-left:8%" >
                    <label>Zip Code</label>
                    <input type="text" required="required" placeholder="Zipcode" class="form-control"  name="x_zip" value="'.$address['zipcode'].'"></input>
                </div>
                 </fieldset>
 <fieldset>

                <div style="width:30%">
                    <label>Country</label>';
                    $t='';
                    $form_country='<select class="form-control" required="required" name="x_country" onchange="changeState(this);">';
                    
                    foreach($countries as $country){
						$t.='<option '.($address['country']==$country['country_id']?'selected="selected"' : '').' value="'.$country['iso_code_2'].'">'.$country['name'].'</option>';
					}
                    
                    $form_country.=$t.'</select>';
                    $form.=$form_country.'
                    </div>
            </fieldset><br>
            
</div>
            <input type="submit" class="btn btn-success" value="Book Job" >
            <input type="button" class="btn btn-info" value="Cancel" onclick="window.location=\''.SITE_URL.'client/events\'" >
            <input type="button" class="btn btn-default" value="Back " onclick="history.back();" >
            <br/><br clear="all"/>
        </form>
        
  <!-- form2 -->
                    <form method="post" id="form2"  action="'.$post_url.'" class="cmxform form-horizontal tasi-form hidden">
                '.$hidden_fields.'
                <input type="hidden" name="x_userid" value="'.$userInfo['userid'].'" />
                <input type="hidden" name="x_invoice_num" value="'.time().'" />
                    
<input type="hidden" name="x_transactiontype" value="booking">  


<input type="hidden" name="x_start_date" value="'.$job_info['start_date'].'" >
<input type="hidden" name="x_end_date" value="'.$job_info['end_date'].'" >
<input type="hidden" name="x_notes" value="'.$job_info['notes'].'" >
  
   <input type="hidden" name="x_children" value="'. htmlentities(serialize($job_info['children'])).'" > 
       
<input type="hidden" name="x_clientpayment" value="'.$payid.'" />


<input type="hidden" name="x_address_id" value="'.$job_info['address_id'].'" >
<input type="hidden" name="x_prefer" value="'. htmlentities(serialize($job_info['prefer'])).'" >

<input type="hidden" name="x_add_credit" value="'.$payment_info['add_credit'].'" >





<div style="margin-top:2%">

            
</div>
            <input type="submit" class="btn btn-success" value="Book Job" >
            <input type="button" class="btn btn-info" value="Cancel" onclick="window.location=\''.SITE_URL.'client/events\'" >
            <input type="button" class="btn btn-default" value="Back " onclick="history.back();" >
            <br/><br clear="all"/>
        </form>';
        return $form;
    }

?>
<script>
$(document).ready(function() {
	if( $('#saved_card').length>0 && $('#saved_card').is(":checked")){
		 $('#card_info_form').addClass('hidden');
	        $('#form2').removeClass('hidden');
	}
});
$('#saved_card').change(function() {
	if($(this).is(":checked")) {
        $('#card_info_form').addClass('hidden');
        $('#form2').removeClass('hidden');
    }
    else{
    	$('#card_info_form').removeClass('hidden');
        $('#form2').addClass('hidden');

    }
});

</script>


