
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                       <span class="table_heading">Billing  Summary</span>
                        
                                <a href="<?php echo SITE_URL ?>client/buycredits" class="label label-success pull-right">Buy Credits</a>

                    </header>

                    <div class="panel-body">
                        <section id="flip-scroll">
                            <?php if($this->searchParams['success']=='payment'){?>
						
				<div style="color:#3c763d"><p><?php echo $this->successMessage;?></p></div>
						<?php }?>
                            <?php
                                if(!empty($this->subscriptions)){?>
                            
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                       <th>Transaction ID</th>
                                        <th>Date</th>
                                        <th>Description</th>
                                        <th class="text-right">Amount</th>
                                        <th>Purchased Credits</th>
                                        <th>Remaining Credits</th>
                                        <th>Expires</th>                     
                                    </tr>

                                </thead>

<tbody>	
	
	<?php foreach($this->subscriptions as $sub){
		//if($sub['transaction_id']=='No Payment')continue; //commented for displaying free credits
		?>
	<tr>
		<td><?php echo ($sub['transaction_id']=='No Payment')?  'Free' : $sub['transaction_id']?> </td>
		<td><?php echo date(DATE_FORMAT,strtotime($sub['last_modified_date']))?> </td>
		<td><?php echo $sub['notes']?></td>
		<td class="numeric"><?php echo ($sub['transaction_id']!='No Payment')? money_format('%.2n',$sub['price']):'No charge'?></td>
		<td><?php echo $sub['total_credits']?></td>
		<td><?php echo $sub['slots']?></td>
		<td><?php echo date(DATETIME_FORMAT,strtotime($sub['end_date']))?></td>
		
		
		
	</tr>
	<?php }?>
	</tbody>

                                
                            </table>
<?php
echo $this->paginationControl($this->paginator, 'Sliding', 'client/pagination.phtml');
?>
                            <?php }else {?>
<div >No credits purchased yet. To create a new job buy credits here <a href="<?php echo SITE_URL ?>client/buycredits" class="button altbutton">Click here</a></div>
<?php }?>

                        </section>
                    </div>
                </section>
            </div>
        </div>

        <!-- page end-->
    </section>
</section>