
<li>
	<a  <?php echo  $this->actionName=='profile'?'class="active"' :''?> href="<?php echo SITE_URL?>client/profile/">Contact Information</a></li>
<li>
<a  <?php echo  $this->actionName=='children'?'class="active"' :''?> href="<?php echo SITE_URL?>client/children/">Children</a></li>
<li><a  <?php echo  $this->actionName=='password'?'class="active"' :''?> href="<?php echo SITE_URL?>client/password">Password</a></li>
