
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <div class="fixed-position col-lg-12">
                        <header class="panel-heading clearfix">
                            Transaction History
                            <?php
                            $key = Zend_Controller_Front::getInstance()->getRequest()->getParam('key');
                            $odr = Zend_Controller_Front::getInstance()->getRequest()->getParam('odr');
                            if (empty($this->searchParams['transaction_type'])) {
                                $this->searchParams['transaction_type'] = "";
                            }
                            if (empty($this->searchParams['start_date'])) {
                                $this->searchParams['start_date'] = "";
                            }
                            if (empty($this->searchParams['end_date'])) {
                                $this->searchParams['end_date'] = "";
                            }
                            ?>
                            <div style="float:right" class="col-lg-6">

                                <div class="col-lg-3">
                                    <a class="btn btn-primary clearfix" style="float:right"  href="<?php echo ADMIN_URL . 'reports/createpdf/type/' . $this->searchParams['transaction_type'] . '/start_date/' . $this->searchParams['start_date'] . '/end_date/' . $this->searchParams['end_date'] . '/key/' . $key . '/odr/' . $odr ?>" > Generate pdf</a> 
                                </div>
                                <div class="col-lg-3">
                                    <input class="btn btn-primary" type="button" style="float:right" value="Print" onclick="printpage()">  
                                </div>
                            </div>

                        </header>
                        <form name="searchform" method="post" class="clearfix">
                            <div>
                                </br>
                                <div class="col-md-3">	
                                    <div data-date-viewmode="years" data-date-format="mm/dd/yyyy"   class="input-group date default-date-picker clearfix">
                                        <input type="text" id="start_date" name="start_date" class="form-control datep" value="<?php echo $this->searchParams['start_date']; ?>" size="16" readonly="" placeholder="Start Date">
                                        <span class="input-group-btn" style="width: auto">
                                            <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                        </span>
                                    </div>

                                </div>
                                <div class="col-md-3">
                                    <div data-date-viewmode="years" data-date-format="mm-dd-yyyy"   class="input-group date default-date-picker clearfix">
                                        <input type="text" id="end_date" name="end_date" class="form-control datep" value="<?php echo $this->searchParams['end_date']; ?>" size="16" readonly="" placeholder="End Date">
                                        <span class="input-group-btn" style="width: auto">
                                            <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                        </span>
                                    </div>

                                </div>
                                <div class="col-md-2">	
                                    <select name="transaction_type" class="form-control">
                                        <option value="all"<?php if ($this->searchParams['transaction_type'] == "all") { ?>
                                                    selected="selected" <?php } ?>>All Transaction</option>                           

                                        <option value="Cr."<?php if ($this->searchParams['transaction_type'] == "Cr.") { ?>
                                                    selected="selected" <?php } ?>>Credit</option>

                                        <option value="Dr."<?php if ($this->searchParams['transaction_type'] == "Dr.") { ?>
                                                    selected="selected" <?php } ?>>Debit</option>
                                    </select>
                                </div>
                                <div class="col-md-2">
                                    <input type="submit" name="filter" value="Filter" class="btn btn-danger" />
                                </div>
                            </div>
                        </form>     

                    </div>
                    </br>   
                    <div class="panel-body" style="margin-top: 135px">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf content" id="b_transaction">
                                <thead class="cf">
                                    <tr>
                                        <th class="text-right"><a href="<?php echo $this->url(array('key' => 'amount', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'amount' ? 'desc' : 'asc')) ?>">Amount</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'transaction_type', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'transaction_type' ? 'desc' : 'asc')) ?>">Transaction Type</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'date_added', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'date_added' ? 'desc' : 'asc')) ?>">Date</a></th>
                                        <th>Client Name/Sitter Name</th>
                                        <th>Job Id </th>
                                    <tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->transactions as $details) { ?>
                                        <tr>
                                            <td class="numeric"><?php echo money_format('%.2n', $details['amount']);
                                    ?> </td>



                                            <?php
                                            if ($details['transaction_type'] == 'Cr.') {
                                                $type = 'Credit';
                                                $var = 'client';
                                            } else {
                                                $var = 'sitters';
                                                $type = 'Debit';
                                            }
                                            ?>
                                            <td><?php echo $type ?></td>
                                            <td><?php echo date('m/d/Y', strtotime($details['date_added'])) ?></td>
                                            <td><a href="<?php echo ADMIN_URL . $var . '/profile/modify/' . $details['userid'] ?>"><?php echo ucwords($details['firstname'] . " " . $details['lastname']) ?></a></td>
                                            <td><a href="<?php echo ADMIN_URL . 'client/events/user/' . $details['userid'] . '/modify/' . $details['job_id'] ?>"><?php echo $details['job_id'] ?></a></td>
                                        </tr><?php } ?>
                                </tbody>
                            </table>
                            <div style="display:none">
                                <table style="border: 1px solid gray; border-collapse: collapse; font-size:14px" id="billing_transactions" >
                                    <thead >
                                        <tr>
                                            <th style="padding:5px; border: 1px solid gray; border-collapse: collapse;">Amount</th>
                                            <th style="padding:5px; border: 1px solid gray; border-collapse: collapse;">Credit/Debit</th>
                                            <th style="padding:5px; border: 1px solid gray; border-collapse: collapse;">Date</th>
                                            <th style="padding:5px; border: 1px solid gray; border-collapse: collapse;">Client Name/Sitter Name</th>
                                            <th style="padding:5px; border: 1px solid gray; border-collapse: collapse;">Job Id </th>
                                        <tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->alltransaction as $details) { ?>
                                            <tr>
                                                <td style="padding:3px;border: 1px solid gray; border-collapse: collapse;"><?php echo $details['amount'] ?> </td>
                                                <td style="padding:3px;border: 1px solid gray; border-collapse: collapse;"><?php echo $details['transaction_type'] ?></td>
                                                <td style="padding:3px;border: 1px solid gray; border-collapse: collapse;"><?php echo date('m/d/Y', strtotime($details['date_added'])) ?></td>
                                                <td style="padding:3px;border: 1px solid gray; border-collapse: collapse;"><?php echo ucwords($details['firstname'] . " " . $details['lastname']) ?></td>
                                                <td style="padding:3px;border: 1px solid gray; border-collapse: collapse;"><?php echo $details['job_id'] ?></td>
                                            </tr><?php } ?>
                                    </tbody>
                                </table>
                            </div>

                            <?php if ($this->searchParams['transaction_type'] == "all" || $this->searchParams['transaction_type'] == "") { ?>
                                <b> Total Credit :<?php echo money_format('%.2n',$this->transactions_credit); ?></b>
                                &nbsp;&nbsp;&nbsp;
                                <b> Total Debit  :<?php echo money_format('%.2n',$this->transactions_debit); ?></b>
                                &nbsp;&nbsp;&nbsp;
                                <b> Balance  : <?php echo money_format('%.2n',$this->transactions_amt); ?></b>                     
                            <?php } ?>
                    </div>

                    <?php if ($this->searchParams['transaction_type'] == "Cr.") { ?>
                        <b> Total Credit :<?php echo $this->transactions_credit; ?></b>
                    <?php } ?>
                    <?php if ($this->searchParams['transaction_type'] == "Dr.") { ?>
                        <b> Total Debit  :<?php echo $this->transactions_debit; ?></b>
                    <?php } ?>

                    <?php
                    echo $this->paginationControl($this->paginator, 'Sliding', 'client/pagination.phtml');
                    ?>
                </section>
            </div>
        </div>
    </section>
</div>
</div>
<!-- page end-->
</section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->
<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/jquery.PrintArea.js"></script>
<script type="text/javascript" src="<?php echo SITE_URL ?>resource/js/core.js"></script>

<script>

function printpage()
{
    var divToPrint = document.getElementById('billing_transactions');
    var htmlToPrint = '' +
            '<style type="text/css">' +
            'table th, table td {' +
            'border:1px solid #000;' +
            'padding;0.5em;' +
            '}' +
            '</style>';
    htmlToPrint += divToPrint.outerHTML;
    newWin = window.open("");
    newWin.document.write(htmlToPrint);
    newWin.print();
    newWin.close();
}

function create_pdf()
{

    $.ajax({url: "<?php echo ADMIN_URL . 'reports/createpdf/' ?>",
        data: {rate: '7'}, success: function (data) {
        }
    });
}
</script>