<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
    <head>
	
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="content-style-type" content="text/css" />
        <meta http-equiv="content-script-type" content="text/javascript" />
        
        <title>Hamptons Babysitters</title>
        
        <link rel="stylesheet" type="text/css" href="<?php echo SITE_URL?>resources/css/black.css" media="screen, projection, tv" />
      	
		<script type="text/javascript" src="<?php echo SITE_URL?>resources/js/jquery.min.js"></script>
		<!-- Adding support for transparent PNGs in IE6: -->
		<!--[if lte IE 6]>
			<script type="text/javascript" src="js/ddpng.js"></script>
			<script type="text/javascript">
				DD_belatedPNG.fix('#nav #h-wrap .h-ico');
				DD_belatedPNG.fix('.ico img');
				DD_belatedPNG.fix('.msg p');
				DD_belatedPNG.fix('table.calendar thead th.month a img');
				DD_belatedPNG.fix('table.calendar tbody img');
			</script>
		<![endif]-->
		<script type="text/javascript">
			$(document).ready(function() {
			    // Search input text handling on focus
					var $searchq = $("#search-q").attr("value");
				    $('#search-q.text').css('color', '#999');
					$('#search-q').focus(function(){
						if ( $(this).attr('value') == $searchq) {
							$(this).css('color', '#555');
							$(this).attr('value', '');
						}
					});
					$('#search-q').blur(function(){
						if ( $(this).attr('value') == '' ) {
							$(this).attr('value', $searchq);
							$(this).css('color', '#999');
						}
					});
				// Switch categories
					$('#h-wrap').hover(function(){
							$(this).toggleClass('active');
							$("#h-wrap ul").css('display', 'block');
						}, function(){
							$(this).toggleClass('active');
							$("#h-wrap ul").css('display', 'none');
					});
				// Handling with tables (adding first and last classes for borders and adding alternate bgs)
					$('tbody tr:even').addClass('even');
					$('table.grid tbody tr:last-child').addClass('last');
					$('tr th:first-child, tr td:first-child').addClass('first');
					$('tr th:last-child, tr td:last-child').addClass('last');
					$('form.fields fieldset:last-child').addClass('last');
				// Handling with lists (alternate bgs)
					$('ul.simple li:even').addClass('even');
				// Handling with grid views (adding first and last classes for borders and adding alternate bgs)
					$('.grid .line:even').addClass('even');
					$('.grid .line:first-child').addClass('firstline');
					$('.grid .line:last-child').addClass('lastline');
				// Tabs switching
					$('#box1 .content#box1-grid').hide(); // hide content related to inactive tab by default
					$('#box1 .header ul a').click(function(){
						$('#box1 .header ul a').removeClass('active');
						$(this).addClass('active'); // make clicked tab active
						$('#box1 .content').hide(); // hide all content
						$('#box1').find('#' + $(this).attr('rel')).show(); // and show content related to clicked tab
						return false;
					});
			});
		</script>
		
    </head>
    <body>	
		<div id="container">
		  <div id="header">
		    <div id="logo"><img src="<?php echo SITE_URL?>resources/img/txt.gif" alt="" width="1" height="12" /><img src="<?php echo SITE_URL?>resources/img/logo.jpg" width="360" height="125" alt="Hamptons Babysitters" /></div>
             </div>
		  <div id="nav">
             <ul>
               <li><a <?php echo $this->searchParams['controller']=='index' ? 'class="sel"' : ''?> href="<?php echo ADMIN_URL?>">Home</a></li>
               <li><a <?php echo $this->searchParams['controller']=='jobs' ? 'class="sel"' : ''?> href="<?php echo ADMIN_URL?>jobs/view/status/new/">Jobs</a></li>
               <li><a <?php echo $this->searchParams['controller']=='client' ? 'class="sel"' : ''?> href="<?php echo ADMIN_URL?>client/" >Clients</a></li>
               <li><a <?php echo $this->searchParams['controller']=='sitters' ? 'class="sel"' : ''?>href="<?php echo ADMIN_URL?>sitters/">Babysitters</a></li>
               <li><a <?php echo $this->searchParams['controller']=='settings' ? 'class="sel"' : ''?>href="<?php echo ADMIN_URL?>settings/">Settings</a></li>
               <li><a <?php echo $this->searchParams['controller']=='logout' ? 'class="sel"' : ''?>href="<?php echo ADMIN_URL?>logout/">Logout</a></li>
             </ul>
          </div>
          
          <?php echo $this->layout()->content; ?>
          
  <div id="footer"></div>
		</div><!-- #container -->
		
    </body>
</html>
