
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th><a href="<?php echo $this->url(array('key' => 'job_id', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'job_id' ? 'desc' : 'asc')) ?>">Job Number</a></th>
                                        <th style="text-align:center;">Alert Source: J/C/S/A</th>
                                        <th style="text-align:center;">Job Status: O/S/A/C/Cl </th>
                                        <th><a href="<?php echo $this->url(array('key' => 'client_name', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'client_name' ? 'desc' : 'asc')) ?>">Client Name</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'sitter_name', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'sitter_name' ? 'desc' : 'asc')) ?>">Sitter Name</a></th>
										<th>Alert Issue<p></p></th>
                                        <th style="text-align:center;">Resolved</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                      
                                <?php if (!empty($this->jobs)) {
                                    ?>
                                        <?php foreach ($this->jobs as $job) { ?>
										 <form id="resolvealert">
                                        <tr>
                                            <th><?php if($job['job_id']) { ?><a href="<?php echo ADMIN_URL . 'client/events/user/' . $job['client_user_id'] . '/modify/' . $job['job_id'] ?>"><?php echo $job['job_id']; ?></a><?php }else { echo "-";} ?></th>
                                            <td style="text-align:center;"> <?php echo $job['alert_source']; ?></td>
                                            <td style="text-align:center;"><?php if($job['job_status']) {echo $job['job_status'];}else{echo "-"; } ?></td>

                                            <td><?php  if($job['client_user_id']) { if($job['client_status']!="deleted"){?><a href="<?php echo ADMIN_URL . 'client/profile/modify/',$job['client_user_id'] ?>"> <?php echo $job['firstname']." ".$job['lastname']; ?></a><?php } else{?> <a class="deleted_client"><?php echo $job['firstname']." ".$job['lastname']; ?></a> <?php } }else { echo "-";} ?></td>

                                            <td><?php if($job['sitter_user_id']!='' && !in_array($job['alert_issue'],array('Client Dispute','Payment Problem')) ){?><a href="<?php echo ADMIN_URL . 'sitters/profile/modify/',$job['sitter_user_id']; ?>"> <?php echo $job['sitter_firstname']." ".$job['sitter_lastname']; ?></a><?php } else{ echo 'Unassigned'; }?></td>
                                            <td> <?php echo $job['modification'];?></td>
                                        	<td style="text-align:center;" class="table_input_padding">
                                        	<div data-toggle="buttons" class="btn-group">    
                                                <label class="btn btn-info chk">
                                                    <input data-toggle="button" type="checkbox" id="<?php echo "c".$job['log_id'];?>" data-id="<?php echo $job['log_id'] ?>"/>
                                                    <span class="glyphicon glyphicon-ok"></span>          
                                                </label>
                                            </div>
                                        	<!--  <input type="checkbox" id="<?php //echo "c".$job['log_id'];?>" onclick="ischecked(<?php //echo $job['log_id']?>)"/>-->
                                        	</td>
                                        </tr>
                                            <?php } ?>	
                                            </form>
                                    <?php } ?>       
                                </tbody>
                            </table>
                            <?php
                            echo $this->paginationControl($this->paginator, 'Sliding', 'client/pagination.phtml');
                            ?>
                        </section>
                    </div>
                </section>
            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->

<div class="modal fade" tabindex="-1" role="dialog" id="dclient">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     <h4 class="modal-title">Notice</h4>
      </div>
      <div class="modal-body">
        <div>This client profile has been deleted.</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

<script>
$(document).ready(function(){
	$('.deleted_client').click(function(){
		$('#dclient').modal('show');
		});
});

$('input[type="checkbox"]').change( function() {
	$(this).parent('label').addClass('active');
	 var id = $(this).attr('data-id');
	 if($("#c"+id).is(':checked'))
	 {
	  	var r=confirm('Are you sure?');
			if(r==true)
			{
				resolve(id);
				$(this).attr('checked', false); 
				$(this).parent('label').removeClass('active'); 
			}
	}
})  ;                     

                            
  function ischecked(id)
  {
		if($("#c"+id).is(':checked'))
		{
			var r=confirm('Are you sure?');
			
			if(r==true)
			{
				resolve(id);
			}
			else
			{
				$("#c"+id).attr('checked', false); 
			}
			
		}
  }

  function resolve(logs_id) {

        $.ajax({url: "<?php echo ADMIN_URL . 'jobs/markresolved/' ?>",
        	type: 'post',
            data: {log_id: logs_id}, success: function (data) {
            	window.location.reload();
            	//$("#c"+logs_id).closest('tr').remove();  
            }
        });
    }
</script>
