
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        Billable  Jobs
                    </header>

                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th><a href="<?php echo $this->url(array('key' => 'job_id', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'job_id' ? 'desc' : 'asc')) ?>">Job Id</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'job_start_date', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'job_start_date' ? 'desc' : 'asc')) ?>">Start Date/Time</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'job_end_date', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'job_end_date' ? 'desc' : 'asc')) ?>">End Date/Time</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'client_name', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'client_name' ? 'desc' : 'asc')) ?>">Client Name</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'sitter_name', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'sitter_name' ? 'desc' : 'asc')) ?>">Sitter Name</a></th>
                                        <th>Babysitting Fee</th>
                                       	<th>Charge Client</th>
                                        <th>Sitter Paid</th>
                                    </tr>

                                </thead>
                                <?php foreach ($this->billablejobs as $job) {?>
                                    <tr>
                                        <td class="numeric"><a href="<?php echo ADMIN_URL . 'client/events/user/' . $job['userid'] . '/modify/' . $job['job_id'] ?>"><?php echo $job['job_id']; ?></a></td>
                                         <td><?php echo date(DATETIME_FORMAT, strtotime($job['job_start_date'])) ?></td>
                                            <td><?php echo date(DATETIME_FORMAT, strtotime($job['job_end_date'])) ?></td>
                                        <td><a href="<?php echo ADMIN_URL . 'client/profile/modify/' . $job['userid'] ?>"><?php echo $job['client_first_name'] . " ", $job['client_last_name']; ?></a></td>
                                        <td><a href="<?php echo ADMIN_URL . 'sitters/profile/modify/' . $job['sitterid'] ?>"><?php echo $job['sitter_first_name'] . " ", $job['sitter_last_name']; ?></a></td>
                                        <?php
                                       if($job['total_received']==0 ||$job['total_received']==null)
                                            	{	
	                                            	if (($job['client_updated_rate'] == "") || ($job['client_updated_rate'] == null)) {
	                                            		$rate = $job['client_rate'];
	                                            	} else {
	                                            		$rate = $job['client_updated_rate'];
	                                            	}
	                                            	
	                                            	if($job['completed_date']!='0000-00-00 00:00:00' && $job['completed_date']!=null)
	                                            	{
	                                            		$end_date=$job['completed_date'];
	                                            	}
	                                            	else 
	                                            	{
	                                            		$end_date = $job['job_end_date'];
	                                            	}
	                                            	
	                                            	if (strtotime($end_date) < strtotime($job['job_start_date'])) {
	                                            		$end_date = $job['job_end_date'];
	                                            	}
	                                            	
	                                            	if($job['immidiate_cancelled']=='yes' && strtotime($job['job_start_date']) > strtotime($job['cancelled_date']))
	                                            		$total_hours = 3;
	                                            	else 
	                                            		$total_hours = round((strtotime(date('Y-m-d H:i:s',strtotime($end_date)))-strtotime(date('y-m-d H:i:s',strtotime($job['job_start_date']))))/(60*60),2);
	                           
	                                            	$job['total_received'] = $total_hours*$rate;
                                            	}
                                            	
                                            	if($job['client_payment_status']=='unpaid')
                                            	{
                                            		$client_paid = 'Outstand';
                                            		$btn_class=" btn-danger";
                                            	}
                                            	else 
                                            	{
                                            		$client_paid = 'Charged';
                                            		$btn_class=" btn-success";
                                            	}
                                            	if($job['sitter_payment_status']=='unpaid')
                                            	{
                                            		$sitter_paid = 'Owed';
                                            		$btn_class1=" btn-danger";
                                            	}
                                            	else
                                            	{
                                            		$sitter_paid = 'Paid';
                                            		$btn_class1=" btn-success";
                                            	}
                                            	?>
                                            	<td class="numeric" ><?php echo "$".$job['total_received'];?></td>
                                            	<td class="table_input_padding"><input type="submit" class="btn<?php echo $btn_class;?>" value="<?php echo $client_paid;?>" onclick="window.location = '<?php echo ADMIN_URL . 'client/events/user/' . $job['userid'] . '/modify/' . $job['job_id'] ?>'"  /></td>
                                            	<td class="table_input_padding"><input type="submit" class="btn<?php echo $btn_class1;?>" value="<?php echo $sitter_paid;?>" <?php if($sitter_paid=='Owed'){?>onclick="paysitter(<?php echo $job['sitterid']?>);" <?php }?> /></td>
                                            	
                                    </tr><?php } ?>
                                </tbody>
                            </table>
<?php
echo $this->paginationControl($this->paginator, 'Sliding', 'client/pagination.phtml');
?>
                        </section>
                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->

<script>

    function reloadPage()
    {
        location.reload();
    }

    function paysitter(id)
    {
    	var form= '<form method="POST" action="<?php echo ADMIN_URL.'sitters/paysitter' ?>"><input type="hidden" name="sitter_id" value="'+id+'"/></form>';
    	$(form).appendTo('body').submit().remove();
    }

</script>