
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    
                     <div class="fixed-position col-lg-12">
                    <header class="panel-heading clearfix">
                       Special Jobs
                        
                    </header>

                    <form name="searchform" method="post" class="clearfix">
                        <div>
                            </br>
                            <div class="col-md-2">	
                                <input placeholder="Job Number" type="text" class="form-control width-60" name="job_id"  value="<?php echo $this->searchParams['job_id'] ?>" />  
                            </div>
                            <div class="col-md-2">
                                <input placeholder="Client Name" type="text" class="form-control width-60" name="client" size="15"  value="<?php echo $this->searchParams['client'] ?>"/>
                            </div>
                            <div class="col-md-2">
                                <input placeholder="Sitter Name" type="text" class="form-control width-60" name="sitter" size="15"  value="<?php echo $this->searchParams['sitter'] ?>"/>
                            </div>
                            <div class="col-md-3">
                                <div data-date-viewmode="years" data-date-format="mm-dd-yyyy"   class="input-group btn-block date default-date-picker clearfix">
                                    <input type="text" readonly  size="16"  value="<?php echo $this->searchParams['job_start_date'] ?>"  class="form-control datep" name="job_start_date" id="job_start_date" placeholder="Start Date">
                                    <span class="input-group-btn" style="width: auto">
                                        <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                    </span>  
                                </div>

                            </div>

                            <div class="col-md-3">	
                                <div data-date-viewmode="years" data-date-format="mm-dd-yyyy"   class="input-group btn-block date default-date-picker clearfix">
                                    <input type="text" readonly  size="16" class="form-control datep"  value="<?php echo $this->searchParams['job_end_date'] ?>" name="job_end_date" id="job_end_date" placeholder="End Date" >
                                    <span class="input-group-btn" style="width: auto">
                                        <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                    </span> 
                                </div>
                            </div> </div>
                            <div class="col-md-12 mar-top">
                                <input type="submit" name="filter" value="Filter" class="btn btn-danger" />
                            </div>
                    </form>  
                    </div>
                    
                    <div class="panel-body list_margin" >
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th><a href="<?php echo $this->url(array('key' => 'j.job_id', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'j.job_id' ? 'desc' : 'asc')) ?>">Job Number</a></th>
                                        <?php if (!in_array($this->searchParams['status'], array('pending', 'confirmed', 'completed', 'cancelled'))) { ?>
                                        <!--  <th><a href="<?php echo $this->url(array('key' => 'j.jobs_posted_date', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'j.jobs_posted_date' ? 'desc' : 'asc')) ?>">Rec'd Date/Time</a></th>-->
                                        <?php } ?>
                                        <th><a href="<?php echo $this->url(array('key' => 'job_start_date', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'job_start_date' ? 'desc' : 'asc')) ?>">Start Date/Time</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'job_end_date', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'job_end_date' ? 'desc' : 'asc')) ?>">End Date/Time</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'client_name', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'client_name' ? 'desc' : 'asc')) ?>">Client Name</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'sitter_name', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'sitter_name' ? 'desc' : 'asc')) ?>">Sitter Name</a></th>
                                       <?php if (in_array($this->searchParams['status'], array('completed', 'closed'))) { ?>
                                        <th>Babysitting Fee</th>
                                        <th>Charge Client</th>
                                        <th>Sitter Paid?</th>
                                        <?php }else{ ?>
                                        <th>Cancelled Date & Time</th>
                                        <th><a href="<?php echo $this->url(array('key' => 'is_special', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'is_special' ? 'desc' : 'asc')) ?>">Special Status</a></th>
                                        <th>Active Alerts</th>
                                        <?php } ?>
                                        
                                    </tr>
<!--                                <form name="searchform" method="post" >-->
                                    </thead>
                                    <tbody>
<!--                                        <tr>
                                            <td><input placeholder="Job Number" type="text" class="form-control width-60" name="job_id"  value="<?php echo $this->searchParams['job_id'] ?>" /></td>
                                            <td colspan="<?php //if (!in_array($this->searchParams['status'], array('pending', 'confirmed', 'completed', 'cancelled'))) { ?>3<?php
                                            ////} else {
                                            //    echo '2';
                                           // }
                                            ?>">
                                                <div style="display:inline;margin:0px 69px" align="center">
                                                    <div data-date-viewmode="years" data-date-format="mm-dd-yyyy"   class="input-group date default-date-picker clearfix">
                                                        <input type="text" readonly  size="16"  value="<?php echo $this->searchParams['job_start_date'] ?>"  class="form-control datep" name="job_start_date" id="job_start_date">
                                                        <span class="input-group-btn" style="width: auto">
                                                            <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                                        </span>  
                                                    </div>
                                                    between 
                                                    <div data-date-viewmode="years" data-date-format="mm-dd-yyyy"   class="input-group date default-date-picker clearfix">
                                                        <input type="text" readonly  size="16" class="form-control datep"  value="<?php echo $this->searchParams['job_end_date'] ?>" name="job_end_date" id="job_end_date">
                                                        <span class="input-group-btn" style="width: auto">
                                                            <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                                        </span> 
                                                    </div>
                                                </div>
                                            </td>
                                            <td><input placeholder="Client Name" type="text" class="form-control" name="client" size="15"  value="<?php //echo $this->searchParams['client'] ?>"/></td>
                                            <td></td>
                                            <?php //if (in_array($this->searchParams['status'], array('closed'))) { ?>
                                                <td><input type="submit" name="filter" value="Filter" class="btn btn-danger"/></td>
                                            <?php //} ?>
                                            <?php //if (in_array($this->searchParams['status'], array('confirmed', 'cancelled'))) { ?>
                                                <td></td>
                                                <td><input type="submit" name="filter" value="Filter" class="btn btn-danger"/></td>
                                            <?php //} ?>
                                            <?php //if (in_array($this->searchParams['status'], array('completed'))) { ?>
                                                <td></td> <td></td>  <td></td> 
                                                <td><input type="submit" name="filter" value="Filter" class="btn btn-danger"/></td>
                                            <?php //} ?>
                                            <?php //if (in_array($this->searchParams['status'], array('new', 'pending', 'cancelled'))) { ?>
                                                <td></td>  <td><input type="submit" name="filter" value="Filter" class="btn btn-danger" /></td>
                                            <?php //} ?>
                                        </tr>-->
                                        
                                        
                                        
                                        
<!--                                    <input type="submit" value="filter" style="display:none" class="btn btn-danger"/>
                                </form>-->
                                <?php
                                if (!empty($this->jobs)) {
                                    ?>
                                    <?php foreach ($this->jobs as $job) { ?>
                                        <tr>
                                            <td><a href="<?php echo ADMIN_URL . 'client/events/user/' . $job['client_user_id'] . '/modify/' . $job['job_id'] ?>"><?php echo str_pad($job['job_id'], 4, 0, STR_PAD_LEFT); ?></a></td>
                                            <td><?php echo date(DATETIME_FORMAT, strtotime($job['job_start_date'])) ?></td>
                                            <td><?php echo date(DATETIME_FORMAT, strtotime($job['job_end_date'])) ?></td>
                                            <td> <a href="<?php echo ADMIN_URL . 'client/profile/modify/' . $job['client_user_id'] ?>"><?php echo ucwords($job['firstname'] . ' ' . $job['lastname']) ?></a></td>
                                            <?php if (in_array($this->searchParams['status'], array('scheduled','active', 'completed', 'cancelled'))) { ?>
                                                <td> <a href="<?php echo ADMIN_URL . 'sitters/profile/modify/' . $job['sitter_user_id'] ?>"> <?php echo $job['sitter_firstname'] . ' ' . $job['sitter_lastname'] ?></a></td>
                                            <?php } 
                                            else{ ?>
                                               <td> <a href="<?php echo ADMIN_URL . 'sitters/profile/modify/' . $job['sitter_user_id'] ?>"> <?php echo $job['sitter_firstname'] . ' ' . $job['sitter_lastname'] ?></a></td>
                                            <?php }
                                            if(!in_array($this->searchParams['status'], array('completed', 'closed')))
                                            { if($job['job_status']=='cancelled'){ ?>
                                              <td>  <?php echo date(DATETIME_FORMAT, strtotime($job['cancelled_date'])); ?></td>
                                              <?php	
                                              }else{ ?>  
                                               <td>  <?php echo "NA"; ?></td>
                                              <?php
                                              }
                                            ?>
                                            <?php if ($job['is_special']==1 || $job['is_special']=='1') { ?>
                                                <td ><?php echo "S";?></td>
                                            <?php }else{ ?><td ><?php echo "NA";?></td><?php } 
                                           if ($job['alerts']>0) { ?>
                                             <td ><?php echo "A";?></td>
                                              <?php }else{ ?><td ><?php echo "NA";?></td><?php } 
                                            }
                                            else {
                                            	if($job['total_received']==0 ||$job['total_received']==null)
                                            	{	
	                                            	if (($job['client_updated_rate'] == "") || ($job['client_updated_rate'] == null)) {
	                                            		$rate = $job['client_rate'];
	                                            	} else {
	                                            		$rate = $job['client_updated_rate'];
	                                            	}
	                                            	
	                                            	if($job['completed_date']!='0000-00-00 00:00:00' && $job['completed_date']!=null)
	                                            	{
	                                            		$end_date=$job['completed_date'];
	                                            	}
	                                            	else 
	                                            	{
	                                            		$end_date = $job['job_end_date'];
	                                            	}
	                                            	
	                                            	if($job['immidiate_cancelled']=='yes' && strtotime($job['job_start_date']) > strtotime($job['cancelled_date']))
	                                            		$total_hours = 3;
	                                            	else 
	                                            		$total_hours = round((strtotime(date('Y-m-d H:i:s',strtotime($end_date)))-strtotime(date('y-m-d H:i:s',strtotime($job['job_start_date']))))/(60*60),2);
	                           
	                                            	$job['total_received'] = $total_hours*$rate;
                                            	}
                                            	
                                            	if($job['client_payment_status']=='unpaid')
                                            	{
                                            		$client_paid = 'Outstand';
                                            		$btn_class=" btn-danger";
                                            	}
                                            	else 
                                            	{
                                            		$client_paid = 'Charged';
                                            		$btn_class=" btn-success";
                                            	}
                                            	if($job['sitter_payment_status']=='unpaid')
                                            	{
                                            		$sitter_paid = 'Owed';
                                            		$btn_class1=" btn-danger";
                                            	}
                                            	else
                                            	{
                                            		$sitter_paid = 'Paid';
                                            		$btn_class1=" btn-success";
                                            	}
                                            	?>
                                            	<td ><?php echo "$".$job['total_received'];?></td>
                                            	<td ><input type="submit" class="btn<?php echo $btn_class;?>" value="<?php echo $client_paid;?>" onclick="window.location = '<?php echo ADMIN_URL . 'client/events/user/' . $job['client_user_id'] . '/modify/' . $job['job_id'] ?>'"  /></td>
                                            	<td ><input type="submit" class="btn<?php echo $btn_class1;?>" value="<?php echo $sitter_paid;?>" <?php if($sitter_paid=='Owed'){?>onclick="paysitter(<?php echo $job['sitter_user_id']?>);" <?php }?> /></td>
                                            	<?php
                                            }
                                            ?>
                                        </tr>
                                    <?php } ?>	
<?php } ?>       

                                </tbody>
                            </table>


                            <?php
                            echo $this->paginationControl($this->paginator, 'Sliding', 'client/pagination.phtml');
                            ?>
                        </section>
                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->


<script>
    function saveRate(th) {
        $.ajax({url: "<?php echo ADMIN_URL . 'client/events/' ?>",
            data: {rate: th.value, saverate: 'rate', job_id: $(th).attr('rel')}, success: function (data) {
            }
        });
    }

    function paysitter(id)
    {
    	var form= '<form method="POST" action="<?php echo ADMIN_URL.'sitters/paysitter' ?>"><input type="hidden" name="sitter_id" value="'+id+'"/></form>';
    	$(form).appendTo('body').submit().remove();
    }
</script>