<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel clearfix">
                    <div class="fixed-navtab">
                        <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
                            <ul class="nav nav-tabs pull-right">
                                <?php include_once('scheduledtabs.phtml'); ?>
                            </ul>
                        </header>


                        <form name="searchform" method="post" class="clearfix">
                            <div>
                                </br>
                                <div class="col-md-2">	
                                    <input placeholder="Job Number" type="text" class="form-control width-60" name="job_id"  value="<?php echo $this->searchParams['job_id'] ?>" />  
                                </div>
                                <div class="col-md-3">
                                    <input placeholder="Client Name" type="text" class="form-control width-60" name="client" size="15"  value="<?php echo $this->searchParams['client'] ?>"/>
                                </div>
                                <div class="col-md-2">
                                    <div data-date-viewmode="years" data-date-format="mm-dd-yyyy"   class="input-group date default-date-picker clearfix">
                                        <input type="text" readonly  size="16"  value="<?php echo $this->searchParams['job_start_date'] ?>"  class="form-control datep" name="job_start_date" id="job_start_date" placeholder="Start Date">
                                        <span class="input-group-btn" style="width: auto">
                                            <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                        </span>  
                                    </div>

                                </div>

                                <div class="col-md-2">	
                                    <div data-date-viewmode="years" data-date-format="mm-dd-yyyy"   class="input-group date default-date-picker clearfix">
                                        <input type="text" readonly  size="16" class="form-control datep"  value="<?php echo $this->searchParams['job_end_date'] ?>" name="job_end_date" id="job_end_date" placeholder="End Date" >
                                        <span class="input-group-btn" style="width: auto">
                                            <button type="button" class="btn btn-danger date-set"><i class="fa fa-calendar"></i></button>
                                        </span> 
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <input type="submit" name="filter" value="Filter" class="btn btn-danger" />
                                </div>
                            </div>
                        </form>
                    </div>
                    </br>
                    </br></br> </br></br>
                    </br>
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th><a href="<?php echo $this->url(array('key' => 'j.job_id', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'j.job_id' ? 'desc' : 'asc')) ?>">Job Number</a></th>
                                        <?php if (!in_array($this->searchParams['status'], array('pending', 'confirmed', 'completed', 'cancelled'))) { ?>
                                            <th><a href="<?php echo $this->url(array('key' => 'j.jobs_posted_date', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'j.jobs_posted_date' ? 'desc' : 'asc')) ?>">Rec'd Date/Time</a></th>
                                        <?php } ?>
                                        <th><a href="<?php echo $this->url(array('key' => 'jm.job_start_date', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'job_start_date' ? 'desc' : 'asc')) ?>">Start Date/Time</a></th>
                                        <th><a href="<?php echo $this->url(array('key' => 'job_end_date', 'odr' => $this->searchParams['odr'] == 'asc' && $this->searchParams['key'] == 'job_end_date' ? 'desc' : 'asc')) ?>">End Date/Time</a></th>
                                        <th>Client</th>
                                        <th>Child</th>
                                        <th class="text-right">Sitter's Rate</th>
                                        <th>Assign</th>
                                    </tr>

                                </thead>
                                <tbody>

                                    <?php if (!empty($this->jobs)) {
                                        ?>
                                        <?php foreach ($this->jobs as $job) { ?>
                                            <tr>
                                                <td><a href="<?php echo ADMIN_URL . 'client/events/user/' . $job['client_user_id'] . '/modify/' . $job['job_id'] ?>"><?php echo str_pad($job['job_id'], 4, 0, STR_PAD_LEFT); ?></a></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['jobs_posted_date'])) ?></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_start_date'])) ?></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_end_date'])) ?></td>
                                                <td> <a href="<?php echo ADMIN_URL . 'client/profile/modify/' . $job['client_user_id'] ?>"><?php echo ucwords($job['firstname'] . ' ' . $job['lastname']) ?></a></td>
                                                <?php
                                                if (!empty($job['actual_child_count'])) {
                                                    $children = $job['actual_child_count'];
                                                } else {
                                                    $children = $job['child_count'];
                                                }
                                                ?>
                                                <td> <?php echo $children; ?></td>

                                                <?php
                                                //$job['rate'] = number_format((float) $job['rate'], 2, '.', '');
                                                   $rate=number_format((float)$job['rate'], 2, '.', ''); 

                                                 $timediff = $this->timediff($job['job_start_date']); 

                                                ?>
                                                <td class="numeric">

                                                    <?php
                                                    if (in_array($job['job_status'], array('new', 'pending')) && !$timediff) {
                                                        ?>
                                                        <span style="line-height: 33px; margin-right: 5px;">$</span> <input onkeyup="saveRate(this);" rel="<?php echo $job['job_id'] ?>" type="text" name="rate[<?php echo $job['job_id'] ?>]" class="form-control" style="width: 65px; float: right" value="<?php echo $rate ?>" disabled="" />


                                                    <?php } else { ?>
                                                        <span style="line-height: 33px; margin-right: 5px;">$</span><input onkeyup="saveRate(this);" rel="<?php echo $job['job_id'] ?>" type="text" name="rate[<?php echo $job['job_id'] ?>]" class="form-control" style="width: 75px; float: right" value="<?php echo $job['rate'] ?>" />

                                                    <?php } ?>                                            
                                                </td>
                                                <td class="text-center"> <input type="submit" class="btn btn-info" value="Assign" onclick="window.location = '<?php echo ADMIN_URL . 'client/assign/user/' . $job['client_user_id'] . '/modify/' . $job['job_id'] ?>'"  /></td>
                                            </tr>
                                        <?php } ?>	
                                    <?php } ?>       
                                </tbody>
                            </table>
                            <?php
                            echo $this->paginationControl($this->paginator, 'Sliding', 'client/pagination.phtml');
                            ?>
                        </section>
                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->
<script>
    function saveRate(th) {
        $.ajax({url: "<?php echo ADMIN_URL . 'client/events/' ?>",
            data: {rate: th.value, saverate: 'rate', job_id: $(th).attr('rel')}, success: function (data) {
            }
        });
    }

</script>