
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        Open Jobs
                        <a href="<?php echo SITE_URL ?>sitters/jobs/view/pending" class="label label-success pull-right">View all New Jobs</a>
                    </header>
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th>Job No.</th>
                                        <th>Start Date/Time</th>
                                        <td>End Date/Time</td>
                                        <td>Children</td>
                                        <td class="text-right">Rate</td>


                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($this->pendingJobs['rows'])) { ?>

                                        <?php foreach ($this->pendingJobs['rows'] as $job) { ?>


                                            <tr>
                                                <td><a href="<?php echo SITE_URL . 'sitters/preview/job/' . $job['job_id'] ?>"><?php echo $this->jobnumber($job['job_id']) ?></a></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_start_date'])) ?></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_end_date'])) ?></td>
                                                <?php
                                                if (!empty($job['actual_child_count'])) {
                                                    $children = $job['actual_child_count'];
                                                } else {
                                                    $children = $job['child_count'];
                                                }
                                                ?>

                <!--                                                <td> <?php //echo count($job['children'])  ?></td>-->
                                                <td> <?php echo $children; ?></td>


                                                <td class="numeric"> <?php echo money_format('%.2n', ($job['rate'])?$job['rate']:$job['sitter_rate_pre']) ?></td>

                                            </tr>

                                        <?php } ?>	
                                    <?php } else { ?>
                                        <tr><td colspan="6">No records found</td></tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </section>
                    </div>
                </section>
            </div>
        </div>



        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        Scheduled Jobs
                        <a href="<?php echo SITE_URL ?>sitters/jobs/view/scheduled" class="label label-success pull-right">View all Scheduled Jobs</a>
                    </header>
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th>Job No.</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Children</th>
                                        <th class="text-right">Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($this->confirmedJobs['rows'])) { ?>

                                        <?php foreach ($this->confirmedJobs['rows'] as $job) { ?>
                                            <tr>
                                                <td ><a href="<?php echo SITE_URL . 'sitters/preview/job/' . $job['job_id'] ?>"><?php echo $this->jobnumber($job['job_id']) ?></a></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_start_date'])) ?></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_end_date'])) ?></td>

                                                <?php
                                                if (!empty($job['actual_child_count'])) {
                                                    $children = $job['actual_child_count'];
                                                } else {
                                                    $children = $job['child_count'];
                                                }
                                                ?>

                <!--                                                <td> <?php //echo count($job['children'])  ?></td>-->

                                                <td> <?php echo $children ?></td>

                                                <td class="numeric"> <?php echo money_format('%.2n', ($job['rate'])?$job['rate']:$job['sitter_rate_pre']) ?></td>

                                            </tr>

                                        <?php } ?>	
                                    <?php } else { ?>
                                        <tr><td colspan="6">No records found</td></tr>
                                    <?php } ?>



                                </tbody>
                                </tbody>
                            </table>
                        </section>
                    </div>
                </section>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        Active Jobs
                        <a href="<?php echo SITE_URL ?>sitters/jobs/view/active" class="label label-success pull-right">View all Active Jobs</a>
                    </header>
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th>Job No.</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Children</th>
                                        <th class="text-right">Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($this->activeJobs['rows'])) { ?>

                                        <?php foreach ($this->activeJobs['rows'] as $job) { ?>
                                            <tr>
                                                <td ><a href="<?php echo SITE_URL . 'sitters/preview/job/' . $job['job_id'] ?>"><?php echo $this->jobnumber($job['job_id']) ?></a></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_start_date'])) ?></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_end_date'])) ?></td>

                                                <?php
                                                if (!empty($job['actual_child_count'])) {
                                                    $children = $job['actual_child_count'];
                                                } else {
                                                    $children = $job['child_count'];
                                                }
                                                ?>

                <!--                                                <td> <?php //echo count($job['children'])  ?></td>-->

                                                <td> <?php echo $children ?></td>

                                                <td class="numeric"> <?php echo money_format('%.2n', ($job['rate'])?$job['rate']:$job['sitter_rate_pre']) ?></td>

                                            </tr>

                                        <?php } ?>	
                                    <?php } else { ?>
                                        <tr><td colspan="6">No records found</td></tr>
                                    <?php } ?>



                                </tbody>
                                </tbody>
                            </table>
                        </section>
                    </div>
                </section>
            </div>
        </div>



        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        Completed Jobs
                        <a href="<?php echo SITE_URL ?>sitters/jobs/view/completed" class="label label-success pull-right">View all Completed Jobs</a>
                    </header>
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th>Job No.</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Children</th>
                                        <th class="text-right">Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($this->completedJobs['rows'])) { ?>

                                        <?php foreach ($this->completedJobs['rows'] as $job) { ?>
                                            <tr>
                                                <td><a href="<?php echo SITE_URL . 'sitters/preview/job/' . $job['job_id'] ?>"><?php echo $this->jobnumber($job['job_id']) ?></a></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_start_date'])) ?></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_end_date'])) ?></td>

                                                <?php
                                                if (!empty($job['actual_child_count'])) {
                                                    $children = $job['actual_child_count'];
                                                } else {
                                                    $children = $job['child_count'];
                                                }
                                                ?>



                                                <td > <?php echo $children; ?></td>

                                                <td class="numeric"> <?php echo money_format('%.2n',  ($job['rate'])?$job['rate']:$job['sitter_rate_pre'])?></td>

                                            </tr>

                                        <?php } ?>	
                                    <?php } else { ?>
                                        <tr><td colspan="6">No records found</td></tr>
                                    <?php } ?>

                                </tbody>
                            </table>
                        </section>
                    </div>
                </section>
            </div>
        </div>
        
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        Closed Jobs
                        <a href="<?php echo SITE_URL ?>sitters/jobs/view/closed" class="label label-success pull-right">View all Closed Jobs</a>
                    </header>
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th>Job No.</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Children</th>
                                        <th class="text-right">Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($this->closedJobs['rows'])) { ?>

                                        <?php foreach ($this->closedJobs['rows'] as $job) { ?>
                                            <tr>
                                                <td><a href="<?php echo SITE_URL . 'sitters/preview/job/' . $job['job_id'] ?>"><?php echo $this->jobnumber($job['job_id']) ?></a></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_start_date'])) ?></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_end_date'])) ?></td>

                                                <?php
                                                if (!empty($job['actual_child_count'])) {
                                                    $children = $job['actual_child_count'];
                                                } else {
                                                    $children = $job['child_count'];
                                                }
                                                ?>



                                                <td > <?php echo $children; ?></td>

                                                <td class="numeric"> <?php echo money_format('%.2n',  ($job['rate'])?$job['rate']:$job['sitter_rate_pre'])?></td>

                                            </tr>

                                        <?php } ?>	
                                    <?php } else { ?>
                                        <tr><td colspan="6">No records found</td></tr>
                                    <?php } ?>

                                </tbody>
                            </table>
                        </section>
                    </div>
                </section>
            </div>
        </div>
        
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        Cancelled Jobs
                        <a href="<?php echo SITE_URL ?>sitters/jobs/view/cancelled" class="label label-success pull-right">View all Cancelled Jobs</a>
                    </header>
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>
                                        <th>Job No.</th>
                                        <th>Start Date/Time</th>
                                        <th>End Date/Time</th>
                                        <th>Children</th>
                                        <th class="text-right">Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (!empty($this->cancelledJobs['rows'])) { ?>

                                        <?php foreach ($this->cancelledJobs['rows'] as $job) { ?>
                                            <tr>
                                                <td><a href="<?php echo SITE_URL . 'sitters/preview/job/' . $job['job_id'] ?>"><?php echo $this->jobnumber($job['job_id']) ?></a></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_start_date'])) ?></td>
                                                <td> <?php echo date(DATETIME_FORMAT, strtotime($job['job_end_date'])) ?></td>

                                                <?php
                                                if (!empty($job['actual_child_count'])) {
                                                    $children = $job['actual_child_count'];
                                                } else {
                                                    $children = $job['child_count'];
                                                }
                                                ?>



                                                <td > <?php echo $children; ?></td>

                                                <td class="numeric"> <?php echo money_format('%.2n', ($job['rate'])?$job['rate']:$job['sitter_rate_pre'])?></td>

                                            </tr>

                                        <?php } ?>	
                                    <?php } else { ?>
                                        <tr><td colspan="6">No records found</td></tr>
                                    <?php } ?>

                                </tbody>
                            </table>
                        </section>
                    </div>
                </section>
            </div>
        </div>

        <!--  <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        From our blog
                        <a class="label label-success pull-right" href="http://www.hamptonsbabysitters.com/blog" title="Go to blog page"  >Read More&nbsp;»</a>
                    </header>

                    <?php //echo $this->blog() ?>
                </section>
            </div>
        </div>-->

        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->
