
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                      Password

                    </header>

                    <?php
                    if ((isset($this->successMsg)) && (!empty($this->successMsg))) {
                        ?>
                        <div  >
                            <p style="color:#3c763d;margin-left:15px">
                                <?php echo $this->successMsg; ?>
                            </p>
                        </div>
                    <?php } ?> 

                    <?php
                    if ((isset($this->errorMsg)) && (!empty($this->errorMsg))) {
                        ?>
                        <div  >
                            <p style="color:#a94442;margin-left:15px">
                                <?php echo $this->errorMsg; ?>
                            </p>
                        </div>
                    <?php } ?> 


                    <div class="panel-body">
                        
                       </br>

                        <div class=" form">
                            <form class="cmxform form-horizontal tasi-form" id="changePasswordForm" method="post" >
                                <div class="form-group ">
                                    <label for="cname" class="control-label col-lg-2">Current Password</label>
                                    <div class="col-lg-4">
                                        <input class=" form-control"  type="password" name="oldpassword" id="oldpassword"  />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-2">New Password
                                    </label>
                                    <div class="col-lg-4">
                                         <input class=" form-control" type="password" name="newpassword" id="newpassword"  />
                                    </div>
                                </div>
                                 <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-2">Confirm password
                                    </label>
                                    <div class="col-lg-4">
                                         <input class=" form-control" type="password" name="repeatpassword" id="repeatpassword"  />
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                    <input type="submit" name="changePassword" value="Change Password" class="btn btn-danger">

                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

<script src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>

<script>
$(document).ready(function() {
	// validate signup form on keyup and submit
	
	var validator = $("#changePasswordForm").validate({
		rules: {			
			oldpassword: {
				required: true
				
			},
			newpassword: {
				required: true,
				minlength: 6
			},
			repeatpassword: {
				required: true,
				minlength: 6,
				equalTo: "#newpassword"
			}

			
		},
		messages: {
			oldpassword: {
				required: "Provide a password",
				rangelength: jQuery.format("Enter at least {0} characters")
			},
			newpassword: {
				required: "Provide a password",
				rangelength: jQuery.format("Enter at least {0} characters")
			},
			repeatpassword: {
				required: "Re-enter your password",
				minlength: jQuery.format("Enter at least {0} characters"),
				equalTo: "Enter the same password as above"
			}

		},
		// the errorPlacement has to take the table layout into account
		errorPlacement: function(error, element) {
			//alert(element.attr('type'));
			
				error.appendTo( element.parent());
				
			
		},
		// specifying a submitHandler prevents the default submit, good for the demo
		submitHandler: function() {
			//$("#login").submit();
			
			document.getElementById('changePasswordForm').submit();
		
		},
		// set this class to error-labels to indicate valid fields
		success: function(label) {
			// set &nbsp; as text for IE
			//checkCredits();
			label.html("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;").addClass("checked");
		}
	});});
	</script>


