
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        <span class="table_heading">Refer a Friend</span>
                    </header>

                    <?php
                    if ((isset($this->successMsg)) && (!empty($this->successMsg))) {
                        ?>
                        <div  >
                            <p style="color:#3c763d;margin-left:15px">
                                <?php echo $this->successMsg; ?>
                            </p>
                        </div>
                    <?php } ?> 

                    <?php
                    if ((isset($this->errorMsg)) && (!empty($this->errorMsg))) {
                        ?>
                        <div  >
                            <p style="color:#a94442;margin-left:15px">
                                <?php echo $this->errorMsg; ?>
                            </p>
                        </div>
                    <?php } ?> 


                    <div class="panel-body">
                        <span>Send an email to anyone you know who might need a babysitter</span>
                        </br>   </br>

                        <div class=" form">
                            <form class="cmxform form-horizontal tasi-form" id="referForm" method="post" >
                                <div class="form-group ">
                                    <label for="cname" class="control-label col-lg-2"><span style="font-weight: normal;">Recipient's Email</span> </label>
                                    <div class="col-lg-4">
                                        <input class=" form-control" placeholder="john@example.com,sam@example.com" type="text" name="emails" id="email"  />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-2"><span style="font-weight: normal;">Message</span>
                                    </label>
                                    <div class="col-lg-4">
                                        <textarea class="form-control" name="message" placeholder="type your message here"></textarea>

                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <input type="submit" name="send" value="Send Message" class="btn btn-danger">

                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

<script src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>

<script type="text/javascript">
    jQuery.validator.addMethod(
            "multiemail",
            function (value, element) {
                var email = value.split(/[;,]+/); // split element by , and ;
                valid = true;
                for (var i in email) {
                    value = email[i];
                    valid = valid && jQuery.validator.methods.email.call(this, $.trim(value), element);
                }
                return valid;
            },
            jQuery.validator.messages.multiemail
            );

</script>
<script type="text/javascript">
    $(document).ready(function () {
        var validator = $("#referForm").validate({
            rules: {
                emails: {
                    required: true,
                    multiemail: true

                }

            },
            messages: {
                emails: {
                    required: "Please Enter the email.",
                    multiemail: 'You must enter a valid email, or comma separate multiple'

                }

            }

            // specifying a submitHandler prevents the default submit, good for the demo

            // set this class to error-labels to indicate valid fields

        });






    });</script>

