<?php //print_r($this->templates1);die;   ?>
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        Site  Settings

                    </header>

                    <div class="panel-body">

                        </br>

                        <div class=" form">
                            <form class="cmxform form-horizontal tasi-form" id="setting" method="post" >
                                <div class="form-group ">
                                    <label for="cname" class="control-label col-lg-3">Site Name</label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control"  name="SITE_NAME" value="<?php echo $this->site['SITE_NAME']['value'] ?>" />                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-3">Choose Template 
                                    </label>
                                    <div class="col-lg-6 radios">
                                        <?php foreach ($this->templates as $temp) { ?>
                                            <label class="label_radio">

                                                <input class="form-control" type="radio"  name="SITE_USER_TEMPLATE" <?php echo ($temp == $this->site['SITE_USER_TEMPLATE']['value']) ? 'checked="checked"' : '' ?> value="<?php echo $temp ?>"/><?php echo ucwords($temp); ?>
                                            </label>
                                        <?php } ?>
                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-3">Environment
                                    </label>
                                    <div class="col-lg-6">
                                        <select name="ENVIRONMENT" class="form-control">
                                            <option>Development</option>
                                            <option>Staging</option>
                                            <option>Production</option>
                                        </select>                                    
                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-3">Time Zone
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control"  name="TIMEZONE" value="<?php echo $this->site['TIMEZONE']['value'] ?>" />                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-3">Date Format
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control"  name="DATE_FORMAT" value="<?php echo $this->site['DATE_FORMAT']['value'] ?>" />                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-3">Date Time Format
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control"  name="DATETIME_FORMAT" value="<?php echo $this->site['DATETIME_FORMAT']['value'] ?>" />                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-3">Thumb Image Size
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control"  name="THUMB_SIZE" value="<?php echo $this->site['THUMB_SIZE']['value'] ?>" />                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-3">Large Image Size
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control"  name="LARGE_SIZE" value="<?php echo $this->site['LARGE_SIZE']['value'] ?>" />                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <input class="btn btn-danger" type="submit" name="save" value="Save" />
                                        <input class="btn btn-default" type="button" onclick="history.back();" name="reset" value="Back" />

                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

<script src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>

<script>
                                            $(document).ready(function () {
                                                // validate signup form on keyup and submit

                                                var validator = $("#setting").validate({
                                                    rules: {
                                                        SITE_NAME: {
                                                            required: true

                                                        },
                                                        TIMEZONE: {
                                                            required: true
                                                           
                                                        },
                                                        DATE_FORMAT: {
                                                            required: true
                                                            
                                                        },
                                                          DATETIME_FORMAT: {
                                                            required: true
                                                            
                                                        },
                                                        THUMB_SIZE: {
                                                            required: true
                                                            
                                                        },
                                                        
                                                        LARGE_SIZE: {
                                                            required: true
                                                            
                                                        }


                                                    },
                                                    messages: {
                                                        SITE_NAME: {
                                                            required: "Provide a Site Name"
                                                        },
                                                        TIMEZONE: {
                                                            required: "Provide a Time Zone"
                                                        },
                                                        DATE_FORMAT: {
                                                            required: "Provide Date Format"
                                                            
                                                        },
                                                         DATETIME_FORMAT: {
                                                            required: "Provide DateTime Format"
                                                            
                                                        },
                                                        
                                                         THUMB_SIZE: {
                                                            required: "Provide Thumb Size"
                                                            
                                                        },
                                                         LARGE_SIZE: {
                                                            required: "Provide Large Size"
                                                            
                                                        }

                                                    },
                                                    // the errorPlacement has to take the table layout into account
                                                    errorPlacement: function (error, element) {
                                                        //alert(element.attr('type'));

                                                        error.appendTo(element.parent());


                                                    },
                                                    // specifying a submitHandler prevents the default submit, good for the demo
                                                    
                                                });
                                            });
</script>


