
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading clearfix">
                        Setting
                    </header>


                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                    <tr>

                                        <th>Template Name </th>
                                        <th>Actions </th>
                                    <tr>

                                </thead>
                                <?php foreach ($this->mailTemplates as $temp) { ?>

                                    <tbody>
                                        <tr>
                                            <td><?php echo $temp['label'] ?></td>

                                            <td class="text-center">	
                                                <a  class="btn btn-primary btn-xs" href="<?php echo ADMIN_URL.'settings/mailmodify/id/'.$temp['mail_id']?>"><i class="fa fa-pencil"></i>

                                            </td>	
                                        </tr>


                                    <?php } ?></tbody>
                            </table>

                        </section>
                    </div>


                </section>
            </div>
        </div>

        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->


<script>
    function saveRate(th) {
        //alert(th.value);
        //alert(th.name);
        $.ajax({url: "<?php echo ADMIN_URL . 'client/events/' ?>",
            data: {rate: th.value, saverate: 'rate', job_id: $(th).attr('rel')}, success: function (data) {
            }
        });
    }


    function printpage()
    {
        window.print()
    }

</script>