<?php //print_r($this->templates1);die;       ?>
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        Sitter Preference

                    </header>

                    <div class="panel-body">

                        </br>

                        <?php if (!empty($this->preferences)) { ?>
                            <table class="table table-bordered table-striped table-condensed cf">
                                <?php foreach ($this->preferences as $group) { ?>
                                    <tr>
                                        <td class="first"><?php echo $group['label'] ?></td>
                                        <td><?php
                                            if (!empty($group['prefer']))
                                                foreach ($group['prefer'] as $p) {

                                                    echo "<div class='col-sm-3 pref-field'><span class='clearfix' id='outer{$p['prefer_id']}'><input class='form-control' type='text' onkeyup='updatePrefer(this,{$p['prefer_id']})' name='prefer' value='{$p['prefer_name']}' />" . ' <a class="btn btn-danger btn-xs fa fa-trash-o" onclick="deletePrefer(' . $p['prefer_id'] . ');" ></a></span> </div>';
                                                }
                                            ?>
                                        </td>
                                    </tr><?php } ?>
                            </table>




                        <?php } ?>

                        <h3>Add New Preference</h3>
                        <div class='clearfix'></div>


                        <form  class="cmxform form-horizontal tasi-form" id="preferenceform" enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->preferForm->getAction(); ?>">
                            <dl class="zend_form">

                                <div class="form-group ">
                                    <label for="cname" class="control-label col-lg-2">Add To </label>
                                    <div class="col-lg-4">
                                        <select name="group_id" class="form-control">
                                            <?php foreach ($this->preferences as $group) { ?>
                                                <option value="<?php echo $group['group_id'] ?>"><?php echo $group['label'] ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label for="cname" class="control-label col-lg-2">Preference Name </label>
                                    <div class="col-lg-4">
                                        <input class="form-control" type="text" name="prefer_name" id="prefer_name" value="<?php echo $this->preferForm->prefer_name->getValue() ?>">
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">

                                        <input class="btn btn-danger" type="submit" name="create" id="create" value="Create">
                                    </div>
                                </div>

                            </dl>
                        </form>

                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

<script src="<?php echo SITE_URL ?>resource/js/jquery-validator.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var validator = $("#preferenceform").validate({
            rules: {
                prefer_name: {
                    required: true



                }

            },
            messages: {
                prefer_name: {
                    required: "Enter the Preference name."

                }

            }

        });




        //$("#login").valid();


    });</script>
<script>
    function deletePrefer(preferId) {
        $.ajax({
            url: "<?php echo ADMIN_URL . 'settings/preference/' ?>",
            data: {deleteprefer: preferId},
            success: function (data) {
                if (data == 'true') {
                    $("#outer" + preferId).remove();
                } else {
                    alert('Preference cannot be deleted now! This preference is used by current jobs.');
                }
            }


        });
    }
    function updatePrefer(th, preferId) {
        $.ajax({
            url: "<?php echo ADMIN_URL . 'settings/preference/' ?>",
            data: {updateprefer: preferId, value: th.value},
            success: function (data) {

            }


        });
    }

</script>