				      <li><a <?php echo  $this->actionName=='index'?'class="active"' :''?> href="<?php echo ADMIN_URL.'settings/'?>">Site </a></li>
 <li><a <?php echo  $this->actionName=='preference'?'class="active"' :''?> href="<?php echo ADMIN_URL.'settings/preference/'?>">Sitter Preferences</a></li>
				      <li><a <?php echo  $this->actionName=='mail'||$this->actionName=='mailmodify'?'class="active"' :''?> href="<?php echo ADMIN_URL.'settings/mail'?>">Mail</a></li>
